Repository realm/realm-js, pull requests merged in 2018-04, with the labels that each got.

#1723 Stop Permissions being redefined and breaking Jest
  lib/extensions.js
Labels: T:Bug

#1734 Fix named linking object queries across classes
  CHANGELOG.md
  src/js_results.hpp
  tests/js/linkingobjects-tests.js
  tests/js/schemas.js
Labels: T:Bug

#1715 Added `writeCopyTo` functionality
  docs/realm.js
  lib/index.d.ts
  src/js_realm.hpp
  tests/js/realm-tests.js
Labels: T:Enhancement

#1749 Updating to Realm Sync 2.2.17
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#1731 Stringify fetch body in logout
  CHANGELOG.md
  lib/user-methods.js
Labels: T:Bug

#1744 Add Subscription import to browser/index.js and register type converter
  lib/browser/index.js
Labels: T:Bug

#1755 Updating change log (forgot in PR #1744).
  CHANGELOG.md
Labels: T:Internal

#1766 Kneth/rn logout
  CHANGELOG.md
  lib/browser/user.js
Labels: T:Bug
