Repository realm/realm-js, pull requests merged in 2018-02, with the labels that each got.

#1659 Updating to Realm Sync 2.2.10
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#1664 Fixing objectForPrimaryKey return type
  lib/index.d.ts
Labels: T:Doc

#1666 Updating to Realm Sync 2.2.11
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#1665 Test of: Multiple list of primitive types
  CHANGELOG.md
  dependencies.list
  tests/js/index.js
  tests/js/list-tests.js
  tests/js/nested-list-helper.js
  tests/js/schemas.js
  tests/js/session-tests.js
Labels: O:User PE/EE, T:Bug

#1672 Don't include the downloaded files in package
  vendor/.npmignore
Labels: T:Internal
