Repository realm/realm-js, pull requests merged in 2018-12, with the labels that each got.

#2157 Fix missing method when debugging React Native
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  lib/browser/index.js
  lib/browser/rpc.js
  src/rpc.cpp
Labels: T:Bug-Crash

#2158 Adds support for reconnecting manually
  CHANGELOG.md
  docs/sync.js
  lib/browser/index.js
  lib/browser/rpc.js
  lib/index.d.ts
  src/js_sync.hpp
  src/rpc.cpp
  tests/js/session-tests.js
Labels: T:Enhancement

#2160 Updating to Sync v3.14.1
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#2161 Cleaning up mistakes in CHANGELOG.md
  CHANGELOG.md
Labels: T:Internal

#2159 Add support for Gradle 5.0
  CHANGELOG.md
  examples/ReactExample/android/app/build.gradle
  examples/ReactExample/android/build.gradle
  examples/ReactExample/android/gradle/wrapper/gradle-wrapper.properties
  package.json
  react-native/android/analytics_template
  react-native/android/build.gradle
  react-native/android/gradle/wrapper/gradle-wrapper.properties
  react-native/android/publish_android_template
  react-native/android/src/main/java/io/realm/react/RealmReactModule.java
Labels: T:Bug

#2171 Upgrading core to v5.12.5 and sync to v3.14.3
  CHANGELOG.md
  dependencies.list
Labels: T:Bug

#2173 revert #2078
  CHANGELOG.md
  src/RealmJS.xcodeproj/project.pbxproj
Labels: T:Bug

#2174 Remove a space in the changelog template
  scripts/changelog-header.sh
Labels: T:Internal

#2175 Fix automatic conversion of Auth to Realm URLs
  CHANGELOG.md
  lib/user-methods.js
  tests/js/user-tests.js
Labels: T:Enhancement

#2177 Updated React Native Android build tools
  CHANGELOG.md
  react-native/android/publish_android_template
Labels: T:Enhancement

#2178 Upgrade to core v5.12.6 and sync v3.14.6
  CHANGELOG.md
  dependencies.list
  tests/js/object-tests.js
Labels: T:Bug
