Repository realm/realm-js, pull requests merged in 2018-11, with the labels that each got.

#2092 Node 10 support
  CHANGELOG.md
  binding.gyp
  dependencies.list
  package-lock.json
  package.json
  packaging/node-pre-gyp/base-image/Dockerfile
  realm.gypi
  scripts/build-node-pre-gyp.ps1
  scripts/build-node-pre-gyp.sh
  scripts/download-realm.js
  src/js_class.hpp
  src/js_list.hpp
  src/js_realm.hpp
  src/js_realm_object.hpp
  src/js_results.hpp
  src/js_sync.hpp
  src/js_util.hpp
  src/jsc/jsc_class.hpp
  src/node/node_class.hpp
  src/node/node_return_value.hpp
  src/node/node_types.hpp
  src/rpc.cpp
  src/rpc.hpp
Labels: T:Enhancement

#2105 API docs
  docs/sync.js
Labels: T:Doc

#2108 Give the app a chance to disable analytics
  CHANGELOG.md
  lib/index.js
  lib/submit-analytics.js
  package-lock.json
  package.json
Labels: T:Bug

#2110 Fix type definitions - generics return <T & Object>
  CHANGELOG.md
  lib/index.d.ts
Labels: T:Bug

#2116 Add lower bound when refreshing tokens.
  CHANGELOG.md
  lib/user-methods.js
Labels: T:Enhancement

#2121 Check the correct name when adding permissions object schemas to the schema
  CHANGELOG.md
  lib/extensions.js
  tests/js/session-tests.js
Labels: T:Bug

#2124 Add support for uploading. and downloading changes easily
  CHANGELOG.md
  Jenkinsfile
  docs/sync.js
  lib/extensions.js
  lib/index.d.ts
  src/js_sync.hpp
  tests/js/session-tests.js
Labels: T:Enhancement

#2127 Protect the context from being GCed
  CHANGELOG.md
  src/js_realm.hpp
Labels: T:Bug-Crash

#2151 Add better error message for wrong Realm types
  CHANGELOG.md
  lib/extensions.js
  lib/index.d.ts
  src/js_realm.hpp
  tests/js/realm-tests.js
Labels: T:Enhancement

#2152 Prepare RealmJS 2.20.1
  CHANGELOG.md
  dependencies.list
  package-lock.json
  package.json
  src/RealmJS.xcodeproj/project.pbxproj
Labels: T:Internal
