Repository realm/realm-js, pull requests merged in 2018-06, with the labels that each got.

#1846 [2.8.0] Bump version
  CHANGELOG.md
  dependencies.list
  package.json
  src/RealmJS.xcodeproj/project.pbxproj
Labels: T:Internal

#1848 Upgrading to Realm Sync v3.5.1
  CHANGELOG.md
  dependencies.list
Labels: P:0 EXPEDITE, T:Internal

#1850 These days Realm Sync for Linux has a new home.
  CHANGELOG.md
  scripts/download-realm.js
Labels: T:Internal

#1858 Upgrading to Realm Sync 3.5.2
  CHANGELOG.md
  dependencies.list
Labels: P:0 EXPEDITE, T:Internal

#1852 Better representation of array of primitive types for (#1847).
  CHANGELOG.md
  src/js_schema.hpp
  tests/js/list-tests.js
Labels: T:Bug

#1859 Upgrading to Realm Core v5.6.1
  CHANGELOG.md
  dependencies.list
  tests/js/query-tests.js
Labels: T:Internal

#1863 Fix building against realm-sync checkout
  realm.gypi
Labels: T:Internal

#1872 Upgrading to Realm Sync v3.5.5
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#1874 Add support for creating template objects
  CHANGELOG.md
  docs/realm.js
  lib/extensions.js
  lib/index.d.ts
  tests/js/realm-tests.js
Labels: T:Enhancement

#1887 Upgrading sync and core
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#1890 Upgrading to Realm Sync 3.5.8
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#1894 Fixing the class names of the permission classes
  CHANGELOG.md
  docs/permission.js
Labels: T:Doc

#1892 Adding getters to debugging support of Realm.Sync.User
  CHANGELOG.md
  lib/browser/user.js
Labels: T:Internal

#1898 Expose custom HTTP headers in sync configuration
  CHANGELOG.md
  docs/sync.js
  lib/index.d.ts
  src/js_sync.hpp
  tests/js/session-tests.js
Labels: T:Enhancement
