Repository realm/realm-js, pull requests merged in 2018-09, with the labels that each got.

#2005 Added 'removeAllListeners()' to the support library for React Native debugging (#479)
  CHANGELOG.md
  lib/browser/subscription.js
Labels: T:Bug

#2019 Add support for sync pause/resume
  CHANGELOG.md
  docs/sync.js
  lib/browser/session.js
  lib/index.d.ts
  src/js_sync.hpp
  tests/js/session-tests.js
Labels: T:Feature

#2002 Redesign user auth
  CHANGELOG.md
  docs/sync.js
  lib/extensions.js
  lib/index.d.ts
  lib/user-methods.js
  tests/js/admin-user-helper.js
  tests/js/download-api-helper.js
  tests/js/encryption-tests.js
  tests/js/nested-list-helper.js
  tests/js/object-id-tests.js
  tests/js/partial-sync-api-helper.js
  tests/js/permission-tests.js
  tests/js/session-tests.js
  tests/js/user-tests.js
  tests/package-lock.json
Labels: Breaking, T:Enhancement

#2020 Fix memory corruption in `writeCopyTo`.
  CHANGELOG.md
  src/js_realm.hpp
  tests/js/realm-tests.js
Labels: T:Bug

#2022 Preparing v2.16.0-rc.1
  CHANGELOG.md
  docs/sync.js
  lib/browser/session.js
  lib/index.d.ts
  src/js_sync.hpp
  tests/js/session-tests.js
Labels: T:Internal

#2013 Fixed the type definition for Realm.Permissions.User
  lib/index.d.ts
Labels: T:Bug

#1997 add changelog template during release
  scripts/publish.sh
Labels: T:Internal

#2026 Forgot changelog entry in PR
  CHANGELOG.md
Labels: T:Internal

#2033 Fix build on Visual Studio 2017 15.8
  target_defaults.gypi
Labels: T:Internal

#2032 Support ASDF shims
  CHANGELOG.md
  src/RealmJS.xcodeproj/project.pbxproj
Labels: T:Enhancement

#2027 Adding permission schema for query based sync
  CHANGELOG.md
  lib/extensions.js
  lib/user-methods.js
  src/js_realm.hpp
  tests/js/permission-tests.js
  tests/js/session-tests.js
Labels: T:Bug-Crash

#2035 Preparing 2.16.0
  CHANGELOG.md
Labels: T:Internal

#2040 Logging in using an admin token should be synchronous
  CHANGELOG.md
  lib/user-methods.js
  tests/js/user-tests.js
Labels: T:Bug

#2034 2.17.x
  CHANGELOG.md
  Jenkinsfile
  dependencies.list
  package.json
  src/RealmJS.xcodeproj/project.pbxproj
Labels: T:Internal
