Repository realm/realm-js, pull requests merged in 2018-08, with the labels that each got.

#1943 Update the query tutorial
  docs/tutorials/query-language.md
Labels: T:Doc

#1949 Upgrading to Realm Sync v3.8.7
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#1953 Realm Sync v3.8.8
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#1957 Fix security vulnerabilities
  CHANGELOG.md
  package-lock.json
  package.json
Labels: T:Internal

#1941 Disable GNU dialect when building for Node 10 with GCC
  target_defaults.gypi
Labels: T:Internal

#1964 Upgrading to Realm Sync v3.8.10
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#1968 Improve handling of parallel CI jobs.
  CHANGELOG.md
  scripts/download-realm.js
Labels: T:Internal

#1973 Upgrading to Realm Sync 3.8.11
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#1975 Update devtoolset from 3 to 6
  CHANGELOG.md
  packaging/node-pre-gyp/base-image/Dockerfile
  packaging/node-pre-gyp/build-image/inside/docker-entrypoint.sh
Labels: T:Internal

#1984 Upgrading to Realm Sync v3.9.1
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#1985 A schema is required when Realm is opened in a query-based sync situation
  CHANGELOG.md
  docs/realm.js
  lib/extensions.js
  src/js_realm.hpp
  tests/js/object-id-tests.js
  tests/js/permission-tests.js
  tests/js/session-tests.js
Labels: T:Bug-Crash

#1994 Forgot the reference to the issue in the change log
  CHANGELOG.md
Labels: T:Internal

#1996 Expose user serialize and deserialize methods
  CHANGELOG.md
  docs/sync.js
  lib/index.d.ts
  lib/user-methods.js
  package-lock.json
  tests/js/user-tests.js
  tests/package.json
Labels: G:Rangers, T:Enhancement

#1998 Slightly rephrasing changelog entry
  CHANGELOG.md
Labels: T:Doc
