Repository realm/realm-js, pull requests merged in 2018-05, with the labels that each got.

#1776 Merge 2.2.x into master
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#1778 Update to sync 3.3.0
  CHANGELOG.md
  dependencies.list
  realm.gypi
Labels: T:Internal

#1780 Track Realms seen in the notifier by id rather than path
  lib/notifier.js
Labels: T:Bug

#1713 Fixing TS definition for open_ssl_verify_callback.
  CHANGELOG.md
  lib/index.d.ts
Labels: T:Bug

#1791 Prepare Realm JS 2.5.0
  CHANGELOG.md
  dependencies.list
  package.json
  src/RealmJS.xcodeproj/project.pbxproj
Labels: T:Internal

#1790 Group SSL configuration options in a new config object
  CHANGELOG.md
  docs/realm.js
  docs/sync.js
  lib/index.d.ts
  src/js_sync.hpp
Labels: T:Enhancement

#1799 Adding entry which I forgot to add during release
  CHANGELOG.md
Labels: T:Internal

#1833 Preparing 2.7.0
  CHANGELOG.md
  dependencies.list
  docs/realm.js
  package.json
  src/RealmJS.xcodeproj/project.pbxproj
Labels: T:Internal

#1816 Fixing TypeScript definition of `Realm.objects()` and `Realm.objectFrPrimaryKey()`
  CHANGELOG.md
  lib/index.d.ts
Labels: T:Bug
