Repository realm/realm-js, pull requests merged in 2018-03, with the labels that each got.

#1683 Updating to Realm Sync 2.2.14
  CHANGELOG.md
  dependencies.list
  scripts/test.sh
Labels: T:Internal

#1684 Updating to Realm Sync 2.2.15
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#1694 Deprecated setFeatureToken().
  CHANGELOG.md
  lib/extensions.js
  lib/index.d.ts
Labels: T:Internal

#1695 Stop worker being redefined and breaking Jest
  lib/index.js
Labels: T:Enhancement

#1698 Updating to Realm Sync 3.0.0-rc.1 and Realm Core 5.4.0.
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#1693 Default sync realm
  CHANGELOG.md
  docs/realm.js
  lib/extensions.js
  lib/index.d.ts
  package.json
  tests/js/realm-tests.js
  tests/js/session-tests.js
Labels: T:Feature

#1696 Revoke refresh token upon logout.
  CHANGELOG.md
  lib/user-methods.js
  src/js_sync.hpp
Labels: T:Enhancement

#1660 Preliminary work for queries over named backlinks
  CHANGELOG.md
  src/js_results.hpp
  tests/js/linkingobjects-tests.js
Labels: T:Enhancement

#1704 Kneth/allow partial in urls
  CHANGELOG.md
  lib/index.d.ts
  src/js_sync.hpp
  tests/js/session-tests.js
Labels: T:Internal

#1707 Updating API docs and TS definitions (closes #1770).
  docs/collection.js
  docs/sync.js
  lib/index.d.ts
Labels: T:Doc

#1709 Adding optional user as argument to Realm.automaticSyncConfiguration.
  CHANGELOG.md
  docs/realm.js
  lib/extensions.js
  lib/index.d.ts
  tests/js/session-tests.js
Labels: T:Enhancement

#1718 Throttle HTTP requests made to the auth server
  CHANGELOG.md
  dependencies.list
  docs/tutorials/query-language.md
  lib/index.js
  lib/user-methods.js
  package.json
  src/RealmJS.xcodeproj/project.pbxproj
Labels: P:0 EXPEDITE, T:Bug

#1717 Throttle HTTP requests made to the auth server
  CHANGELOG.md
  lib/user-methods.js
Labels: P:0 EXPEDITE, T:Bug

#1719 Adding compatibility info
  .github/pull_request_template.md
  CHANGELOG.md
Labels: T:Internal

#1724 Avoid leaking realms when an error occurs within an event handler
  lib/notification-worker.js
  lib/notifier.js
Labels: T:Bug
