Repository realm/realm-js, pull requests merged in 2018-10, with the labels that each got.

#2044 Aligned release note template
  scripts/changelog-header.sh
Labels: T:Internal

#2036 Align permission API's with Java/Swift
  CHANGELOG.md
  docs/permission.js
  docs/realm.js
  lib/browser/index.js
  lib/extensions.js
  lib/index.d.ts
  src/js_realm.hpp
  src/js_realm_object.hpp
  tests/js/permission-tests.js
  tests/js/realm-tests.js
Labels: P:1 Required, T:Enhancement

#2045 Handle sync config in Realm.deleteFile
  CHANGELOG.md
  package-lock.json
  src/js_realm.hpp
  tests/js/realm-tests.js
Labels: T:Enhancement

#2048 Prepare v2.18.0
  CHANGELOG.md
Labels: T:Internal

#2051 Typo: file format 9 instead of 7
  CHANGELOG.md
  scripts/changelog-header.sh
Labels: T:Internal

#2055 Expose customQueryBasedSyncIdentifier in the sync config
  CHANGELOG.md
  docs/sync.js
  lib/index.d.ts
  package-lock.json
  src/js_sync.hpp
  tests/js/session-tests.js
Labels: G:Rangers, O:User PE/EE, T:Enhancement

#2050 Auth fixes
  CHANGELOG.md
  lib/index.d.ts
  lib/user-methods.js
  tests/js/user-tests.js
Labels: G:Rangers, T:Bug

#2054 Update changelog
  CHANGELOG.md
  scripts/changelog-header.sh
Labels: T:Internal

#2071 Don't schedule multiple token refreshes for the same user/realm
  CHANGELOG.md
  docs/sync.js
  lib/index.d.ts
  lib/user-methods.js
Labels: G:Rangers, O:User PE/EE, T:Enhancement

#2073 Preparing 2.19.0-rc.3
  CHANGELOG.md
Labels: T:Internal

#2064 Unit test for partial Realm schema updates
  tests/js/realm-tests.js
Labels: T:Test

#2084 Throw a meaningful error when refreshing a token for an invalid Realm path
  CHANGELOG.md
  lib/user-methods.js
  tests/js/encryption-tests.js
Labels: G:Rangers, O:User PE/EE, T:Enhancement
