Repository realm/realm-js, pull requests merged in 2018-07, with the labels that each got.

#1907 Fixing unsolved symbol in RN Android
  CHANGELOG.md
  react-native/android/src/main/jni/Android.mk
Labels: T:Bug

#1908 Upgrading to Realm Core v5.6.5 and Realm Sync v3.7.0
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#1884 Improve performance of `realm.create()` when running in node
  CHANGELOG.md
  src/js_object_accessor.hpp
  src/js_types.hpp
  src/jsc/jsc_object.hpp
  src/node/node_object.hpp
  src/node/node_string.hpp
  tests/js/realm-tests.js
Labels: T:Enhancement

#1912 OpenSSL isn't linked due to typing error
  CHANGELOG.md
  realm.gypi
Labels: T:Bug

#1902 initial work on getting subscriptions to work in RN debugger
  lib/browser/subscription.js
  src/rpc.cpp
Labels: T:Bug

#1922 Realm Core 5.7.1 and Realm Sync 3.8.0
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#1937 Fix Node.js 10 support
  package-lock.json
  package.json
  src/js_class.hpp
  src/js_list.hpp
  src/js_realm.hpp
  src/js_realm_object.hpp
  src/js_results.hpp
  src/js_sync.hpp
  src/js_util.hpp
  src/jsc/jsc_class.hpp
  src/node/node_class.hpp
  src/node/node_return_value.hpp
  src/node/node_types.hpp
  src/rpc.cpp
  src/rpc.hpp
Labels: T:Enhancement
