Repository realm/realm-js, pull requests merged in 2019-07, with the labels that each got.

#2424 Add test where objects are created during schema migration
  CHANGELOG.md
  src/js_realm.hpp
  tests/js/migration-tests.js
Labels: T:Bug-Crash

#2429 Update packages due to audit
  examples/ReactExample/package-lock.json
  examples/ReactExample/package.json
  integration-tests/environments/electron/package-lock.json
  integration-tests/environments/electron/package.json
  integration-tests/environments/react-native/package-lock.json
  integration-tests/environments/react-native/package.json
  tests/react-test-app/package-lock.json
  tests/react-test-app/package.json
Labels: T:Internal

#2432 Update to core v5.23.0 and sync v4.6.2
  CHANGELOG.md
  dependencies.list
Labels: T:Enhancement

#2437 Deprecate credentials.nickname
  CHANGELOG.md
  docs/sync.js
  lib/index.d.ts
  lib/user-methods.js
  scripts/test-ros-server.js
  tests/js/download-api-helper.js
  tests/js/encryption-tests.js
  tests/js/nested-list-helper.js
  tests/js/open-behavior-tests.js
  tests/js/partial-sync-api-helper.js
  tests/js/permission-tests.js
  tests/js/realm-tests.js
  tests/js/session-tests.js
  tests/js/subscription-tests.js
  tests/js/test-utils.js
Labels: Breaking, T:Enhancement

#2436 Testing some list functions
  tests/js/list-tests.js
Labels: T:Test

#2444 Update to core v5.23.1 and sync v4.6.3.
  CHANGELOG.md
  Dockerfile.android
  dependencies.list
Labels: T:Internal

#2453 Electron v4.2.x
  CHANGELOG.md
  Jenkinsfile
Labels: T:Internal

#2438 [3.0] remove deprecated stuff
  CHANGELOG.md
  docs/permission.js
  docs/realm.js
  docs/sync.js
  lib/extensions.js
  lib/index.d.ts
  lib/notifier.js
  lib/user-methods.js
  src/js_sync.hpp
  tests/js/download-api-helper.js
  tests/js/nested-list-helper.js
  tests/js/notifier-tests.ts
  tests/js/session-tests.js
  tests/js/support/ros-controller.js
  tests/js/user-tests.js
Labels: Breaking, T:Internal
