Repository realm/realm-js, pull requests merged in 2019-10, with the labels that each got.

#2548 Cleaning up console output from tests
  CHANGELOG.md
  CONTRIBUTING.md
  tests/js/adapter-tests.ts
  tests/js/index.js
  tests/js/notifier-tests.ts
  tests/js/open-behavior-tests.js
  tests/js/session-tests.js
  tests/js/support/test-object-server.js
  tests/package-lock.json
  tests/package.json
  tests/spec/helpers/realm-logging.js
  tests/spec/helpers/reporters.js
  tests/spec/unit_tests.js
Labels: T-Internal

#2558 Explaning opening behavior a bit better
  docs/sync.js
Labels: T-Doc

#2561 Adding React Test App README
  CHANGELOG.md
  tests/react-test-app/README.md
Labels: T-Doc

#2567 Update user-methods.js to check if XMLHttpRequest is defined
  CHANGELOG.md
  lib/user-methods.js
Labels: T-Bug

#2553 Update Realm Sync to v4.7.10
  CHANGELOG.md
  dependencies.list
  examples/ReactExample/package-lock.json
  examples/ReactExample/package.json
  package-lock.json
  package.json
  react-native.config.js
  src/RealmJS.xcodeproj/project.pbxproj
  tests/react-test-app/package-lock.json
  tests/react-test-app/package.json
Labels: T-Internal

#2568 Fixing return type of Realm.Sync.addListener in API doc and TS definition
  CHANGELOG.md
  docs/sync.js
  lib/index.d.ts
  lib/notifier.js
Labels: T-Doc

#2569 Deprecated list view component
  CHANGELOG.md
  examples/ReactNativeBenchmarks/benchmarks.js
  package-lock.json
  package.json
  react-native/listview.js
Labels: T-Internal
