Repository realm/realm-js, pull requests merged in 2019-11, with the labels that each got.

#2591 Fixing a couple of flaky tests.
  CHANGELOG.md
  Jenkinsfile
  tests/js/realm-tests.js
  tests/js/session-tests.js
  tests/js/subscription-tests.js
Labels: T-Internal

#2595 Fixing new flaky tests.
  lib/extensions.js
  tests/js/session-tests.js
  tests/js/subscription-tests.js
Labels: T-Internal

#2589 Mention supported node.js versions in README.md
  README.md
  tests/js/session-tests.js
Labels: T-Doc

#2600 Fix a seg.fault when calling Realm.deleteAll() after Realm.deleteModel()
  CHANGELOG.md
  docs/realm.js
  src/js_realm.hpp
  tests/js/realm-tests.js
Labels: T-Bug-Crash

#2586 Podspec
  CHANGELOG.md
  RealmJS.podspec
  lib/index.js
  package.json
  react-native.config.js
Labels: T-Enhancement

#2585 Prepare v3.4.0
  CHANGELOG.md
  dependencies.list
Labels: T-Internal

#2601 Upgrade to sync v4.8.2.
  CHANGELOG.md
  dependencies.list
Labels: T-Internal

#2604 Upgrade to sync v4.8.3.
  CHANGELOG.md
  dependencies.list
Labels: T-Internal

#2603 Upgrade React Native integration tests
  .gitignore
  CHANGELOG.md
  Jenkinsfile
  integration-tests/README.md
  integration-tests/environments/electron/README.md
  integration-tests/environments/electron/package-lock.json
  integration-tests/environments/electron/package.json
  integration-tests/environments/index.js
  integration-tests/environments/node/README.md
  integration-tests/environments/node/package-lock.json
  integration-tests/environments/node/package.json
  integration-tests/environments/react-native/.babelrc
  integration-tests/environments/react-native/.eslintrc.js
  integration-tests/environments/react-native/.eslintrc.json
  integration-tests/environments/react-native/.flowconfig
  integration-tests/environments/react-native/.gitignore
  integration-tests/environments/react-native/.prettierrc.js
  integration-tests/environments/react-native/README.md
  integration-tests/environments/react-native/android/app/_BUCK
  integration-tests/environments/react-native/android/app/build.gradle
  integration-tests/environments/react-native/android/app/build_defs.bzl
  integration-tests/environments/react-native/android/app/debug.keystore
  integration-tests/environments/react-native/android/app/proguard-rules.pro
  integration-tests/environments/react-native/android/app/src/debug/AndroidManifest.xml
  integration-tests/environments/react-native/android/app/src/main/AndroidManifest.xml
  integration-tests/environments/react-native/android/app/src/main/java/com/realmreactnativetests/MainActivity.java
  integration-tests/environments/react-native/android/app/src/main/java/com/realmreactnativetests/MainApplication.java
  integration-tests/environments/react-native/android/app/src/main/java/io/realm/tests/reactnative/MainActivity.java
  integration-tests/environments/react-native/android/app/src/main/java/io/realm/tests/reactnative/MainApplication.java
  integration-tests/environments/react-native/android/app/src/main/res/values/styles.xml
  integration-tests/environments/react-native/android/build.gradle
  integration-tests/environments/react-native/android/gradle.properties
  integration-tests/environments/react-native/android/gradle/wrapper/gradle-wrapper.jar
  integration-tests/environments/react-native/android/gradle/wrapper/gradle-wrapper.properties
  integration-tests/environments/react-native/android/gradlew
  integration-tests/environments/react-native/android/gradlew.bat
  integration-tests/environments/react-native/android/keystores/BUCK
  integration-tests/environments/react-native/android/keystores/debug.keystore.properties
  integration-tests/environments/react-native/android/settings.gradle
  integration-tests/environments/react-native/babel.config.js
  integration-tests/environments/react-native/ios/Podfile
  integration-tests/environments/react-native/ios/RealmReactNativeTests-tvOS/Info.plist
  integration-tests/environments/react-native/ios/RealmReactNativeTests.xcodeproj/project.pbxproj
  integration-tests/environments/react-native/ios/RealmReactNativeTests.xcodeproj/xcshareddata/xcschemes/RealmReactNativeTests-tvOS.xcscheme
  integration-tests/environments/react-native/ios/RealmReactNativeTests.xcodeproj/xcshareddata/xcschemes/RealmReactNativeTests.xcscheme
  integration-tests/environments/react-native/ios/RealmReactNativeTests.xcworkspace/contents.xcworkspacedata
  integration-tests/environments/react-native/ios/RealmReactNativeTests/AppDelegate.h
  integration-tests/environments/react-native/ios/RealmReactNativeTests/AppDelegate.m
  integration-tests/environments/react-native/ios/RealmReactNativeTests/Info.plist
  integration-tests/environments/react-native/ios/RealmReactNativeTests/main.m
  integration-tests/environments/react-native/ios/RealmReactNativeTestsTests/Info.plist
  integration-tests/environments/react-native/ios/RealmReactNativeTestsTests/RealmReactNativeTestsTests.m
  integration-tests/environments/react-native/metro.config.js
  integration-tests/environments/react-native/package-lock.json
  integration-tests/environments/react-native/package.json
  integration-tests/package.json
  integration-tests/tests/package-lock.json
Labels: T-Internal

#2609 Fixing React Native iOS integration tests
  CHANGELOG.md
  Jenkinsfile
  integration-tests/environments/react-native/harness/react-native-cli.js
Labels: T-Test

#2615 Test that Realm.close() can be called on a closed Realm
  CHANGELOG.md
  docs/realm.js
  tests/js/realm-tests.js
Labels: T-Internal

#2618 Call ObjectStore::table_for_object_type() only when needed
  CHANGELOG.md
  src/js_results.hpp
  tests/js/realm-tests.js
  tests/js/schemas.js
Labels: T-Enhancement

#2624 Update jsdoc (marked) and https-proxy-agent
  package-lock.json
  package.json
Labels: T-Internal
