Repository realm/realm-js, pull requests merged in 2019-06, with the labels that each got.

#2392 Fix a bug in instruction cache invalidation
  CHANGELOG.md
  dependencies.list
  package-lock.json
  package.json
  src/RealmJS.xcodeproj/project.pbxproj
  src/android/jsc_override.cpp
Labels: T:Bug-Crash

#2405 Fix ROS dependency in release notes
  CHANGELOG.md
  scripts/changelog-header.sh
Labels: T:Doc

#2402 App crashes on the first launch
  src/ios/platform.mm
Labels: T:Bug

#2412 Updating changelog for #2402
  CHANGELOG.md
Labels: T:Internal
