Repository realm/realm-js, pull requests merged in 2019-03, with the labels that each got.

#2260 TS definition and API doc for setSyncLogger
  CHANGELOG.md
  docs/sync.js
  lib/extensions.js
  lib/index.d.ts
Labels: T:Doc

#2263 Update JS docs for custom authentication
  docs/sync.js
Labels: T:Doc

#2264 Fix broken user auth functions when running in electron
  CHANGELOG.md
  Jenkinsfile
  examples/ReactExample/package.json
  lib/user-methods.js
  scripts/test.sh
  tests/electron/package-lock.json
  tests/electron/package.json
  tests/react-test-app/package-lock.json
  tests/react-test-app/package.json
Labels: T:Bug

#2275 Fix a flaky test
  tests/electron/app/main.js
  tests/electron/app/renderer.js
  tests/electron/runner.js
  tests/js/user-tests.js
Labels: T:Test

#2273 Prepare v2.25.0
  CHANGELOG.md
  dependencies.list
  package-lock.json
  package.json
  src/RealmJS.xcodeproj/project.pbxproj
Labels: T:Internal

#2277 Relaxing xcode script a bit
  integration-tests/tests/package-lock.json
  integration-tests/tests/package.json
  package-lock.json
  package.json
  scripts/download-realm.js
  src/RealmJS.xcodeproj/project.pbxproj
Labels: T:Internal

#2285 Make SessionStopPolicy a const enum
  lib/index.d.ts
Labels: T:Bug

#2286 An attempt at fixing the Electron integration tests
  CHANGELOG.md
  Jenkinsfile
  integration-tests/environments/electron/app/main.js
  integration-tests/environments/electron/app/mocha.js
  integration-tests/environments/electron/jenkins.groovy
  integration-tests/environments/electron/package-lock.json
  integration-tests/environments/electron/package.json
  integration-tests/environments/electron/rebuild-realm.sh
  integration-tests/environments/electron/runner.js
  integration-tests/package.json
Labels: T:Internal

#2214 Add RealmObject.addListener()
  CHANGELOG.md
  docs/object.js
  lib/browser/objects.js
  lib/index.d.ts
  src/js_realm_object.hpp
  tests/js/object-tests.js
Labels: T:Enhancement

#2298 Update user-methods.js to fix authentication retrying
  CHANGELOG.md
  lib/user-methods.js
Labels: T:Bug

#2283 Fixed adding property to existing class using _updateSchema
  CHANGELOG.md
  integration-tests/tests/src/dynamic-schema-updates.ts
  lib/index.d.ts
  package-lock.json
  src/js_realm.hpp
Labels: T:Invalid
