Repository realm/realm-js, pull requests merged in 2019-05, with the labels that each got.

#2355 npm updates and fixes
  CHANGELOG.md
  README.md
  package.json
  tests/package-lock.json
  tests/package.json
Labels: T:Internal

#2358 Global Notifier Add method to return local realms
  docs/sync.js
  lib/index.d.ts
  lib/notification-worker.js
  lib/notifier.js
  lib/worker.js
Labels: T:Enhancement

#2359 Add update mode type
  CHANGELOG.md
  lib/extensions.js
Labels: T:Bug

#2317 Update type of Realm.Sync.setLogger
  CHANGELOG.md
  docs/collection.js
  docs/list.js
  docs/object.js
  docs/permission.js
  docs/realm.js
  docs/results.js
  docs/sync.js
  lib/index.d.ts
Labels: T:Bug

#2321 Fixed integration tests packages
  CHANGELOG.md
  integration-tests/environments/electron/package-lock.json
  integration-tests/package.json
  integration-tests/tests/package-lock.json
Labels: T:Internal

#2363 Adding doc for localListenerRealms
  CHANGELOG.md
  docs/sync.js
  lib/index.d.ts
Labels: T:Doc

#2368 Publish before testing
  Jenkinsfile
  dependencies.list
Labels: T:Internal

#2362 Kneth/reduce bundle size
  lib/index.js
Labels: T:Test

#2377 Prepare v2.28.0
  CHANGELOG.md
  dependencies.list
  package-lock.json
  package.json
  src/RealmJS.xcodeproj/project.pbxproj
Labels: T:Internal
