Repository realm/realm-js, pull requests merged in 2019-09, with the labels that each got.

#2503 fix error on refreshAdminToken and refreshAccessToken
  CHANGELOG.md
  lib/extensions.js
  lib/user-methods.js
Labels: T-Enhancement

#2473 Fix readme for env setup
  .gitignore
  README.md
Labels: T-Doc

#2504 Fix node win build debug
  .vscode/launch.json
  .vscode/tasks.json
  README.md
  integration-tests/package-lock.json
  integration-tests/package.json
  integration-tests/tests/package-lock.json
  integration-tests/tests/package.json
  package.json
  scripts/test.sh
  tests/electron/package-lock.json
  tests/electron/package.json
  tests/js/index.js
  tests/js/package.json
  tests/package-lock.json
  tests/package.json
Labels: T-Internal

#2470 Right-hand OR test
  tests/js/query-tests.js
  tests/js/schemas.js
Labels: T-Test

#2523 stuff missing in async open
  CHANGELOG.md
  docs/sync.js
Labels: T-Doc

#2520 client resync
  CHANGELOG.md
  docs/sync.js
  lib/index.d.ts
  scripts/changelog-header.sh
  src/js_sync.hpp
  tests/js/session-tests.js
Labels: T-Feature

#2528 Checking if VS Code is debugging
  lib/index.js
Labels: T-Bug

#2534 Migrate away from rnpm in package.json, use react-native.config.js instead
  package.json
  react-native.config.js
Labels: T-Enhancement

#2538 Update to Realm Core v5.23.5 and Realm Sync v4.7.8
  CHANGELOG.md
  dependencies.list
  src/js_realm_object.hpp
Labels: T-Internal

#2542 Added test to validate chained OR work
  tests/js/query-tests.js
  tests/js/schemas.js
Labels: T-Test
