Repository realm/realm-js, pull requests merged in 2019-02, with the labels that each got.

#2243 Add support for ssl configuration to addListener
  CHANGELOG.md
  docs/sync.js
  lib/index.d.ts
  lib/notifier.js
Labels: T:Enhancement

#2245 Prepare v2.23.0
  CHANGELOG.md
Labels: T:Internal

#2250 Updated pull_request_template.md
  .github/pull_request_template.md
Labels: T:Internal

#2251 Imperative aka. dynamic schema manipulation
  CHANGELOG.md
  integration-tests/environments/electron/package-lock.json
  integration-tests/tests/package-lock.json
  integration-tests/tests/package.json
  integration-tests/tests/src/dynamic-schema-updates.js
  integration-tests/tests/src/index.js
  integration-tests/tests/src/utils/segfault-handler.js
  src/js_realm.hpp
  src/js_schema.hpp
Labels: T:Feature

#2254 Fixing doc error
  docs/collection.js
Labels: T:Doc

#2257 Prepare v2.24.0
  CHANGELOG.md
Labels: T:Internal
