Repository realm/realm-js, pull requests merged in 2019-12, with the labels that each got.

#2630 Fix URLs when building without sync
  CHANGELOG.md
  scripts/download-realm.js
Labels: T-Internal

#2626 React Native iOS integration tests simulator
  CHANGELOG.md
  Jenkinsfile
  integration-tests/environments/react-native/harness/runner.js
  integration-tests/environments/react-native/harness/xcode-cli.js
  integration-tests/environments/react-native/package-lock.json
  integration-tests/environments/react-native/package.json
Labels: T-Internal

#2623 React Native iOS: Support comitting `ios/Pods` to a users git repository
  CHANGELOG.md
  CONTRIBUTING.md
  RealmJS.podspec
Labels: T-Bug

#2647 Prepare v3.6.0
  CHANGELOG.md
Labels: T-Internal

#2649 Update to Realm Core v5.23.7. Update to Realm Sync v4.9.1.
  CHANGELOG.md
  dependencies.list
Labels: T-Internal

#2660 Add an example of a manual transaction (RJS-372).
  docs/realm.js
Labels: T-Doc
