Repository realm/realm-js, pull requests merged in 2019-04, with the labels that each got.

#2314 Build using the macOS 10.13 SDK on CI
  Jenkinsfile
Labels: T:Internal

#2313 Always include the memmove hack (on Android).
  CHANGELOG.md
  react-native/android/src/main/jni/Android.mk
  react-native/android/src/main/jni/Application.mk
Labels: T:Bug

#2306 Add support for subscription timestamps and updating query
  CHANGELOG.md
  docs/collection.js
  docs/realm.js
  docs/sync.js
  lib/extensions.js
  lib/index.d.ts
  package-lock.json
  src/js_results.hpp
  tests/js/index.js
  tests/js/session-tests.js
  tests/js/subscription-tests.js
Labels: T:Enhancement

#2213 Add explicit support for createOrUpdate with diffed updates.
  CHANGELOG.md
  docs/realm.js
  lib/index.d.ts
  src/js_realm.hpp
  tests/js/realm-tests.js
Labels: T:Enhancement

#2320 Update integration tests to conform to new schema property.
  integration-tests/tests/src/dynamic-schema-updates.ts
Labels: T:Test

#2303 Fix Xcode 10.2 'Control may reach end of non-void function' error
  CHANGELOG.md
  src/jsc/jsc_value.hpp
  src/rpc.cpp
Labels: T:Enhancement

#2323 Add description of running/debugging react native tests.
  CONTRIBUTING.md
Labels: T:Doc

#2335 Prepare v2.26.1
  CHANGELOG.md
  dependencies.list
  package-lock.json
  package.json
  src/RealmJS.xcodeproj/project.pbxproj
Labels: T:Internal

#2348 Ensures proper headers are set when calling logout
  CHANGELOG.md
  lib/user-methods.js
Labels: T:Bug

#2302 Adding a global notifier listener that triggers at startup
  CHANGELOG.md
  docs/sync.js
  lib/index.d.ts
  lib/notification-worker.js
  lib/notifier.js
  lib/worker.js
Labels: T:Feature
