Repository realm/realm-js, pull requests merged in 2019-01, with the labels that each got.

#2197 Fix Android builds
  CHANGELOG.md
  react-native/android/src/main/jni/Application.mk
  vendor/json.hpp
Labels: T:Bug

#2195 change the default for argv because child process expects argv to be an array
  lib/worker.js
Labels: T:Bug

#2201 Updating CHANGELOG.md
  CHANGELOG.md
Labels: T:Internal

#2206 The new distribution form for Windows doesn't require SSH.
  Jenkinsfile
  scripts/download-realm.js
Labels: T:Internal

#2223 Don't include headers from the developers JDK
  CHANGELOG.md
  react-native/android/src/main/jni/Android.mk
  src/android/jni_utils.cpp
Labels: T:Internal

#2222 Don't initialize SyncManager when importing Realm
  CHANGELOG.md
  lib/extensions.js
  lib/index.js
  src/js_sync.hpp
Labels: T:Bug

#2209 Add copyBundledRealmFiles() to TS definition and API doc
  CHANGELOG.md
  docs/realm.js
  lib/index.d.ts
Labels: T:Doc
