Repository realm/realm-js, pull requests merged in 2020-04, with the labels that each got.

#2789 Adding a platform independent print
  CHANGELOG.md
  src/android/platform.cpp
  src/ios/platform.mm
  src/node/platform.cpp
  src/platform.hpp
Labels: T-Enhancement

#2780 Remove outdated newsletter link
  README.md
Labels: T-Doc

#2793 Watch-mode for the React Native integration tests
  .eslintrc.json
  .prettierrc.js
  Jenkinsfile
  integration-tests/.eslintrc.json
  integration-tests/environments/electron/.eslintrc.json
  integration-tests/environments/electron/package-lock.json
  integration-tests/environments/electron/package.json
  integration-tests/environments/node/.eslintrc.json
  integration-tests/environments/node/package-lock.json
  integration-tests/environments/node/package.json
  integration-tests/environments/react-native/.eslintrc.js
  integration-tests/environments/react-native/.eslintrc.json
  integration-tests/environments/react-native/README.md
  integration-tests/environments/react-native/babel.config.js
  integration-tests/environments/react-native/harness/android-cli.js
  integration-tests/environments/react-native/harness/react-native-cli.js
  integration-tests/environments/react-native/harness/runner.js
  integration-tests/environments/react-native/harness/xcode-cli.js
  integration-tests/environments/react-native/metro.config.js
  integration-tests/environments/react-native/package-lock.json
  integration-tests/environments/react-native/package.json
  integration-tests/environments/react-native/src/App.js
  integration-tests/package.json
  integration-tests/tests/package.json
  integration-tests/tests/src/index.ts
  integration-tests/tests/src/objects.ts
  integration-tests/tests/tsconfig.json
  package-lock.json
  package.json
Labels: T-Internal, T-Test

#2811 Using eslint instead of tslint in "/packages"
  .eslintrc.json
  .prettierrc.js
  package-lock.json
  package.json
  packages/realm-app-importer/.eslintignore
  packages/realm-app-importer/.eslintrc.json
  packages/realm-app-importer/package-lock.json
  packages/realm-app-importer/package.json
  packages/realm-app-importer/src/RealmAppImporter.ts
  packages/realm-app-importer/src/cli.ts
  packages/realm-network-transport/.eslintignore
  packages/realm-network-transport/.eslintrc.json
  packages/realm-network-transport/package-lock.json
  packages/realm-network-transport/package.json
  packages/realm-network-transport/src/NetworkTransport.test.ts
  packages/realm-network-transport/src/NetworkTransport.ts
  packages/realm-network-transport/src/index.ts
Labels: T-Internal

#2835 Add node 14 to CI.
  CHANGELOG.md
  Dockerfile
  Jenkinsfile
  README.md
  package-lock.json
  package.json
  packaging/node-pre-gyp/base-image/Dockerfile
Labels: T-Internal

#2840 Getting ready for v5.0.4.
  CHANGELOG.md
Labels: T-Internal
