Repository realm/realm-js, pull requests merged in 2020-01, with the labels that each got.

#2673 Expand API doc for Realm.write()
  docs/realm.js
Labels: T-Doc

#2648 Updated the index.d.ts for Realm.Sync.User.current & subscriptionCallback
  lib/index.d.ts
Labels: T-Bug

#2688 Update to Realm Core v5.23.8 and Realm Sync v4.9.2.
  CHANGELOG.md
  dependencies.list
Labels: T-Internal

#2691 Update to Realm Sync v4.9.4
  CHANGELOG.md
  dependencies.list
Labels: T-Internal

#2692 Add ClientResyncMode enum to JavaScript
  CHANGELOG.md
  lib/extensions.js
  tests/js/session-tests.js
Labels: T-Bug

#2686 Use the node versions as specified (Linux)
  Jenkinsfile
  scripts/test.sh
Labels: T-Internal

#2700 Fix ReactNative iOS integration tests
  Jenkinsfile
  integration-tests/environments/react-native/harness/runner.js
  integration-tests/environments/react-native/harness/xcode-cli.js
Labels: T-Internal
