Repository realm/realm-js, pull requests merged in 2020-09, with the labels that each got.

#3086 Realm Web: Refactor to enable link credentials
  packages/realm-network-transport/src/DefaultNetworkTransport.ts
  packages/realm-network-transport/src/MongoDBRealmError.ts
  packages/realm-network-transport/src/dom/index.ts
  packages/realm-network-transport/src/index.ts
  packages/realm-network-transport/src/node/index.ts
  packages/realm-network-transport/src/tests/DefaultNetworkTransport.test.ts
  packages/realm-network-transport/src/types.ts
  packages/realm-network-transport/test/mocha.opts
  packages/realm-web/.eslintrc.json
  packages/realm-web/CHANGELOG.md
  packages/realm-web/package-lock.json
  packages/realm-web/src/App.ts
  packages/realm-web/src/AppLocation.ts
  packages/realm-web/src/AppStorage.ts
  packages/realm-web/src/Authenticator.ts
  packages/realm-web/src/Credentials.ts
  packages/realm-web/src/Fetcher.ts
  packages/realm-web/src/FunctionsFactory.ts
  packages/realm-web/src/MongoDBRealmError.ts
  packages/realm-web/src/OAuth2Helper.ts
  packages/realm-web/src/User.ts
  packages/realm-web/src/UserProfile.ts
  packages/realm-web/src/auth-providers/ApiKeyAuth.ts
  packages/realm-web/src/auth-providers/EmailPasswordAuth.ts
  packages/realm-web/src/dom/LocalStorage.ts
  packages/realm-web/src/environment.ts
  packages/realm-web/src/index.ts
  packages/realm-web/src/routes.ts
  packages/realm-web/src/services/HTTPService.ts
  packages/realm-web/src/services/MongoDBService.ts
  packages/realm-web/src/services/index.ts
  packages/realm-web/src/storage/MemoryStorage.ts
  packages/realm-web/src/storage/PrefixedStorage.ts
  packages/realm-web/src/storage/Storage.ts
  packages/realm-web/src/tests/ApiKeyAuth.test.ts
  packages/realm-web/src/tests/App.test.ts
  packages/realm-web/src/tests/Fetcher.test.ts
  packages/realm-web/src/tests/FunctionsFactory.test.ts
  packages/realm-web/src/tests/HTTPService.test.ts
  packages/realm-web/src/tests/MongoDBService.test.ts
  packages/realm-web/src/tests/OAuth2Helper.test.ts
  packages/realm-web/src/tests/User.test.ts
  packages/realm-web/src/tests/utils/MockApp.ts
  packages/realm-web/src/tests/utils/MockFetcher.ts
  packages/realm-web/src/tests/utils/MockNetworkTransport.ts
  packages/realm-web/src/tests/utils/MockTransport.ts
  packages/realm-web/src/tests/utils/index.ts
  packages/realm-web/src/transports/AppTransport.ts
  packages/realm-web/src/transports/AuthenticatedTransport.ts
  packages/realm-web/src/transports/BaseTransport.ts
  packages/realm-web/src/transports/PrefixedTransport.ts
  packages/realm-web/src/transports/Transport.ts
  packages/realm-web/src/transports/index.ts
  packages/realm-web/src/utils/ejson.ts
  packages/realm-web/tsconfig.json
Labels: T-Feature

#3229 Upgrade to sync v5.0.23
  CHANGELOG.md
  dependencies.list
Labels: T-Internal

#3231 Upgrade to sync v10.0.0-beta.12
  CHANGELOG.md
  dependencies.list
  scripts/changelog-header.sh
Labels: T-Internal

#3239 Realm Web: Fixing linking with OAuth2 credentials
  packages/realm-web-integration-tests/src/index.ts
  packages/realm-web-integration-tests/src/user.test.ts
  packages/realm-web/CHANGELOG.md
  packages/realm-web/src/Authenticator.ts
  packages/realm-web/src/Credentials.ts
  packages/realm-web/src/Fetcher.ts
  packages/realm-web/src/OAuth2Helper.ts
  packages/realm-web/src/User.ts
  packages/realm-web/src/tests/OAuth2Helper.test.ts
  packages/realm-web/src/tests/User.test.ts
  packages/realm-web/src/utils/string.ts
Labels: T-Bug

#3240 Realm Web: Fixing linking with OAuth2 credentials (more)
  packages/realm-network-transport/src/DefaultNetworkTransport.ts
  packages/realm-network-transport/src/types.ts
  packages/realm-web/CHANGELOG.md
  packages/realm-web/src/Authenticator.ts
  packages/realm-web/src/Fetcher.ts
Labels: T-Bug

#3250 Update changelog to reflect Studio releases
  CHANGELOG.md
Labels: T-Internal

#3247 Realm Web: Adding watch to MongoDB collections
  packages/realm-network-transport/src/types.ts
  packages/realm-network-transport/tsconfig.json
  packages/realm-web-integration-tests/src/remote-mongodb-service.test.ts
  packages/realm-web-integration-tests/src/user.test.ts
  packages/realm-web/CHANGELOG.md
  packages/realm-web/src/Fetcher.ts
  packages/realm-web/src/FunctionsFactory.ts
  packages/realm-web/src/User.ts
  packages/realm-web/src/dom/index.ts
  packages/realm-web/src/environment.ts
  packages/realm-web/src/node/index.ts
  packages/realm-web/src/services/MongoDBService/MongoDBCollection.ts
  packages/realm-web/src/services/MongoDBService/WatchError.ts
  packages/realm-web/src/services/MongoDBService/WatchStream.ts
  packages/realm-web/src/services/MongoDBService/index.ts
  packages/realm-web/src/tests/WatchStream.test.ts
  tests/js/user-tests.js
  types/app.d.ts
Labels: T-Feature
