Repository realm/realm-js, pull requests merged in 2020-07, with the labels that each got.

#3023 Add a timeout to more CI jobs
  Jenkinsfile
Labels: T-Internal

#3024 Upgrade to Realm Core v6.0.8 and Realm Sync v5.0.7
  CHANGELOG.md
  dependencies.list
Labels: T-Internal

#3028 PR feedback
  CHANGELOG.md
Labels: T-Internal

#3043 sendResetPasswordEmail() must parse arguments correctly
  CHANGELOG.md
  src/js_email_password_provider.hpp
Labels: T-Bug

#3040 Generate API doc for Realm.Sync too
  docs/sync.js
Labels: T-Doc

#3030 Log out using App::log_out()
  CHANGELOG.md
  docs/sync.js
  lib/user.js
  src/js_user.hpp
  tests/js/encryption-tests.js
  tests/js/session-tests.js
  types/index.d.ts
Labels: T-Bug

#3042 fix failing MongoDBRealmSync test
  tests/js/app-tests.js
Labels: T-Internal

#3047 ApiKeyAuth renames
  CHANGELOG.md
  docs/sync.js
  lib/browser/user.js
  lib/extensions.js
  lib/user.js
  lib/user_apikey_provider_client.js
  src/RealmJS.xcodeproj/project.pbxproj
  src/js_api_key_auth.hpp
  src/js_realm.hpp
  src/js_user.hpp
  tests/js/user-tests.js
Labels: Breaking

#2994 Realm Web: Refactored `AuthenticatedTransport`
  packages/realm-web/src/App.test.ts
  packages/realm-web/src/Credentials.test.ts
  packages/realm-web/src/User.test.ts
  packages/realm-web/src/User.ts
  packages/realm-web/src/transports/AuthenticatedTransport.test.ts
  packages/realm-web/src/transports/AuthenticatedTransport.ts
  packages/realm-web/src/transports/BaseTransport.ts
  packages/realm-web/src/transports/PrefixedTransport.ts
  packages/realm-web/src/transports/Transport.ts
Labels: T-Internal

#3001 Realm Web: Minor refactors
  packages/realm-network-transport/package-lock.json
  packages/realm-network-transport/src/MongoDBRealmError.ts
  packages/realm-network-transport/src/NetworkTransport.ts
  packages/realm-web-integration-tests/src/remote-mongodb-service.test.ts
  packages/realm-web/CHANGELOG.md
  packages/realm-web/README.md
  packages/realm-web/package-lock.json
  packages/realm-web/package.json
  packages/realm-web/src/App.ts
  packages/realm-web/src/FunctionsFactory.test.ts
  packages/realm-web/src/FunctionsFactory.ts
  packages/realm-web/src/User.test.ts
  packages/realm-web/src/User.ts
  packages/realm-web/src/services/HTTPService.ts
  packages/realm-web/src/services/MongoDBService.test.ts
  packages/realm-web/src/services/MongoDBService.ts
  packages/realm-web/src/services/index.ts
  types/services.d.ts
Labels: T-Internal

#3055 Realm Web: Custom data base64 fixed
  packages/realm-web/CHANGELOG.md
  packages/realm-web/package-lock.json
  packages/realm-web/package.json
  packages/realm-web/rollup.config.js
  packages/realm-web/src/User.ts
  packages/realm-web/src/utils/base64.ts
  packages/realm-web/tsconfig.build.json
Labels: T-Bug

#3052 Realm Web: Fixing duplication of user ids
  packages/realm-web/CHANGELOG.md
  packages/realm-web/src/App.test.ts
  packages/realm-web/src/App.ts
  packages/realm-web/src/AppStorage.ts
  packages/realm-web/src/Credentials.ts
  packages/realm-web/src/User.ts
Labels: T-Bug

#3051 API keys revisited
  CHANGELOG.md
  docs/sync.js
  lib/browser/credentials.js
  packages/realm-web-integration-tests/harness/node.ts
  packages/realm-web-integration-tests/src/api-key-auth-provider.test.ts
  packages/realm-web-integration-tests/src/index.ts
  packages/realm-web/CHANGELOG.md
  packages/realm-web/src/App.test.ts
  packages/realm-web/src/Credentials.ts
  packages/realm-web/src/User.test.ts
  packages/realm-web/src/User.ts
  packages/realm-web/src/auth-providers/ApiKeyAuth.test.ts
  packages/realm-web/src/auth-providers/ApiKeyAuth.ts
  packages/realm-web/src/auth-providers/EmailPasswordAuth.ts
  packages/realm-web/src/transports/AuthenticatedTransport.ts
  packages/realm-web/src/transports/Transport.ts
  src/js_app_credentials.hpp
  src/rpc.cpp
  types/app.d.ts
  types/auth-providers.d.ts
Labels: Breaking, T-Enhancement

#3058 Realm Web publish v0.7.0
  packages/realm-web/CHANGELOG.md
  packages/realm-web/package-lock.json
  packages/realm-web/package.json
Labels: T-Internal

#3065 Upgrade to Realm Core v6.0.9 and Realm Sync v5.0.8.
  CHANGELOG.md
  dependencies.list
Labels: T-Internal

#3079 Fix resetPassword and callResetPasswordFunction
  CHANGELOG.md
  docs/sync.js
  lib/email-password-auth-methods.js
  packages/realm-web/src/auth-providers/EmailPasswordAuth.ts
  src/js_email_password_auth.hpp
  types/auth-providers.d.ts
Labels: T-Bug

#3061 Minor type bugs related to Credentials and MongoDB Collection watch
  packages/realm-web/src/Credentials.ts
  packages/realm-web/src/services/MongoDBService.ts
  types/.eslintrc.json
  types/app.d.ts
  types/services.d.ts
Labels: T-Enhancement

#3082 Allow a string argument when constructing an App
  CHANGELOG.md
  docs/sync.js
  src/js_app.hpp
  tests/js/app-tests.js
Labels: T-Bug

#3064 Realm Web: Reject login when window closes
  packages/realm-web/CHANGELOG.md
  packages/realm-web/src/OAuth2Helper.ts
  packages/realm-web/types/environment.d.ts
Labels: T-Enhancement
