Repository realm/realm-js, pull requests merged in 2020-03, with the labels that each got.

#2743 Fix bug in how multiplexing is started
  CHANGELOG.md
  src/js_sync.hpp
Labels: T-Bug

#2757 Prepare v5.0.0
  CHANGELOG.md
Labels: T-Internal

#2753 Realm App importer
  CHANGELOG.md
  packages/realm-app-importer/.gitignore
  packages/realm-app-importer/README.md
  packages/realm-app-importer/package-lock.json
  packages/realm-app-importer/package.json
  packages/realm-app-importer/realm-app-importer
  packages/realm-app-importer/src/RealmAppImporter.ts
  packages/realm-app-importer/src/cli.ts
  packages/realm-app-importer/src/index.ts
  packages/realm-app-importer/templates/simple/stitch.json
  packages/realm-app-importer/templates/with-secret/auth_providers/custom-token.json
  packages/realm-app-importer/templates/with-secret/secrets.json
  packages/realm-app-importer/templates/with-secret/stitch.json
  packages/realm-app-importer/tsconfig.build.json
  packages/realm-app-importer/tsconfig.json
Labels: T-Feature

#2771 Object Store requires gcc 9
  Dockerfile
Labels: T-Internal

#2764 5.0.2
  CHANGELOG.md
  Jenkinsfile
  dependencies.list
  docs/realm.js
  package-lock.json
  package.json
  src/RealmJS.xcodeproj/project.pbxproj
Labels: T-Internal
