Repository realm/realm-js, pull requests merged in 2020-10, with the labels that each got.

#3278 Upgrade to Realm Core v10.0.0-beta.8 and Realm Sync v10.0.0-beta.14
  CHANGELOG.md
  dependencies.list
Labels: T-Internal

#3269 Realm Web: Making session refresh and deletion more robust
  packages/realm-app-importer/package.json
  packages/realm-network-transport/package.json
  packages/realm-web/CHANGELOG.md
  packages/realm-web/src/Fetcher.ts
  packages/realm-web/src/User.ts
  packages/realm-web/src/tests/App.test.ts
  packages/realm-web/src/tests/User.test.ts
Labels: T-Enhancement

#3296 Realm Web: Send device information in body (fixing tests)
  packages/realm-web/CHANGELOG.md
  packages/realm-web/src/Authenticator.ts
  packages/realm-web/src/DeviceInformation.ts
  packages/realm-web/src/tests/App.test.ts
  packages/realm-web/src/tests/User.test.ts
  packages/realm-web/src/tests/utils/index.ts
Labels: T-Internal

#3297 Realm Web: Move the getApp method
  packages/realm-web/CHANGELOG.md
  packages/realm-web/src/App.ts
  packages/realm-web/src/index.ts
  packages/realm-web/src/tests/App.test.ts
  types/app.d.ts
Labels: T-Enhancement

#3298 Realm Web: App "services" and "functions" removed
  packages/realm-web-integration-tests/src/app.test.ts
  packages/realm-web-integration-tests/src/functions.test.ts
  packages/realm-web-integration-tests/src/http-service.test.ts
  packages/realm-web-integration-tests/src/iife.test.ts
  packages/realm-web-integration-tests/src/remote-mongodb-service.test.ts
  packages/realm-web/CHANGELOG.md
  packages/realm-web/src/App.ts
  packages/realm-web/src/services/HTTPService.ts
  packages/realm-web/src/services/MongoDBService/index.ts
  packages/realm-web/src/services/index.ts
  packages/realm-web/src/tests/App.test.ts
Labels: Breaking

#3323 Realm Web: Removed the typescript declarations for app.services and app.functions
  CHANGELOG.md
  packages/realm-web/CHANGELOG.md
  types/app.d.ts
Labels: Breaking

#3330 Realm Web: Fixing email password provider client
  packages/realm-web-integration-tests/src/api-key-auth.test.ts
  packages/realm-web-integration-tests/src/email-password-auth-provider.test.ts
  packages/realm-web-integration-tests/src/email-password-auth.test.ts
  packages/realm-web-integration-tests/src/index.ts
  packages/realm-web/CHANGELOG.md
  packages/realm-web/src/auth-providers/EmailPasswordAuth.ts
  packages/realm-web/src/tests/ApiKeyAuth.test.ts
  packages/realm-web/src/tests/EmailPasswordAuth.test.ts
Labels: T-Bug

#3338 Releasing Realm Web 1.0.0-rc.2
  packages/realm-web/CHANGELOG.md
  packages/realm-web/README.md
  packages/realm-web/RELEASENOTES.template.md
  packages/realm-web/package-lock.json
  packages/realm-web/package.json
  packages/realm-web/scripts/postversion.ts
Labels: T-Internal

#3345 Realm Web: Integration test on PRs
  .github/workflows/pr-realm-web.yml
  packages/realm-web-integration-tests/harness/dev.ts
  packages/realm-web-integration-tests/harness/github.ts
  packages/realm-web-integration-tests/harness/index.ts
  packages/realm-web-integration-tests/package.json
Labels: T-Internal

#3346 Realm Web: allUser object keyed by ids
  CHANGELOG.md
  packages/realm-web-integration-tests/src/app.test.ts
  packages/realm-web/CHANGELOG.md
  packages/realm-web/src/App.ts
  packages/realm-web/src/User.ts
  packages/realm-web/src/tests/App.test.ts
  types/app.d.ts
Labels: T-Bug
