Repository realm/realm-js, pull requests merged in 2020-06, with the labels that each got.

#2742 MongoDB Realm integration
  CHANGELOG.md
  realm.gypi
  scripts/download-realm.js
  target_defaults.gypi
Labels: Breaking, T-Feature

#2930 v10.0.0-beta.2
  CHANGELOG.md
  dependencies.list
  package-lock.json
  package.json
Labels: T-Internal

#2931 RN debugger support
  CHANGELOG.md
  lib/browser/index.js
  react-native/android/src/main/jni/Android.mk
Labels: T-Bug

#2932 10.0.0-beta.4
  CHANGELOG.md
  dependencies.list
  package-lock.json
  package.json
Labels: T-Internal

#2933 Add methods to Realm.Auth providers
  CHANGELOG.md
  lib/app.js
  lib/extensions.js
  lib/user.js
  lib/user_apikey_provider_client.js
  src/js_app.hpp
  src/js_user.hpp
  tests/js/app-tests.js
Labels: T-Bug

#2944 [10.0.0-beta.5] Bump version
  CHANGELOG.md
  Jenkinsfile
  dependencies.list
  package-lock.json
  package.json
Labels: T-Internal

#2955 [10.0.0-beta.6] Bump version
  CHANGELOG.md
  dependencies.list
  package-lock.json
  package.json
Labels: T-Internal

#2958 Fixing bad merges on v10
  .eslintrc.json
  integration-tests/tests/package-lock.json
  package-lock.json
  package.json
  packages/realm-app-importer/package-lock.json
  packages/realm-network-transport/package-lock.json
  packages/realm-network-transport/src/NetworkTransport.ts
  packages/realm-web-integration-tests/package-lock.json
  packages/realm-web/package-lock.json
  packages/realm-web/package.json
  packages/realm-web/src/transports/BaseTransport.ts
Labels: T-Internal

#2985 Missing toJSON TS declaration added for Realm.Object
  CHANGELOG.md
  lib/index.d.ts
Labels: T-Bug

#3008 Fix require of AbortController from window
  lib/NetworkTransport.js
  lib/extensions.js
  package-lock.json
  package.json
  packages/realm-network-transport/package-lock.json
  packages/realm-network-transport/package.json
  packages/realm-network-transport/src/NetworkTransport.ts
  packages/realm-web/package-lock.json
  packages/realm-web/package.json
Labels: T-Bug
