Repository realm/realm-js, pull requests merged in 2021-12, with the labels that each got.

#4120 Hermes: Fixing a couple of breaking tests
  src/js_object_accessor.hpp
  src/jsi/jsi_class.hpp
  tests/js/dictionary-tests.js
  tests/js/mixed-tests.js
  tests/js/object-tests.js
  tests/js/realm-tests.js
Labels: T-Test, hermes, cla: yes

#4123 Intercept missing libjsi.so
  CHANGELOG.md
  react-native/android/src/main/java/io/realm/react/RealmReactModule.java
Labels: T-Enhancement, hermes, cla: yes

#4124 Updated RN peer dependency version
  package.json
Labels: hermes, cla: yes

#4125 Fix classes not extending `Realm.Object`
  CHANGELOG.md
  src/jsi/jsi_class.hpp
Labels: T-Bug, hermes, cla: yes

#4128 Fixed throwing "Illegal constructor"
  CHANGELOG.md
  src/jsi/jsi_class.hpp
Labels: T-Bug, hermes, cla: yes

#4129 Various JSI fixes to greenlight more tests
  src/jsi/jsi_class.hpp
  src/jsi/jsi_types.hpp
  src/jsi/jsi_value.hpp
  tests/js/list-tests.js
Labels: cla: yes

#4147 Direct TypeScript tests & Shared realm metro config
  .github/workflows/package-unit-tests.yml
  CHANGELOG.md
  integration-tests/README.md
  integration-tests/environments/electron/app/mocha.js
  integration-tests/environments/node/index.js
  integration-tests/environments/react-native/metro.config.js
  integration-tests/environments/react-native/package.json
  integration-tests/tests/.mocharc.json
  integration-tests/tests/package.json
  package-lock.json
  package.json
  packages/metro-config/.eslintrc.json
  packages/metro-config/README.md
  packages/metro-config/index.js
  packages/metro-config/package-lock.json
  packages/metro-config/package.json
  packages/realm-app-importer/package.json
  packages/realm-common/package-lock.json
  packages/realm-common/package.json
  packages/realm-network-transport/package-lock.json
  packages/realm-network-transport/package.json
  packages/realm-react/example/metro.config.js
  packages/realm-react/example/package.json
  packages/realm-react/package.json
  packages/realm-web-integration-tests/package.json
  packages/realm-web/package.json
  tests/package-lock.json
  tests/package.json
Labels: T-Internal, cla: yes

#3986 Create github workflow to build and publish jsdocs (#3762)
  .github/workflows/jsdoc.yml
Labels: cla: yes

#4148 Pass arguments correctly to callResetPasswordFunction
  CHANGELOG.md
  lib/email-password-auth-methods.js
  src/js_email_password_auth.hpp
  tests/js/user-tests.js
Labels: cla: yes

#4109 Type resolution fix for Set and friends
  CHANGELOG.md
  lib/collection-methods.js
  lib/extensions.js
Labels: cla: yes

#4149 Tests failing for Node > 14
  CHANGELOG.md
  package-lock.json
  package.json
  src/node/node_protected.hpp
Labels: cla: yes

#4082 Automated Client Reset with Discard Local behavior
  CHANGELOG.md
  docs/sync.js
  src/js_sync.hpp
  tests/js/session-tests.js
  types/index.d.ts
Labels: cla: yes

#4156 Fix error that caused a segfault when users registered custom Sync logger functions
  CHANGELOG.md
  src/js_sync.hpp
  src/logger.hpp
  tests/js/session-tests.js
Labels: cla: yes

#4165 Realm App Importer: Environment variables & API keys
  packages/realm-app-importer/README.md
  packages/realm-app-importer/src/AppImporter.ts
  packages/realm-app-importer/src/cli.ts
  packages/realm-app-importer/tsconfig.build.json
Labels: cla: yes

#4168 Rename @realm.io/react to @realm/react and make Realm importable
  .github/workflows/pr-realm-react.yml
  packages/metro-config/package-lock.json
  packages/realm-react/CHANGELOG.md
  packages/realm-react/README.md
  packages/realm-react/example/README.md
  packages/realm-react/example/app/components/TaskList.tsx
  packages/realm-react/example/app/models/Task.ts
  packages/realm-react/example/ios/Podfile.lock
  packages/realm-react/example/ios/RealmReactExample.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  packages/realm-react/example/package-lock.json
  packages/realm-react/example/package.json
  packages/realm-react/package-lock.json
  packages/realm-react/package.json
  packages/realm-react/src/index.tsx
Labels: cla: yes

#4167 Remove Emacs config.
  .dir-locals.el
  CHANGELOG.md
Labels: cla: yes

#4173 Template Tweaks
  templates/expo-template-js/.npmignore
  templates/expo-template-js/README.md
  templates/expo-template-js/app.json
  templates/expo-template-js/eas.json
  templates/expo-template-js/gitignore
  templates/expo-template-js/package.json
  templates/expo-template-js/react-native.config.js
  templates/expo-template-ts/.npmignore
  templates/expo-template-ts/README.md
  templates/expo-template-ts/app.json
  templates/expo-template-ts/eas.json
  templates/expo-template-ts/gitignore
  templates/expo-template-ts/package.json
  templates/expo-template-ts/react-native.config.js
  templates/react-native-template-realm-ts/package.json
Labels: cla: yes

#4180 Fix realm-web integration tests
  .github/workflows/pr-realm-web.yml
  packages/realm-web-integration-tests/harness/import-realm-app.ts
Labels: cla: yes

#4179 Remove `deprecated-react-native-listview` from root package.json
  CHANGELOG.md
  examples/ReactNativeBenchmarks/package-lock.json
  examples/ReactNativeBenchmarks/package.json
  integration-tests/package-lock.json
  integration-tests/tests/package-lock.json
  package-lock.json
  package.json
  packages/realm-app-importer/package-lock.json
  packages/realm-react/package-lock.json
  packages/realm-web-integration-tests/package-lock.json
  packages/realm-web/package-lock.json
  tests/package-lock.json
  tests/test-runners/jest/package-lock.json
Labels: cla: yes
