Repository realm/realm-js, pull requests merged in 2021-11, with the labels that each got.

#4053 Update CONTRIBUTING.md to cover branches
  CONTRIBUTING.md
Labels: T-Doc, cla: yes

#4056 Removed caches in favour of relying more on ccache
  .github/workflows/integration-tests.yml
Labels: cla: yes

#4055 Avoid building on changes to integration tests or .md files
  Jenkinsfile
Labels: cla: yes

#4043 Update react native templates to RN 0.66.1
  packages/react-native-template-realm-js/package.json
  packages/react-native-template-realm-js/template/_flowconfig
  packages/react-native-template-realm-js/template/_gitignore
  packages/react-native-template-realm-js/template/android/app/build.gradle
  packages/react-native-template-realm-js/template/android/app/src/main/res/values/styles.xml
  packages/react-native-template-realm-js/template/android/build.gradle
  packages/react-native-template-realm-js/template/android/gradle.properties
  packages/react-native-template-realm-js/template/ios/Podfile
  packages/react-native-template-realm-js/template/ios/RealmJsTemplate.xcodeproj/project.pbxproj
  packages/react-native-template-realm-js/template/package.json
  packages/react-native-template-realm-ts/package.json
  packages/react-native-template-realm-ts/template/_gitignore
  packages/react-native-template-realm-ts/template/android/app/build.gradle
  packages/react-native-template-realm-ts/template/android/app/src/main/res/values/styles.xml
  packages/react-native-template-realm-ts/template/android/build.gradle
  packages/react-native-template-realm-ts/template/android/gradle.properties
  packages/react-native-template-realm-ts/template/ios/Podfile
  packages/react-native-template-realm-ts/template/ios/RealmTsTemplate.xcodeproj/project.pbxproj
  packages/react-native-template-realm-ts/template/package.json
Labels: cla: yes

#4063 Attempting to stabilize integration tests
  .github/workflows/integration-tests.yml
Labels: cla: yes

#3625 Update launch.json and contrib guide to prompt for a test filter
  .vscode/launch.json
  contrib/assets/debug-enter-test-filter.png
  contrib/vscode-debugging.md
Labels: cla: yes

#4054 Avoid `local-install` and rely on `metro.config.js` instead
  .watchmanconfig
  CHANGELOG.md
  integration-tests/environments/react-native/README.md
  integration-tests/environments/react-native/android/app/src/main/java/com/realmreactnativetests/MainApplication.java
  integration-tests/environments/react-native/ios/Podfile
  integration-tests/environments/react-native/metro.config.js
  integration-tests/environments/react-native/package-lock.json
  integration-tests/environments/react-native/package.json
  packages/realm-network-transport/.watchmanconfig
Labels: T-Test, cla: yes

#4067 Add readme note on debugging CI tests
  contrib/building.md
Labels: cla: yes

#4072 Combine type definitions
  CHANGELOG.md
  types/index.d.ts
Labels: cla: yes

#4050 Colorized compiler diagnostics if using Ninja
  CHANGELOG.md
  CMakeLists.txt
Labels: cla: yes

#4068 Upgrade integration test app to React Native v0.66.2
  .github/workflows/integration-tests.yml
  integration-tests/environments/node/package.json
  integration-tests/environments/react-native/.flowconfig
  integration-tests/environments/react-native/.gitignore
  integration-tests/environments/react-native/android/app/build.gradle
  integration-tests/environments/react-native/android/app/src/main/res/values/styles.xml
  integration-tests/environments/react-native/android/build.gradle
  integration-tests/environments/react-native/android/gradle.properties
  integration-tests/environments/react-native/android/gradle/wrapper/gradle-wrapper.properties
  integration-tests/environments/react-native/harness/runner.js
  integration-tests/environments/react-native/ios/Podfile
  integration-tests/environments/react-native/ios/RealmReactNativeTests.xcodeproj/project.pbxproj
  integration-tests/environments/react-native/package-lock.json
  integration-tests/environments/react-native/package.json
Labels: cla: yes

#4074 Fix mismatch between TS/API doc and implementation
  CHANGELOG.md
  lib/extensions.js
  tests/js/open-behavior-tests.js
Labels: cla: yes

#4069 Remove commented out mixed code
  src/js_types.hpp
Labels: cla: yes

#4076 Reading into @scoped packages when resolving symbolic links in Metro config
  integration-tests/environments/react-native/metro.config.js
Labels: cla: yes

#4070 Enable CMake compile_commands.json and add appropriate VS Code config and setup instructions
  .gitignore
  .vscode/extensions.json
  CMakeLists.txt
  compile_commands.json
  contrib/building.md
Labels: cla: yes

#4084 Realm Web: Use `globalThis` instead of `window` global
  packages/realm-network-transport/src/dom/index.ts
  packages/realm-web/.eslintrc.json
  packages/realm-web/CHANGELOG.md
  packages/realm-web/package-lock.json
  packages/realm-web/package.json
  packages/realm-web/src/FunctionsFactory.ts
  packages/realm-web/src/dom/LocalStorage.ts
  packages/realm-web/src/dom/index.ts
  packages/realm-web/test/env.js
Labels: T-Bug, cla: yes

#3444 Creating a GitHub action installing Realm JS with the latest versions
  .github/workflows/install-test-react-native.yml
  .gitignore
  install-tests/react-native/.eslintrc.json
  install-tests/react-native/App.js
  install-tests/react-native/install.sh
  install-tests/react-native/listen.js
  install-tests/react-native/package.json
  install-tests/react-native/run-ios.sh
Labels: cla: yes

#4085 Add lldb debug integration tests config, upgrade mocha to prevent child process being spawned
  .vscode/launch.json
  integration-tests/README.md
  integration-tests/tests/.mocharc.json
  integration-tests/tests/package-lock.json
  integration-tests/tests/package.json
Labels: cla: yes

#4088 Quote all args for integration test run, so that quoted multi-word grep strings are preserved
  integration-tests/tests/start.js
Labels: cla: yes

#4091 Update linting.md to clarify disabling any other formatting extensions
  .vscode/settings.json
  contrib/linting.md
Labels: T-Doc, T-Internal, cla: yes

#4079 Rename namespaces in the JSI codebase to reflect that it doesn't just support Hermes
  CHANGELOG.md
  RealmJS.podspec
  react-native/ios/RealmReact/RealmReact.mm
  scripts/build-ios.sh
  src/CMakeLists.txt
  src/android/io_realm_react_RealmReactModule.cpp
  src/jsi/CMakeLists.txt
  src/jsi/jsi_class.hpp
  src/jsi/jsi_function.hpp
  src/jsi/jsi_init.cpp
  src/jsi/jsi_init.h
  src/jsi/jsi_init.hpp
  src/jsi/jsi_object.hpp
  src/jsi/jsi_protected.hpp
  src/jsi/jsi_return_value.hpp
  src/jsi/jsi_string.hpp
  src/jsi/jsi_types.hpp
  src/jsi/jsi_value.hpp
Labels: cla: yes

#4099 Remove unmaintained `src/test` directory
  src/test/README.md
  src/test/catch.cpp
  src/test/catch_amalgamated.hpp
  src/test/jsc_object.js
  src/test/main.cpp
  src/test/test.sh
  src/test/test_bed.hpp
Labels: cla: yes

#4100 Add clang-format commit to gitignore-revs
  .gitignore-revs
  contrib/building.md
Labels: cla: yes

#4102 Open simulator before running RN tests to ensure system can find it
  .github/workflows/integration-tests.yml
Labels: cla: yes

#4103 Update docker image URL to ghcr.io
  .github/workflows/pr-realm-web.yml
  CONTRIBUTING.md
  packages/realm-web-integration-tests/README.md
  scripts/start-sync-server.sh
Labels: cla: yes

#4105 Simplify clang-format script
  package.json
Labels: T-Internal, cla: yes

#4108 Fix docker url in web
  CHANGELOG.md
  packages/realm-web-integration-tests/harness/github.ts
Labels: cla: yes

#4112 Exclude react-native/android/build from NPM package
  CHANGELOG.md
  react-native/android/.npmignore
Labels: T-Internal, cla: yes

#4113 Removing the React Example app
  CHANGELOG.md
  Jenkinsfile
  examples/ReactExample/.babelrc
  examples/ReactExample/.buckconfig
  examples/ReactExample/.eslintrc.json
  examples/ReactExample/.flowconfig
  examples/ReactExample/.gitattributes
  examples/ReactExample/.gitignore
  examples/ReactExample/.npmignore
  examples/ReactExample/.watchmanconfig
  examples/ReactExample/android/app/BUCK
  examples/ReactExample/android/app/build.gradle
  examples/ReactExample/android/app/proguard-rules.pro
  examples/ReactExample/android/app/src/main/AndroidManifest.xml
  examples/ReactExample/android/app/src/main/java/io/realm/react/example/MainActivity.java
  examples/ReactExample/android/app/src/main/java/io/realm/react/example/MainApplication.java
  examples/ReactExample/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  examples/ReactExample/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  examples/ReactExample/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  examples/ReactExample/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  examples/ReactExample/android/app/src/main/res/values/strings.xml
  examples/ReactExample/android/app/src/main/res/values/styles.xml
  examples/ReactExample/android/build.gradle
  examples/ReactExample/android/gradle.properties
  examples/ReactExample/android/gradle/wrapper/gradle-wrapper.jar
  examples/ReactExample/android/gradle/wrapper/gradle-wrapper.properties
  examples/ReactExample/android/gradlew
  examples/ReactExample/android/gradlew.bat
  examples/ReactExample/android/keystores/BUCK
  examples/ReactExample/android/keystores/debug.keystore.properties
  examples/ReactExample/android/settings.gradle
  examples/ReactExample/components/items-screen.js
  examples/ReactExample/components/realm.js
  examples/ReactExample/components/styles.js
  examples/ReactExample/components/todo-app.js
  examples/ReactExample/components/todo-item.js
  examples/ReactExample/components/todo-itemsview.js
  examples/ReactExample/components/todo-list-item.js
  examples/ReactExample/components/todo-listview.js
  examples/ReactExample/index.android.js
  examples/ReactExample/index.ios.js
  examples/ReactExample/ios/Podfile
  examples/ReactExample/ios/ReactExample.xcodeproj/project.pbxproj
  examples/ReactExample/ios/ReactExample.xcodeproj/xcshareddata/xcschemes/ReactExample.xcscheme
  examples/ReactExample/ios/ReactExample/AppDelegate.h
  examples/ReactExample/ios/ReactExample/AppDelegate.m
  examples/ReactExample/ios/ReactExample/Base.lproj/LaunchScreen.xib
  examples/ReactExample/ios/ReactExample/Images.xcassets/AppIcon.appiconset/Contents.json
  examples/ReactExample/ios/ReactExample/Info.plist
  examples/ReactExample/ios/ReactExample/main.m
  examples/ReactExample/ios/ReactExampleTests/Info.plist
  examples/ReactExample/ios/ReactExampleTests/ReactExampleTests.m
  examples/ReactExample/main.js
  examples/ReactExample/package-lock.json
  examples/ReactExample/package.json
  examples/ReactExample/run-android.sh
  scripts/test.sh
Labels: T-Test, T-Internal, cla: yes

#4110 Validate sync option 'user'
  CHANGELOG.md
  src/js_sync.hpp
  tests/js/session-tests.js
Labels: cla: yes

#4114 Remove `realm/react-native` "sub-package" / `ListView` component
  CHANGELOG.md
  react-native/.eslintrc.json
  react-native/android/build.gradle
  react-native/index.js
  react-native/listview.js
  react-native/package.json
  tests/ReactTestApp/tests/index.js
  tests/ReactTestApp/tests/listview-test.js
Labels: T-Internal, cla: yes

#4107 Remove typescript dependency from child packages and upgrade root version to latest
  CHANGELOG.md
  contrib/building.md
  integration-tests/tests/package.json
  package-lock.json
  package.json
  packages/realm-app-importer/package.json
  packages/realm-app-importer/src/AppImporter.ts
  packages/realm-common/package-lock.json
  packages/realm-common/package.json
  packages/realm-network-transport/package-lock.json
  packages/realm-network-transport/package.json
  packages/realm-react/example/package.json
  packages/realm-react/package.json
  packages/realm-web-integration-tests/harness/github.ts
  packages/realm-web-integration-tests/src/email-password-auth.test.ts
  packages/realm-web/package.json
Labels: cla: yes
