Repository realm/realm-js, pull requests merged in 2022-09, with the labels that each got.

#4850 Fix normalisation of `embedded` and `asymmetric` on `Realm#schema`
  integration-tests/tests/src/tests/sync/asymmetric.ts
  src/js_schema.hpp
Labels: T-Bug, cla: yes

#4872 Upgrade to RN 70
  example/.flowconfig
  example/.gitignore
  example/.node-version
  example/android/app/build.gradle
  example/android/app/src/main/jni/Android.mk
  example/android/app/src/main/jni/MainApplicationModuleProvider.cpp
  example/android/app/src/main/jni/MainApplicationModuleProvider.h
  example/android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  example/android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  example/android/app/src/main/jni/MainComponentsRegistry.cpp
  example/android/build.gradle
  example/android/gradle/wrapper/gradle-wrapper.jar
  example/android/gradle/wrapper/gradle-wrapper.properties
  example/ios/Podfile
  example/ios/Podfile.lock
  example/package-lock.json
  example/package.json
  integration-tests/environments/react-native/.gitignore
  integration-tests/environments/react-native/.node-version
  integration-tests/environments/react-native/android/app/build.gradle
  integration-tests/environments/react-native/android/app/src/main/jni/Android.mk
  integration-tests/environments/react-native/android/app/src/main/jni/CMakeLists.txt
  integration-tests/environments/react-native/android/app/src/main/jni/MainApplicationModuleProvider.cpp
  integration-tests/environments/react-native/android/app/src/main/jni/MainApplicationModuleProvider.h
  integration-tests/environments/react-native/android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  integration-tests/environments/react-native/android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  integration-tests/environments/react-native/android/app/src/main/jni/MainComponentsRegistry.cpp
  integration-tests/environments/react-native/android/build.gradle
  integration-tests/environments/react-native/android/gradle/wrapper/gradle-wrapper.jar
  integration-tests/environments/react-native/android/gradle/wrapper/gradle-wrapper.properties
  integration-tests/environments/react-native/ios/Podfile
  integration-tests/environments/react-native/package-lock.json
  integration-tests/environments/react-native/package.json
Labels: cla: yes

#4869 Update clang-format npm package version to match system clangd on newer Macs, and update code style to match
  CHANGELOG.md
  package-lock.json
  package.json
  src/common/object/strategies.hpp
  src/common/type_deduction.hpp
  src/js_auth.hpp
  src/js_collection.hpp
  src/js_observable.hpp
  src/jsc/jsc_class.hpp
  src/node/node_class.hpp
Labels: cla: yes

#4867 Mention v11 in README
  README.md
Labels: cla: yes

#4875 Reverting a bad merge in "import-app-before" hook of the integration tests
  integration-tests/tests/src/hooks/import-app-before.ts
Labels: T-Internal, cla: yes

#4877 Andrew/prime cache
  .github/workflows/pr-realm-js.yml
Labels: cla: yes

#4876 Stable roundtrip tests
  integration-tests/tests/src/tests/sync/mixed.ts
  integration-tests/tests/src/utils/sleep.ts
Labels: T-Test, cla: yes

#4887 Update prepare-release GHA workflow to override version
  .github/workflows/prepare-release.yml
Labels: T-Internal, cla: yes

#4888 [CI] Use a more specific cache key for vcpkg
  .github/workflows/pr-realm-js.yml
Labels: cla: yes

#4890 [CI] Use a unshallow fetch on the vcpkg submodule
  .github/workflows/pr-realm-js.yml
Labels: cla: yes

#4892 Fix Template Publish Workflow
  .github/workflows/publish-templates.yml
Labels: cla: yes

#4881 Refactored manual transaction tests
  integration-tests/tests/src/tests/transaction.ts
Labels: T-Test, cla: yes

#4894 Prepare for 10.21.0
  CHANGELOG.md
  dependencies.list
  package-lock.json
  package.json
  react-native/ios/RealmReact.xcodeproj/project.pbxproj
Labels: cla: yes

#4889 Adding a package to help build and run BaaS from source
  integration-tests/baas-test-server/.eslintignore
  integration-tests/baas-test-server/.eslintrc.json
  integration-tests/baas-test-server/.gitignore
  integration-tests/baas-test-server/README.md
  integration-tests/baas-test-server/index.ts
  integration-tests/baas-test-server/package-lock.json
  integration-tests/baas-test-server/package.json
  integration-tests/baas-test-server/tsconfig.json
  integration-tests/realm-apps/with-db-flx/secrets.json
  integration-tests/realm-apps/with-db/secrets.json
  lerna.json
Labels: cla: yes

#4896 Prepare for 10.21.0
  .github/workflows/publish-release.yml
  CHANGELOG.md
  vendor/.npmignore
Labels: cla: yes

#4900 Publish prebuilds to S3
  .github/workflows/publish-release.yml
Labels: cla: yes

#4902 Add Apple M1 prebuild variant
  .github/workflows/pr-realm-js.yml
Labels: cla: yes

#4898 Improving "publish release" workflow
  .github/workflows/publish-release.yml
  .gitignore
  scripts/extract-changelog.js
  scripts/extract-changelog.sh
Labels: T-Internal, cla: yes

#4840 Match types for User#callFunction implementation across platforms
  CHANGELOG.md
  docs/sync.js
  lib/email-password-auth-methods.js
  lib/user.js
  packages/realm-web/src/auth-providers/EmailPasswordAuth.ts
  tests/js/user-tests.js
  types/app.d.ts
  types/auth-providers.d.ts
Labels: cla: yes

#4910 Pinning NDK and use `--active-arch-only` on Android
  .github/workflows/pr-realm-js.yml
  CHANGELOG.md
  integration-tests/environments/react-native/harness/runner.js
Labels: T-Bug-Crash

#4915 Prepare for 10.21.1
  .github/workflows/publish-release.yml
  CHANGELOG.md
  dependencies.list
  package-lock.json
  package.json
  react-native/ios/RealmReact.xcodeproj/project.pbxproj
Labels: cla: yes

#4918 Update pr-realm-js to ignore scripts when building
  .github/workflows/pr-realm-js.yml
Labels: cla: yes

#4917 Prepare for 11.0.0-rc.2
  CHANGELOG.md
  dependencies.list
  package-lock.json
  package.json
  react-native/ios/RealmReact.xcodeproj/project.pbxproj
Labels: cla: yes

#4909 Append ClusterName to AppName for CI Tests
  integration-tests/.gitignore
  integration-tests/tests/src/utils/import-app.ts
  packages/realm-app-importer/src/AppImporter.ts
Labels: cla: yes

#4928 objectForPrimaryKey should return null instead of undefined
  CHANGELOG.md
  docs/realm.js
  src/js_realm.hpp
  tests/js/query-tests.js
  tests/js/realm-tests.js
  types/index.d.ts
Labels: Breaking, cla: yes

#4921 Mobile SDK is missing Realm.Credentials.apiKey() method
  CHANGELOG.md
  docs/sync.js
  packages/realm-web/CHANGELOG.md
  packages/realm-web/src/Credentials.ts
  packages/realm-web/src/tests/App.test.ts
  src/js_app_credentials.hpp
  types/app.d.ts
Labels: Breaking, cla: yes

#4920 Enclose all packages in `@realm` scope
  .github/workflows/package-unit-tests.yml
  .github/workflows/pr-realm-js.yml
  CHANGELOG.md
  example/package-lock.json
  example/package.json
  integration-tests/baas-test-server/package-lock.json
  integration-tests/environments/electron/package.json
  integration-tests/environments/node/package.json
  integration-tests/environments/react-native/package.json
  integration-tests/tests/package.json
  integration-tests/tests/src/utils/fetch.ts
  integration-tests/tests/src/utils/import-app.ts
  integration-tests/tests/tsconfig.json
  lib/dictionary.js
  lib/extensions.js
  lib/mongo-client.js
  lib/mutable-subscription-set.js
  package-lock.json
  package.json
  packages/realm-app-importer/package-lock.json
  packages/realm-app-importer/package.json
  packages/realm-app-importer/src/fetch.ts
  packages/realm-common/package-lock.json
  packages/realm-common/package.json
  packages/realm-network-transport/package-lock.json
  packages/realm-network-transport/package.json
  packages/realm-network-transport/src/dom/index.ts
  packages/realm-network-transport/src/react-native/index.ts
  packages/realm-react/package-lock.json
  packages/realm-react/package.json
  packages/realm-react/src/useQuery.tsx
  packages/realm-tools/package-lock.json
  packages/realm-web-integration-tests/harness/import-realm-app.ts
  packages/realm-web-integration-tests/package-lock.json
  packages/realm-web-integration-tests/package.json
  packages/realm-web-integration-tests/tsconfig.web.json
  packages/realm-web/package-lock.json
  packages/realm-web/package.json
  packages/realm-web/rollup.config.js
  packages/realm-web/src/App.ts
  packages/realm-web/src/Fetcher.ts
  packages/realm-web/src/MongoDBRealmError.ts
  packages/realm-web/src/dom/LocalStorage.ts
  packages/realm-web/src/dom/index.ts
  packages/realm-web/src/dom/tsconfig.json
  packages/realm-web/src/node/tsconfig.json
  packages/realm-web/src/tests/utils/MockNetworkTransport.ts
  packages/realm-web/tsconfig.json
Labels: cla: yes

#4911 Align on boolean property types
  CHANGELOG.md
  docs/realm.js
  install-tests/react-native/App.js
  src/js_realm.hpp
  tests/js/open-behavior-tests.js
  tests/js/realm-tests.js
  types/index.d.ts
Labels: Breaking, cla: yes

#4874 Add compatibitily matrix
  .github/pull_request_template.md
  COMPATIBILITY.md
  README.md
Labels: cla: yes

#4935 Add ARM/Linux build guide
  CHANGELOG.md
  contrib/building.md
Labels: cla: yes

#4946 Update compatibility matrix
  COMPATIBILITY.md
Labels: cla: yes

#4947 Fix `inMemory` test - follow-up to #4911
  tests/js/realm-tests.js
Labels: T-Test, cla: yes

#4954 Use CMake-JS parameters to deduce VCPKG triplet
  CMakeLists.txt
Labels: cla: yes

#4960 Upgrade Realm React dependencies
  packages/realm-react/CHANGELOG.md
  packages/realm-react/package-lock.json
  packages/realm-react/package.json
  packages/realm-react/src/__tests__/AppProvider.test.tsx
  packages/realm-react/src/__tests__/RealmProvider.test.tsx
  packages/realm-react/src/__tests__/useObjectHook.test.tsx
  packages/realm-react/src/__tests__/useObjectRender.test.tsx
  packages/realm-react/src/__tests__/useQueryHook.test.tsx
  packages/realm-react/src/__tests__/useQueryRender.test.tsx
Labels: cla: yes

#4963 Realm react contribution guide
  packages/realm-react/CHANGELOG.md
  packages/realm-react/CONTRIBUTING.md
Labels: cla: yes
