Repository realm/realm-js, pull requests merged in 2022-07, with the labels that each got.

#4695 Delete leftover `package.json` files
  integration-tests/tests/src/node/electron-package.json
  integration-tests/tests/src/node/node-package.json
  integration-tests/tests/src/node/rn-package.json
Labels: T-Internal, cla: yes

#4700 Closing connections after calling `return` on `AsyncIntegrator` returned from `watch`
  packages/realm-web/CHANGELOG.md
  packages/realm-web/src/Fetcher.ts
  packages/realm-web/src/services/MongoDBService/MongoDBCollection.ts
Labels: T-Bug, cla: yes

#4703 Fix types and add a test for flexible sync client reset
  CHANGELOG.md
  integration-tests/tests/src/tests/sync/flexible.ts
  integration-tests/tests/src/utils/expect-sync-error.ts
  types/index.d.ts
Labels: cla: yes

#4705 Update how-to-release.md
  contrib/how-to-release.md
Labels: cla: yes

#4707 Add fix for older Android Gradle plugin
  CHANGELOG.md
  react-native/android/build.gradle
  tests/ReactTestApp/android/build.gradle
  tests/ReactTestApp/android/gradle/wrapper/gradle-wrapper.properties
Labels: cla: yes

#4709 Upgrading `react-native-fs`
  CHANGELOG.md
  integration-tests/environments/react-native/package-lock.json
  integration-tests/environments/react-native/package.json
  packages/realm-common/package-lock.json
  tests/ReactTestApp/package.json
Labels: cla: yes

#4583 Upgrade `integration-tests/environment/react-native` to React Native 0.68.2
  .github/workflows/integration-tests.yml
  CHANGELOG.md
  integration-tests/environments/react-native/.bundle/config
  integration-tests/environments/react-native/.editorconfig
  integration-tests/environments/react-native/.gitattributes
  integration-tests/environments/react-native/.gitignore
  integration-tests/environments/react-native/.ruby-version
  integration-tests/environments/react-native/Gemfile
  integration-tests/environments/react-native/android/app/build.gradle
  integration-tests/environments/react-native/android/app/src/debug/AndroidManifest.xml
  integration-tests/environments/react-native/android/app/src/debug/java/com/realmreactnativetests/ReactNativeFlipper.java
  integration-tests/environments/react-native/android/app/src/main/AndroidManifest.xml
  integration-tests/environments/react-native/android/app/src/main/java/com/realmreactnativetests/MainActivity.java
  integration-tests/environments/react-native/android/app/src/main/java/com/realmreactnativetests/MainApplication.java
  integration-tests/environments/react-native/android/app/src/main/java/com/realmreactnativetests/newarchitecture/MainApplicationReactNativeHost.java
  integration-tests/environments/react-native/android/app/src/main/java/com/realmreactnativetests/newarchitecture/components/MainComponentsRegistry.java
  integration-tests/environments/react-native/android/app/src/main/java/com/realmreactnativetests/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  integration-tests/environments/react-native/android/app/src/main/jni/Android.mk
  integration-tests/environments/react-native/android/app/src/main/jni/MainApplicationModuleProvider.cpp
  integration-tests/environments/react-native/android/app/src/main/jni/MainApplicationModuleProvider.h
  integration-tests/environments/react-native/android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  integration-tests/environments/react-native/android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  integration-tests/environments/react-native/android/app/src/main/jni/MainComponentsRegistry.cpp
  integration-tests/environments/react-native/android/app/src/main/jni/MainComponentsRegistry.h
  integration-tests/environments/react-native/android/app/src/main/jni/OnLoad.cpp
  integration-tests/environments/react-native/android/app/src/main/res/drawable/rn_edit_text_material.xml
  integration-tests/environments/react-native/android/app/src/main/res/values/styles.xml
  integration-tests/environments/react-native/android/build.gradle
  integration-tests/environments/react-native/android/gradle.properties
  integration-tests/environments/react-native/android/gradle/wrapper/gradle-wrapper.jar
  integration-tests/environments/react-native/android/gradle/wrapper/gradle-wrapper.properties
  integration-tests/environments/react-native/android/gradlew
  integration-tests/environments/react-native/android/settings.gradle
  integration-tests/environments/react-native/ios/Podfile
  integration-tests/environments/react-native/ios/RealmReactNativeTests.xcodeproj/project.pbxproj
  integration-tests/environments/react-native/ios/RealmReactNativeTests/AppDelegate.m
  integration-tests/environments/react-native/ios/RealmReactNativeTests/AppDelegate.mm
  integration-tests/environments/react-native/ios/RealmReactNativeTests/Images.xcassets/AppIcon.appiconset/Contents.json
  integration-tests/environments/react-native/ios/RealmReactNativeTests/main.m
  integration-tests/environments/react-native/ios/RealmReactNativeTestsTests/RealmReactNativeTestsTests.m
  integration-tests/environments/react-native/package-lock.json
  integration-tests/environments/react-native/package.json
Labels: T-Internal, cla: yes

#4713 Upgrade `integration-tests/environment/react-native` to React Native 0.69.1
  CHANGELOG.md
  integration-tests/environments/react-native/.gitignore
  integration-tests/environments/react-native/.ruby-version
  integration-tests/environments/react-native/Gemfile
  integration-tests/environments/react-native/android/app/build.gradle
  integration-tests/environments/react-native/android/app/src/main/java/com/realmreactnativetests/MainActivity.java
  integration-tests/environments/react-native/android/app/src/main/java/com/realmreactnativetests/newarchitecture/MainApplicationReactNativeHost.java
  integration-tests/environments/react-native/android/app/src/main/jni/Android.mk
  integration-tests/environments/react-native/android/build.gradle
  integration-tests/environments/react-native/android/settings.gradle
  integration-tests/environments/react-native/ios/.xcode.env
  integration-tests/environments/react-native/ios/Podfile
  integration-tests/environments/react-native/ios/RealmReactNativeTests.xcodeproj/project.pbxproj
  integration-tests/environments/react-native/ios/RealmReactNativeTests/AppDelegate.mm
  integration-tests/environments/react-native/package-lock.json
  integration-tests/environments/react-native/package.json
Labels: cla: yes

#4717 Update `building.md` to most recent steps
  contrib/building.md
Labels: cla: yes

#4719 Fix Android debug docs
  contrib/debugging-cpp.md
Labels: cla: yes

#4716 [@realm/react] Add generic type parameters to hooks
  packages/realm-react/CHANGELOG.md
  packages/realm-react/src/AppProvider.tsx
  packages/realm-react/src/UserProvider.tsx
Labels: cla: yes

#4724 Fix Metro Config Dependency Blocker
  packages/metro-config/index.js
Labels: cla: yes

#4727 Make RN harness reverse ports when skipping runner
  integration-tests/environments/react-native/harness/runner.js
Labels: cla: yes

#4725 Flush RN UI queue on Android
  CHANGELOG.md
  package-lock.json
  package.json
  react-native/android/src/main/java/io/realm/react/RealmReactModule.java
  src/android/CMakeLists.txt
  src/android/io_realm_react_RealmReactModule.cpp
  src/android/io_realm_react_RealmReactModule.h
  src/android/jsc_override.cpp
  src/jsc/jsc_class.hpp
  src/jsc/jsc_externs.hpp
  src/jsc/jsc_function.hpp
Labels: cla: yes

#4722 Andrew/update example
  CHANGELOG.md
  example/.bundle/config
  example/.eslintrc.js
  example/.flowconfig
  example/.ruby-version
  example/Gemfile
  example/Gemfile.lock
  example/README.md
  example/__tests__/App-test.js
  example/android/app/_BUCK
  example/android/app/build.gradle
  example/android/app/src/debug/java/com/realmexample/ReactNativeFlipper.java
  example/android/app/src/main/AndroidManifest.xml
  example/android/app/src/main/java/com/realmexample/MainActivity.java
  example/android/app/src/main/java/com/realmexample/MainApplication.java
  example/android/app/src/main/java/com/realmexample/newarchitecture/MainApplicationReactNativeHost.java
  example/android/app/src/main/java/com/realmexample/newarchitecture/components/MainComponentsRegistry.java
  example/android/app/src/main/java/com/realmexample/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  example/android/app/src/main/jni/Android.mk
  example/android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  example/android/app/src/main/jni/MainComponentsRegistry.h
  example/android/app/src/main/res/values/strings.xml
  example/android/build.gradle
  example/android/gradlew.bat
  example/android/settings.gradle
  example/app.json
  example/app/components/TaskItem.tsx
  example/ios/Podfile
  example/ios/Podfile.lock
  example/ios/RealmExample.xcodeproj/project.pbxproj
  example/ios/RealmExample.xcodeproj/xcshareddata/xcschemes/RealmExample.xcscheme
  example/ios/RealmExample.xcworkspace/contents.xcworkspacedata
  example/ios/RealmExample.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  example/ios/RealmExample/AppDelegate.h
  example/ios/RealmExample/AppDelegate.mm
  example/ios/RealmExample/Images.xcassets/AppIcon.appiconset/Contents.json
  example/ios/RealmExample/Images.xcassets/Contents.json
  example/ios/RealmExample/Info.plist
  example/ios/RealmExample/LaunchScreen.storyboard
  example/ios/RealmExample/main.m
  example/ios/RealmExampleTests/Info.plist
  example/ios/RealmExampleTests/RealmExampleTests.m
  example/ios/_xcode.env
  example/package-lock.json
  example/package.json
  packages/metro-config/package-lock.json
  packages/metro-config/package.json
  tests/package-lock.json
Labels: cla: yes

#4742 Fix for integration tests with skip_runner true on iOS
  CHANGELOG.md
  integration-tests/environments/react-native/harness/runner.js
Labels: cla: yes
