Repository realm/realm-js, pull requests merged in 2022-06, with the labels that each got.

#4589 Initial renaming
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/hermes.yml
  CONTRIBUTING.md
  docs/sync.js
  integration-tests/tests/src/node/rn-package.json
  packages/realm-app-importer/README.md
  packages/realm-app-importer/src/cli.ts
  packages/realm-web-integration-tests/README.md
  packages/realm-web-integration-tests/harness/github.ts
  packages/realm-web-integration-tests/src/google-login.ts
  packages/realm-web/README.md
  packages/realm-web/package.json
  packages/realm-web/src/App.ts
  packages/realm-web/src/OAuth2Helper.ts
  packages/realm-web/src/User.ts
  packages/realm-web/src/index.ts
  packages/realm-web/src/tests/App.test.ts
  scripts/changelog-header.sh
  tests/js/encryption-tests.js
  tests/js/index.js
  tests/js/realm-tests.js
  types/app.d.ts
Labels: cla: yes

#4584 Documenting guidelines for testing & refactoring accordingly
  integration-tests/README.md
  integration-tests/tests/src/hooks/open-realm-before.ts
  integration-tests/tests/src/utils/open-realm.ts
Labels: cla: yes

#4581 Test Migration: Alias tests
  integration-tests/tests/src/tests/alias.ts
  integration-tests/tests/src/tests/index.ts
  tests/js/alias-tests.js
  tests/js/index.js
Labels: cla: yes

#4606 Update build-ios to use xcode 13.1
  CHANGELOG.md
  scripts/build-ios.sh
Labels: cla: yes

#4564 Asymmetric sync
  CHANGELOG.md
  docs/realm.js
  integration-tests/tests/src/tests/dynamic-schema-updates.ts
  integration-tests/tests/src/tests/index.ts
  integration-tests/tests/src/tests/sync/asymmetric.ts
  react-native/ios/RealmReact.xcodeproj/project.pbxproj
  src/js_realm.hpp
  src/js_schema.hpp
  src/js_sync.hpp
  types/index.d.ts
Labels: cla: yes

#4612 Updated cmake config to read arch from `NODE_ARCH`
  CHANGELOG.md
  CMakeLists.txt
  package.json
Labels: T-Internal, cla: yes

#4616 Realm.Configuration.sync can be a boolean
  CHANGELOG.md
  src/js_realm.hpp
Labels: cla: yes

#4615 Fix FLX error scenario tests (compensating writes)
  CHANGELOG.md
  integration-tests/tests/src/tests/sync/flexible.ts
Labels: cla: yes

#4614 Remove support for node.js v12 and earlier.
  CHANGELOG.md
  dependencies.list
  package-lock.json
  package.json
  src/node/node_value.hpp
Labels: cla: yes

#4624 Adding test verifing synced Realms opened as local
  integration-tests/tests/src/tests/index.ts
  integration-tests/tests/src/tests/sync/sync-as-local.ts
Labels: T-Test, cla: yes

#4613 Cleaning up: Remove old, unused scripts
  CHANGELOG.md
  package-lock.json
  package.json
  scripts/download-realm.js
  scripts/find-ios-device.rb
  scripts/find-ios-runtime.rb
  scripts/test-android.js
  scripts/xcode-download-realm.sh
Labels: cla: yes

#4631 Upgrade Example to RN 0.68.2
  CHANGELOG.md
  example/.editorconfig
  example/.eslintrc.js
  example/.gitattributes
  example/.gitignore
  example/.prettierrc.js
  example/.ruby-version
  example/Gemfile
  example/__tests__/App-test.tsx
  example/_bundle/config
  example/android/app/build.gradle
  example/android/app/src/debug/AndroidManifest.xml
  example/android/app/src/debug/java/com/realmtstemplate/ReactNativeFlipper.java
  example/android/app/src/main/AndroidManifest.xml
  example/android/app/src/main/java/com/realmtstemplate/MainActivity.java
  example/android/app/src/main/java/com/realmtstemplate/MainApplication.java
  example/android/app/src/main/java/com/realmtstemplate/newarchitecture/MainApplicationReactNativeHost.java
  example/android/app/src/main/java/com/realmtstemplate/newarchitecture/components/MainComponentsRegistry.java
  example/android/app/src/main/java/com/realmtstemplate/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  example/android/app/src/main/jni/Android.mk
  example/android/app/src/main/jni/MainApplicationModuleProvider.cpp
  example/android/app/src/main/jni/MainApplicationModuleProvider.h
  example/android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  example/android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  example/android/app/src/main/jni/MainComponentsRegistry.cpp
  example/android/app/src/main/jni/MainComponentsRegistry.h
  example/android/app/src/main/jni/OnLoad.cpp
  example/android/app/src/main/res/drawable/rn_edit_text_material.xml
  example/android/app/src/main/res/values/styles.xml
  example/android/build.gradle
  example/android/gradle.properties
  example/android/gradle/wrapper/gradle-wrapper.jar
  example/android/gradle/wrapper/gradle-wrapper.properties
  example/android/gradlew
  example/android/settings.gradle
  example/ios/Podfile
  example/ios/Podfile.lock
  example/ios/RealmTsTemplate.xcodeproj/project.pbxproj
  example/ios/RealmTsTemplate.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  example/ios/RealmTsTemplate/AppDelegate.m
  example/ios/RealmTsTemplate/AppDelegate.mm
  example/ios/RealmTsTemplate/main.m
  example/ios/RealmTsTemplateTests/RealmTsTemplateTests.m
  example/package-lock.json
  example/package.json
  example/tsconfig.json
Labels: cla: yes

#4626 callFunction argument validation
  src/js_user.hpp
  tests/js/user-tests.js
Labels: cla: yes

#4634 Refactored make_js_error into Object::create_error
  CHANGELOG.md
  src/js_realm.hpp
  src/js_subscriptions.hpp
  src/js_types.hpp
  src/js_util.hpp
Labels: T-Internal, cla: yes

#4635 Defaulting to host ip when running integration tests on React Native Android
  CHANGELOG.md
  integration-tests/environments/react-native/src/App.js
Labels: T-Internal, cla: yes

#4641 Fix a typo in flexible sync tests
  integration-tests/tests/src/tests/sync/flexible.ts
Labels: cla: yes

#4661 Pin BaaS in the Realm Web PR workflow
  .github/workflows/pr-realm-web.yml
Labels: T-Internal, cla: yes

#4660 Update realm.io/common to 0.1.2
  CHANGELOG.md
  package-lock.json
  package.json
  packages/realm-web/package.json
Labels: cla: yes

#4666 Add a checklist item for updating internal package versions
  .github/pull_request_template.md
Labels: cla: yes

#4663 Enable testNoMigrationOnSync
  CHANGELOG.md
  tests/js/app-tests.js
  tests/js/realm-tests.js
Labels: cla: yes

#4653 Implement polyfill for globalThis
  .eslintrc.json
  CHANGELOG.md
  lib/mongo-client.js
  package-lock.json
  package.json
  packages/realm-common/package-lock.json
  packages/realm-common/package.json
  packages/realm-common/src/index.ts
  packages/realm-common/src/node/index.ts
  packages/realm-common/src/safeGlobalThis.ts
  packages/realm-network-transport/package.json
  packages/realm-network-transport/rollup.config.js
  packages/realm-network-transport/src/dom/index.ts
  packages/realm-network-transport/src/react-native/index.ts
  packages/realm-react/package-lock.json
  packages/realm-tools/package-lock.json
  packages/realm-web-integration-tests/package-lock.json
  packages/realm-web/.eslintrc.json
  packages/realm-web/package.json
  packages/realm-web/src/dom/LocalStorage.ts
  packages/realm-web/src/dom/index.ts
Labels: cla: yes

#4672 Update package.json to discard tag_prefix to make npm binary mirroring work
  CHANGELOG.md
  package.json
Labels: cla: yes

#4674 Fix toJSON behaviour for Dictionary on JSC pre-v11 (fixes #4658)
  integration-tests/tests/src/tests/dictionary.ts
  lib/dictionary.js
  lib/extensions.js
  package-lock.json
  package.json
  packages/realm-common/package.json
  packages/realm-common/src/symbols.ts
  packages/realm-network-transport/package.json
  packages/realm-react/package.json
  packages/realm-web/package.json
Labels: cla: yes

#4670 Documentation: useMemo expects a function
  packages/realm-react/README.md
Labels: cla: yes

#4684 Fix null handling in toJSON (fixes #4682)
  CHANGELOG.md
  integration-tests/tests/src/tests/serialization.ts
  lib/extensions.js
Labels: cla: yes

#4687 Fixing analytics tests
  CHANGELOG.md
  integration-tests/tests/src/node/analytics.ts
  integration-tests/tests/src/node/fixtures/electron/node_modules/electron/package.json
  integration-tests/tests/src/node/fixtures/electron/package.json
  integration-tests/tests/src/node/fixtures/node/package.json
  integration-tests/tests/src/node/fixtures/react-native/node_modules/react-native/package.json
  integration-tests/tests/src/node/fixtures/react-native/package.json
  integration-tests/tests/src/typings.d.ts
  scripts/submit-analytics.js
Labels: T-Internal, cla: yes

#4688 Adding type checking to the realm-app-importer
  CHANGELOG.md
  packages/realm-app-importer/package-lock.json
  packages/realm-app-importer/package.json
  packages/realm-app-importer/src/AppImporter.ts
Labels: T-Internal, cla: yes

#4686 Fix android test app failing to build
  CHANGELOG.md
  integration-tests/environments/react-native/android/app/src/main/AndroidManifest.xml
  integration-tests/environments/react-native/android/build.gradle
Labels: cla: yes
