Repository realm/realm-js, pull requests merged in 2022-10, with the labels that each got.

#4979 Update test for breaking change
  packages/realm-react/src/__tests__/useObjectRender.test.tsx
Labels: cla: yes

#4901 Align How Enums are Defined
  CHANGELOG.md
  lib/extensions.js
  types/index.d.ts
Labels: Breaking, cla: yes

#4821 Remove the type for the `Object#_objectId`
  .github/workflows/pr-realm-react.yml
  .github/workflows/publish-realm-react.yml
  CHANGELOG.md
  integration-tests/tests/src/tests/class-models.ts
  lib/extensions.js
  packages/realm-react/src/cachedCollection.ts
  src/js_realm_object.hpp
  tests/js/linkingobjects-tests.js
  types/index.d.ts
Labels: Breaking, cla: yes

#4958 Fix #4513
  packages/realm-react/CHANGELOG.md
  packages/realm-react/src/useObject.tsx
  packages/realm-react/src/useQuery.tsx
Labels: cla: yes

#4982 Add test case for plain objects defined in lists
  packages/realm/src/tests/list.test.ts
Labels: cla: yes

#4987 Remove Deprecated Methods:
  CHANGELOG.md
  docs/realm.js
  docs/sync.js
  lib/email-password-auth-methods.js
  packages/realm-web-integration-tests/src/credentials.test.ts
  packages/realm-web-integration-tests/src/google-login.ts
  packages/realm-web-integration-tests/src/user.test.ts
  packages/realm-web/src/Credentials.ts
  packages/realm-web/src/tests/Credentials.test.ts
  packages/realm-web/src/tests/OAuth2Helper.test.ts
  src/js_app_credentials.hpp
  src/js_realm.hpp
  tests/js/realm-tests.js
  tests/js/session-tests.js
  types/app.d.ts
Labels: cla: yes

#4990 Change callback names
  CHANGELOG.md
  docs/realm.js
  docs/sync.js
  integration-tests/tests/src/utils/expect-sync-error.ts
  packages/realm-react/src/__tests__/RealmProvider.test.tsx
  src/js_realm.hpp
  src/js_sync.hpp
  tests/js/app-tests.js
  tests/js/download-api-helper.js
  tests/js/migration-tests.js
  tests/js/realm-tests.js
  tests/js/session-tests.js
  types/index.d.ts
Labels: cla: yes

#4991 Change default client reset mode to 'discardLocal'
  CHANGELOG.md
  docs/sync.js
  src/js_sync.hpp
  tests/js/session-tests.js
Labels: cla: yes

#4980 Test case: Dictionary set corner cases
  integration-tests/tests/src/tests/dictionary.ts
  packages/realm/src/types.ts
Labels: cla: yes

#4996 Updating "bin" of the "realm-app-importer"
  packages/realm-app-importer/package.json
Labels: T-Internal, cla: yes

#4993 Update `SortDescriptor` type to match implementation
  types/index.d.ts
Labels: T-Bug, cla: yes

#4997 Improve toJSON functionality and remove JSONSerializerReplacer
  CHANGELOG.md
  integration-tests/tests/src/tests/dictionary.ts
  integration-tests/tests/src/tests/serialization.ts
  lib/dictionary.js
  lib/extensions.js
  src/js_realm_object.hpp
  types/index.d.ts
Labels: Breaking, cla: yes

#5004 Support importing values with the app importer
  integration-tests/tests/src/utils/import-app.ts
  packages/realm-app-importer/src/AppImporter.ts
Labels: T-Internal, cla: yes

#5003 Add _updateSchema functionality
  packages/bindgen/spec.yml
  packages/realm/src/Realm.ts
  packages/realm/src/tests/updateschema.test.ts
Labels: cla: yes

#4966 Add toJSON implementation and testing
  integration-tests/tests/src/schemas/playlist-with-songs-with-ids.ts
  integration-tests/tests/src/schemas/playlist-with-songs.ts
  integration-tests/tests/src/tests/dictionary.ts
  integration-tests/tests/src/tests/serialization.ts
  packages/realm/src/Dictionary.ts
  packages/realm/src/JSONCacheMap.ts
  packages/realm/src/Object.ts
  packages/realm/src/OrderedCollection.ts
Labels: cla: yes

#4999 Update types for min, max, avg & sum
  CHANGELOG.md
  types/index.d.ts
Labels: cla: yes

#5008 Removing `writeCopyTo` overload from types
  types/index.d.ts
Labels: Breaking, cla: yes

#5014 Prepare for 10.22.0
  CHANGELOG.md
  dependencies.list
  package-lock.json
  package.json
  react-native/ios/RealmReact.xcodeproj/project.pbxproj
Labels: cla: yes

#4868 workflows: instructions for release process
  contrib/how-to-release.md
Labels: cla: yes

#5010 Mention the missing support of RHEL 7
  README.md
Labels: cla: yes

#4925 Fixing prebuilds env
  .github/workflows/pr-realm-js.yml
Labels: cla: yes

#4907 @realm/react 0.4.0-rc.0
  packages/realm-react/CHANGELOG.md
  packages/realm-react/README.md
  packages/realm-react/package-lock.json
  packages/realm-react/package.json
Labels: cla: yes

#5018 Prepare for 11.0.0
  CHANGELOG.md
  dependencies.list
  package-lock.json
  package.json
Labels: cla: yes

#5000 Allow specifying required fields on Realm.Object
  CHANGELOG.md
  types/index.d.ts
Labels: cla: yes

#5023 Use MacOS 11 runner to have Xcode 12.5.1
  .github/workflows/install-test-react-native.yml
  .github/workflows/pr-realm-js.yml
Labels: cla: yes

#5022 A little v11 clean up
  .github/ISSUE_TEMPLATE/hermes.yml
  .github/pull_request_template.md
  COMPATIBILITY.md
  README.md
  package-lock.json
  package.json
  packages/babel-plugin/CHANGELOG.md
  packages/babel-plugin/LICENSE
  packages/babel-plugin/package-lock.json
  packages/babel-plugin/package.json
Labels: cla: yes

#5042 Prepare for 10.23.0
  CHANGELOG.md
  dependencies.list
  package-lock.json
  package.json
  react-native/ios/RealmReact.xcodeproj/project.pbxproj
Labels: cla: yes

#5043 Revert 5042 release/10.23.0
  CHANGELOG.md
  dependencies.list
  package-lock.json
  package.json
  react-native/ios/RealmReact.xcodeproj/project.pbxproj
Labels: cla: yes
