Repository realm/realm-js, pull requests merged in 2022-05, with the labels that each got.

#4542 Fix missing file behaviour options for flexible sync
  CHANGELOG.md
  types/index.d.ts
Labels: cla: yes

#4550 Backport of `NotificationBucket`
  CHANGELOG.md
  integration-tests/tests/.mocharc.json
  integration-tests/tests/src/index.ts
  integration-tests/tests/src/typings.d.ts
  react-native/ios/RealmReact/RealmReact.mm
  src/js_dictionary.hpp
  src/js_list.hpp
  src/js_notifications.hpp
  src/js_realm_object.hpp
  src/js_results.hpp
  src/js_set.hpp
  src/jsc/jsc_init.cpp
Labels: T-Internal, cla: yes

#4551 Use NotificationBucket for App & User
  src/js_app.hpp
  src/js_dictionary.hpp
  src/js_list.hpp
  src/js_notifications.hpp
  src/js_realm_object.hpp
  src/js_results.hpp
  src/js_set.hpp
  src/js_user.hpp
  src/jsc/jsc_init.cpp
Labels: T-Internal, cla: yes

#4522 Implement User/App listener
  .vscode/launch.json
  CHANGELOG.md
  docs/sync.js
  packages/realm-web/src/App.ts
  packages/realm-web/src/User.ts
  src/js_app.hpp
  src/js_dictionary.hpp
  src/js_list.hpp
  src/js_notifications.hpp
  src/js_realm_object.hpp
  src/js_results.hpp
  src/js_set.hpp
  src/js_sync.hpp
  src/js_user.hpp
  src/jsc/jsc_init.cpp
  tests/js/app-tests.js
  types/app.d.ts
Labels: cla: yes

#4555 Remove deprecated keys from the React Native config
  CHANGELOG.md
  react-native.config.js
Labels: T-Bug-Crash, cla: yes

#4426 Docs: Running React Native tests with Xcode
  integration-tests/environments/react-native/README.md
Labels: T-Doc, cla: yes

#4558 Fix typo in `testRealmConversion`
  CHANGELOG.md
  tests/js/session-tests.js
Labels: cla: yes

#4563 Add checklist step to run flexible sync tests
  .github/pull_request_template.md
Labels: cla: yes

#4562 Fix for Flexible Sync Configuration
  CHANGELOG.md
  integration-tests/tests/src/tests/sync/flexible.ts
  types/index.d.ts
Labels: cla: yes

#4557 UserProvider and useUser
  example/app/AppSync.tsx
  example/app/AppWrapperSync.tsx
  example/app/components/LoginScreen.tsx
  example/ios/RealmTsTemplate.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  packages/realm-react/CHANGELOG.md
  packages/realm-react/README.md
  packages/realm-react/package.json
  packages/realm-react/src/AppProvider.tsx
  packages/realm-react/src/RealmProvider.tsx
  packages/realm-react/src/UserProvider.tsx
  packages/realm-react/src/index.tsx
Labels: cla: yes

#4566 Explicitly add children to provider props
  packages/realm-react/CHANGELOG.md
  packages/realm-react/src/AppProvider.tsx
  packages/realm-react/src/RealmProvider.tsx
  packages/realm-react/src/UserProvider.tsx
  packages/realm-react/src/__tests__/RealmProvider.test.tsx
Labels: cla: yes

#4569 Remove unnecessary steps from GHA workflow
  .github/workflows/publish-realm-react.yml
Labels: cla: yes

#4570 Update README for `@realm/react` to use valid JSX
  packages/realm-react/README.md
Labels: T-Doc, cla: yes

#4575 Expose realm ref when using RealmProvider in @realm/react
  packages/realm-react/CHANGELOG.md
  packages/realm-react/README.md
  packages/realm-react/src/AppProvider.tsx
  packages/realm-react/src/RealmProvider.tsx
  packages/realm-react/src/__tests__/AppProvider.test.tsx
  packages/realm-react/src/__tests__/RealmProvider.test.tsx
Labels: cla: yes

#4567 Update information for external contributors
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
Labels: cla: yes

#4538 [@realm/tools] Set up the package. Initial import of realm-schema.
  packages/realm-tools/.eslintignore
  packages/realm-tools/.eslintrc.json
  packages/realm-tools/.gitignore
  packages/realm-tools/CHANGELOG.md
  packages/realm-tools/LICENSE
  packages/realm-tools/README.md
  packages/realm-tools/package-lock.json
  packages/realm-tools/package.json
  packages/realm-tools/samples/default.realm
  packages/realm-tools/samples/dict.realm
  packages/realm-tools/src/realm-schema.ts
  packages/realm-tools/tsconfig.build.json
  packages/realm-tools/tsconfig.json
Labels: cla: yes

#4593 Simplify vcpkg acquisition and caching
  .github/workflows/pr-realm-js.yml
  CMakeLists.txt
Labels: cla: yes

#4568 Add `initialSubscriptions` sync config option to bootstrap initial set of flexible sync subscriptions
  CHANGELOG.md
  docs/flexible-sync.js
  docs/sync.js
  integration-tests/tests/src/tests/sync/flexible.ts
  lib/extensions.js
  src/js_realm.hpp
  src/js_subscriptions.hpp
  types/index.d.ts
Labels: cla: yes

#4603 Fix comment layout
  src/js_subscriptions.hpp
Labels: cla: yes

#4600 Switch to building with Xcode 13
  .github/workflows/install-test-react-native.yml
  .github/workflows/integration-tests.yml
  CHANGELOG.md
  Jenkinsfile
  contrib/building.md
Labels: cla: yes

#4594 Working with Github Actions
  contrib/assets/github-actions-menu.png
  contrib/working-with-github-actions.md
Labels: cla: yes

#4577 Remove ObjectSchema from PropertiesTypes
  CHANGELOG.md
  docs/realm.js
  types/index.d.ts
Labels: cla: yes

#4580 Type Fix for Returned Schemas
  CHANGELOG.md
  docs/realm.js
  integration-tests/tests/src/tests/dynamic-schema-updates.ts
  types/index.d.ts
Labels: cla: yes
