Repository realm/realm-js, pull requests merged in 2022-02, with the labels that each got.

#4279 Enable mixed tests for flexible sync
  CHANGELOG.md
  dependencies.list
  integration-tests/README.md
  integration-tests/realm-apps/with-db-flx/services/local-mongodb/config.json
  integration-tests/tests/src/hooks/import-app-before.ts
  integration-tests/tests/src/tests/sync/mixed.ts
  integration-tests/tests/src/tests/sync/upload-delete-download.ts
  integration-tests/tests/src/utils/import-app.ts
  packages/realm-app-importer/src/AppImportServer.ts
  packages/realm-app-importer/src/AppImporter.ts
Labels: cla: yes

#4298 Fix instances where SubscriptionSet was still referred to as Subscriptions
  CHANGELOG.md
  docs/realm.js
  integration-tests/tests/src/tests/sync/flexible.ts
  lib/extensions.js
  lib/subscription-set.js
  src/js_subscriptions.hpp
  src/js_sync.hpp
  types/index.d.ts
Labels: cla: yes

#4284 Fix logo in darkmode
  README.md
  logo-dark.svg
  logo.svg
  scripts/prepublishReadme.sh
Labels: cla: yes

#4296 Flexible sync code review changes
  integration-tests/tests/src/utils/expect-sync-error.ts
  src/js_subscriptions.hpp
  src/js_util.hpp
Labels: cla: yes

#4299 Enabling integration tests to import apps into atlas
  integration-tests/README.md
  integration-tests/realm-apps/with-db-flx/services/mongodb/config.json
  integration-tests/realm-apps/with-db-flx/services/mongodb/rules/test-database.Person.json
  integration-tests/realm-apps/with-db/services/local-mongodb/config.json
  integration-tests/realm-apps/with-db/services/mongodb/config.json
  integration-tests/realm-apps/with-db/services/mongodb/rules/test-database.test-collection.json
  integration-tests/tests/src/hooks/import-app-before.ts
  integration-tests/tests/src/tests/sync/flexible.ts
  integration-tests/tests/src/tests/sync/mixed.ts
  integration-tests/tests/src/typings.d.ts
  integration-tests/tests/src/utils/import-app.ts
  packages/realm-app-importer/src/cli.ts
Labels: T-Internal, cla: yes

#4305 Lock to Windows 2019 to fix integration tests
  .github/workflows/integration-tests.yml
Labels: cla: yes

#4313 `deleteUser` extended
  packages/realm-web-integration-tests/harness/index.ts
  packages/realm-web-integration-tests/src/user.test.ts
  packages/realm-web/src/App.ts
  packages/realm-web/src/User.ts
  packages/realm-web/src/tests/App.test.ts
Labels: T-Internal

#4317 Enabling strict (except strictFunctionTypes) in integration tests
  integration-tests/tests/src/schemas/person-and-dog-with-object-ids.ts
  integration-tests/tests/src/schemas/person-and-dogs.ts
  integration-tests/tests/src/schemas/playlist-with-songs-with-ids.ts
  integration-tests/tests/src/schemas/playlist-with-songs.ts
  integration-tests/tests/src/utils/import-app.test.ts
  integration-tests/tests/tsconfig.json
Labels: T-Internal, cla: yes

#4307 Upgraded Mocha Remote to fix serialization errors
  integration-tests/environments/electron/package-lock.json
  integration-tests/environments/electron/package.json
  integration-tests/environments/node/package-lock.json
  integration-tests/environments/node/package.json
  integration-tests/environments/react-native/package.json
  packages/realm-web-integration-tests/package-lock.json
  packages/realm-web-integration-tests/package.json
Labels: T-Internal, cla: yes

#4315 Remove use of destructuring on update as it doesn't work on React Native
  integration-tests/tests/src/tests/sync/mixed.ts
Labels: cla: yes

#4163 New analytics
  CHANGELOG.md
  README.md
  integration-tests/environments/node/index.js
  integration-tests/tests/src/node/analytics.ts
  integration-tests/tests/src/node/electron-package.json
  integration-tests/tests/src/node/index.ts
  integration-tests/tests/src/node/node-package.json
  integration-tests/tests/src/node/rn-package.json
  integration-tests/tests/src/typings.d.ts
  lib/index.js
  lib/submit-analytics.js
  package.json
  react-native/android/analytics.gradle
  react-native/android/build.gradle
  react-native/ios/RealmReact/RealmAnalytics.h
  react-native/ios/RealmReact/RealmAnalytics.mm
  react-native/ios/RealmReact/RealmReact.mm
  scripts/submit-analytics.js
  tests/js/analytics-tests.js
  tests/js/index.js
Labels: cla: yes

#4311 Delete user
  CHANGELOG.md
  dependencies.list
  docs/sync.js
  lib/app.js
  lib/browser/user.js
  packages/realm-web-integration-tests/harness/index.ts
  packages/realm-web-integration-tests/src/user.test.ts
  packages/realm-web/CHANGELOG.md
  packages/realm-web/src/App.ts
  packages/realm-web/src/User.ts
  packages/realm-web/src/routes.ts
  packages/realm-web/src/tests/App.test.ts
  src/js_app.hpp
  src/js_user.hpp
  tests/js/user-tests.js
  types/app.d.ts
Labels: cla: yes

#4321 Always call uploadAllLocalChanges/downloadAllServerChanges
  integration-tests/tests/src/tests/sync/upload-delete-download.ts
Labels: cla: yes

#4325 Update to newest docker image
  dependencies.list
Labels: cla: yes

#4338 Fix types for Object Listener
  .gitignore-revs
  packages/realm-react/src/useObject.tsx
  types/index.d.ts
Labels: cla: yes

#4308 Refactored serialization tests to use `openRealmBefore`
  integration-tests/environments/react-native/package-lock.json
  integration-tests/tests/src/tests/serialization.ts
Labels: T-Test, cla: yes

#4340 Add missing recursive flag to s3cmd
  .github/workflows/jsdoc-publish.yml
Labels: cla: yes

#4345 Add missing slash to remote path when publishing docs
  .github/workflows/jsdoc-publish.yml
Labels: cla: yes

#4347 Add missing trailing slashes on source directory for jsdoc publish
  .github/workflows/jsdoc-publish.yml
Labels: cla: yes

#4353 How to disable analytics
  contrib/building.md
Labels: cla: yes

#4362 Try a fix for incorrect CSS MIME type when uploading docs
  .github/workflows/jsdoc-publish.yml
Labels: cla: yes

#4366 Fix for Mixed binary roundtrip issue (#4278)
  CHANGELOG.md
  src/js_object_accessor.hpp
  src/js_types.hpp
  src/node/node_value.hpp
  tests/js/mixed-tests.js
Labels: cla: yes

#4348 Andrew/realmreact docs
  packages/realm-react/.eslintrc.json
  packages/realm-react/README.md
  packages/realm-react/package.json
  packages/realm-react/src/RealmProvider.tsx
  packages/realm-react/src/cachedCollection.ts
  packages/realm-react/src/cachedObject.ts
  packages/realm-react/src/index.tsx
  packages/realm-react/src/useObject.tsx
  packages/realm-react/src/useQuery.tsx
  packages/realm-react/src/useRealm.tsx
Labels: cla: yes

#4370 Added tests for Mixed with 16 and 32 bit data
  tests/js/mixed-tests.js
Labels: cla: yes
