Repository realm/realm-js, pull requests merged in 2022-04, with the labels that each got.

#4479 Fix type for add
  types/index.d.ts
Labels: cla: yes

#4486 Add more details to release docs
  contrib/how-to-release.md
Labels: cla: yes

#4493 Improve documentation for copyBundledRealmFiles
  CHANGELOG.md
  docs/realm.js
  types/index.d.ts
Labels: cla: yes

#4498 Update package.json to include a `unpkg` field
  packages/realm-web/README.md
  packages/realm-web/package.json
  packages/realm-web/scripts/postversion.ts
Labels: T-Enhancement, cla: yes

#4505 Make test ready for node 18
  CHANGELOG.md
  tests/js/app-tests.js
Labels: cla: yes

#4446 Fix for adding event listeners while in a write transaction
  packages/realm-react/CHANGELOG.md
  packages/realm-react/src/__tests__/useObjectRender.test.tsx
  packages/realm-react/src/__tests__/useQueryHook.test.tsx
  packages/realm-react/src/__tests__/useQueryRender.test.tsx
  packages/realm-react/src/cachedCollection.ts
  packages/realm-react/src/cachedObject.ts
  packages/realm-react/src/useObject.tsx
  packages/realm-react/src/useQuery.tsx
Labels: cla: yes

#4524 Add a section on profiling node JS code
  contrib/debugging-cpp.md
Labels: cla: yes

#4470 @realm/react AppProvider and useApp
  example/app/AppSync.tsx
  example/app/AppWrapperSync.tsx
  example/app/components/TaskList.tsx
  example/app/components/TaskManager.tsx
  packages/realm-react/CHANGELOG.md
  packages/realm-react/README.md
  packages/realm-react/src/AppProvider.tsx
  packages/realm-react/src/__tests__/AppProvider.test.tsx
  packages/realm-react/src/index.tsx
  packages/realm-react/src/useRealm.tsx
Labels: cla: yes

#4499 Add note on realm-core changelog
  contrib/how-to-release.md
Labels: cla: yes

#4509 Close sync sessions on hot reload to prevent race condition
  CHANGELOG.md
  react-native/ios/RealmReact/RealmReact.mm
  src/jsc/jsc_init.cpp
  src/jsc/jsc_init.h
Labels: Blocked, cla: yes

#4471 Update build script to use Xcode 12.4
  .github/workflows/integration-tests.yml
  CHANGELOG.md
  Jenkinsfile
  scripts/build-ios.sh
  tests/ReactTestApp/ios/ReactTestApp.xcodeproj/project.pbxproj
Labels: cla: yes

#4532 Move changelog to realm react
  CHANGELOG.md
  packages/realm-react/CHANGELOG.md
Labels: cla: yes

#4435 Class models: `Realm.Object#constructor` for JSI / Hermes
  integration-tests/tests/src/tests/sync/flexible.ts
  package-lock.json
  packages/realm-web/src/App.ts
  packages/realm-web/src/Fetcher.ts
  packages/realm-web/src/User.ts
  packages/realm-web/src/auth-providers/EmailPasswordAuth.ts
  src/js_realm.hpp
  src/jsi/jsi_class.hpp
  src/jsi/jsi_object.hpp
  src/jsi/jsi_return_value.hpp
  src/jsi/jsi_types.hpp
  tests/js/array-buffer-tests.js
  tests/js/object-tests.js
  tests/js/results-tests.js
  types/app.d.ts
Labels: Breaking, cla: yes

#4537 Class-based Models types
  CHANGELOG.md
  integration-tests/tests/src/tests/class-models.ts
  types/index.d.ts
Labels: Breaking, cla: yes
