Repository realm/realm-js, pull requests merged in 2023-03, with the labels that each got.

#5515 Refactored closing, deleting and reopening Realms
  integration-tests/tests/src/hooks/open-realm-before.ts
  integration-tests/tests/src/index.ts
  integration-tests/tests/src/mocha-internals.test.ts
  integration-tests/tests/src/tests/sync/flexible.ts
  integration-tests/tests/src/tests/sync/realm-conversions.ts
  integration-tests/tests/src/tests/sync/upload-delete-download.ts
  integration-tests/tests/src/typings.d.ts
  integration-tests/tests/src/utils/close-realm.ts
  integration-tests/tests/src/utils/open-realm.ts
Labels: cla: yes

#5530 Fetch `statusText` polyfill
  packages/realm-network-transport/src/DefaultNetworkTransport.ts
  packages/realm-network-transport/src/status-text.ts
  packages/realm/src/app-services/User.ts
Labels: cla: yes

#5529 Allow optional primary keys
  integration-tests/tests/src/tests/dictionary.ts
  integration-tests/tests/src/tests/objects.ts
  packages/realm/src/schema/normalize.ts
  packages/realm/src/schema/types.ts
  packages/realm/src/tests/schema-normalization.test.ts
Labels: cla: yes

#5526 Get realm/react to build in bindgen
  package.json
  packages/realm-react/package.json
  packages/realm-react/src/AppProvider.tsx
  packages/realm-react/src/UserProvider.tsx
  packages/realm-react/src/cachedCollection.ts
  packages/realm-react/src/helpers.ts
  packages/realm-react/src/useObject.tsx
  packages/realm-react/src/useQuery.tsx
  packages/realm/src/Realm.ts
  packages/realm/src/app-services/App.ts
  packages/realm/src/app-services/User.ts
Labels: cla: yes

#5549 Sync.flexible and deleteRealmIfMigrationNeeded is not an allowed combination
  CHANGELOG.md
  integration-tests/tests/src/tests/sync/app.ts
  src/js_realm.hpp
Labels: cla: yes

#5552 Renaming `master` → `main`
  .github/workflows/pr-realm-js.yml
  .github/workflows/prepare-release.yml
  .github/workflows/publish-containers.yml
  CHANGELOG.md
  README.md
  contrib/building.md
  contrib/debugging-cpp.md
  contrib/how-to-release.md
  contrib/logger/sync_logging.md
  example/app/models/Task.js
  example/app/models/Task.ts
  packages/realm-react/CHANGELOG.md
  packages/realm-react/CONTRIBUTING.md
  packages/realm-react/package.json
  packages/realm-web/CONTRIBUTING.md
  packages/realm-web/package.json
  packages/realm-web/scripts/postversion.ts
  packages/realm/RealmJS.podspec
  packages/realm/src/errors.ts
  templates/expo-template-js/README.md
  templates/expo-template-js/app/models/Task.js
  templates/expo-template-ts/README.md
  templates/expo-template-ts/app/models/Task.ts
  templates/react-native-template-realm-js/README.md
  templates/react-native-template-realm-js/template/app/models/Task.js
  templates/react-native-template-realm-ts/README.md
  templates/react-native-template-realm-ts/template/app/models/Task.ts
Labels: cla: yes

#5554 Prevent node 19 to hang under installation
  CHANGELOG.md
  scripts/submit-analytics.js
Labels: cla: yes

#5531 Allow user to use Xcode 13
  CHANGELOG.md
  src/ios/CMakeLists.txt
Labels: cla: yes

#5556 Update containers with more recent GCC compiler version (issue #5551)
  .github/workflows/pr-realm-js.yml
  .github/workflows/publish-containers.yml
  Dockerfile
  debian-multiarch-arm.Dockerfile
Labels: cla: yes

#5524 Fixed some types definition in bindgen
  integration-tests/tests/src/schemas/person-and-dog-with-object-ids.ts
  integration-tests/tests/src/schemas/person-and-dogs.ts
  packages/realm-tools/src/realm-schema.ts
  packages/realm/src/Realm.ts
Labels: cla: yes

#5561 Update launch.json
  .vscode/launch.json
Labels: cla: yes

#5560 Prepare for 11.5.2
  CHANGELOG.md
  COMPATIBILITY.md
  dependencies.list
  integration-tests/tests/src/tests/sync/app.ts
  package-lock.json
  package.json
  react-native/ios/RealmReact.xcodeproj/project.pbxproj
Labels: cla: yes

#5565 Adopting to change in `SyncManager#path_for_realm`
  integration-tests/tests/src/node/path.ts
  integration-tests/tests/src/utils/close-realm.ts
  packages/bindgen/spec.yml
  packages/realm/src/Realm.ts
  packages/realm/src/app-services/Sync.ts
  packages/realm/src/node/fs.ts
  packages/realm/src/platform/file-system.ts
  packages/realm/src/react-native/fs.ts
Labels: cla: yes

#5539 Green builds on CI via NPM workspaces
  .github/workflows/pr-linting.yml
  .github/workflows/pr-realm-js.yml
  integration-tests/environments/electron/package.json
  integration-tests/environments/node/package.json
  integration-tests/environments/react-native/package.json
  integration-tests/tests/package.json
  integration-tests/tests/src/tests/array-buffer.ts
  integration-tests/tests/src/tests/credentials/api-key.ts
  package-lock.json
  package.json
  packages/bindgen/CMakeLists.txt
  packages/bindgen/package.json
  packages/bindgen/src/realm_js_helpers.h
  packages/bindgen/src/realm_js_jsi_helpers.h
  packages/bindgen/tests/test.ts
  packages/realm-app-importer/package.json
  packages/realm-react/babel.config.json
  packages/realm-react/package.json
  packages/realm/package.json
  packages/realm/src/node/device-info.ts
  packages/realm/src/react-native/device-info.ts
  src/android/io_realm_react_RealmReactModule.h
Labels: cla: yes

#5592 Download the assisted_agg binary
  integration-tests/baas-test-server/index.ts
Labels: cla: yes

#5594 Import device-info platform module to React Native bundle
  packages/realm/src/react-native/index.ts
Labels: cla: yes

#5534 Fix example
  example/android/app/build.gradle
  example/android/settings.gradle
  example/app/components/TaskList.tsx
  example/app/models/Task.ts
  example/ios/Podfile
  example/ios/Podfile.lock
  example/ios/RealmExample.xcodeproj/project.pbxproj
  example/ios/RealmExample.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  example/metro.config.js
  example/package-lock.json
  example/package.json
  integration-tests/environments/react-native/package.json
  package-lock.json
  package.json
  packages/realm-react/package-lock.json
  packages/realm-react/package.json
  packages/realm-react/src/helper.ts
  packages/realm/package.json
Labels: T-Enhancement, cla: yes

#5598 Remove dependencies.list
  .github/workflows/pr-realm-js.yml
  .github/workflows/prepare-release.yml
  dependencies.list
  package-lock.json
  package.json
  packages/realm/package.json
  scripts/.npmignore
  scripts/build-android.js
  scripts/publish.sh
  scripts/set-version.sh
  scripts/start-sync-server.sh
  scripts/utils.sh
Labels: cla: yes

#5602 Testing
  .github/workflows/pr-realm-js.yml
  CHANGELOG.md
Labels: cla: yes

#5600 Prepare for 12.0.0-alpha.0
  .github/workflows/publish-release.yml
  CHANGELOG.md
  package-lock.json
  packages/realm-react/package.json
  packages/realm/package.json
Labels: cla: yes

#5603 Remove redundant `MongoDBCollection` tests.
  integration-tests/tests/src/tests/sync/user.ts
Labels: cla: yes

#5606 Reenable all tests
  integration-tests/tests/src/tests/sync/app.ts
Labels: cla: yes

#5608 Fix commonjs bundle
  CHANGELOG.md
  integration-tests/environments/node/index.cjs
  integration-tests/environments/node/package.json
  integration-tests/tests/package.json
  package-lock.json
  packages/realm-app-importer/package.json
  packages/realm-network-transport/package.json
  packages/realm-tools/package.json
  packages/realm-web/package.json
  packages/realm/package.json
Labels: cla: yes

#5614 Prepare for 12.0.0-alpha.1
  CHANGELOG.md
  package-lock.json
  packages/realm/package.json
Labels: cla: yes

#5610 Fix linting on CI
  .github/workflows/pr-linting.yml
  CHANGELOG.md
  package.json
  packages/realm-react/package.json
  packages/realm-web/src/App.ts
  packages/realm-web/src/Fetcher.ts
  packages/realm-web/src/User.ts
Labels: cla: yes

#5617 Fix Create Call Signature
  CHANGELOG.md
  example/app/components/TaskManager.tsx
  example/app/models/Task.ts
  example/package-lock.json
  example/package.json
  types/index.d.ts
Labels: cla: yes

#5599 Add support for compensating writes
  CHANGELOG.md
  integration-tests/tests/src/tests/sync/flexible.ts
  integration-tests/tests/src/utils/promise-handle.ts
  packages/bindgen/spec.yml
  packages/realm/src/assert.ts
  packages/realm/src/errors.ts
  packages/realm/src/index.ts
Labels: cla: yes

#5634 Fix shared realms
  CHANGELOG.md
  integration-tests/tests/src/tests.ts
  integration-tests/tests/src/tests/shared-realms.ts
  packages/realm/src/ClassMap.ts
  packages/realm/src/Realm.ts
  packages/realm/src/TypeHelpers.ts
Labels: cla: yes

#5636 Update how to run pod install
  integration-tests/environments/react-native/README.md
Labels: cla: yes

#5635 Add missing method on iOS
  CHANGELOG.md
  src/ios/platform.mm
Labels: cla: yes

#5643 Prepare for 11.7.0
  CHANGELOG.md
  COMPATIBILITY.md
  dependencies.list
  package-lock.json
  package.json
  react-native/ios/RealmReact.xcodeproj/project.pbxproj
Labels: cla: yes

#5637 Pinning chai to fix dictionary tests
  package-lock.json
  packages/bindgen/package.json
  packages/realm-common/package.json
  packages/realm-network-transport/package.json
  packages/realm-web-integration-tests/package-lock.json
  packages/realm-web-integration-tests/package.json
  packages/realm-web/package.json
  packages/realm/package.json
Labels: cla: yes

#5632 Added `SyncError.logUrl`
  CHANGELOG.md
  integration-tests/tests/src/tests/sync/flexible.ts
  packages/realm/src/errors.ts
Labels: cla: yes

#5650 Fix `mocha` dependencies
  integration-tests/environments/electron/package.json
  integration-tests/environments/node/package.json
  integration-tests/environments/react-native/package.json
  package-lock.json
  package.json
  packages/realm-web-integration-tests/package.json
Labels: cla: yes

#5628 Printing calling stack frame when accessing global `Realm`
  packages/realm/src/Realm.ts
Labels: cla: yes

#5652 Fix network transport bundle
  integration-tests/tests/package.json
  package-lock.json
  packages/bindgen/package.json
  packages/mocha-reporter/package.json
  packages/realm-app-importer/package.json
  packages/realm-network-transport/package.json
  packages/realm-network-transport/src/node/tsconfig.json
  packages/realm-network-transport/types/node/index.d.ts
  packages/realm-tools/package.json
  packages/realm-web-integration-tests/package.json
  packages/realm-web/package.json
  packages/realm/package.json
Labels: cla: yes

#5656 Throwing errors when using symbols as keys of dictionary
  integration-tests/tests/src/tests/dictionary.ts
  packages/realm/src/Dictionary.ts
Labels: cla: yes

#5655 Improvements to perf tests
  integration-tests/tests/src/performance-tests/property-reads.ts
Labels: cla: yes

#5657 Adopting `@realm/babel-plugin` to the changes in the v12 schema parser
  packages/babel-plugin/src/index.test.ts
  packages/babel-plugin/src/plugin/index.ts
  packages/babel-plugin/src/tests/generator/suite.ts
  packages/babel-plugin/src/tests/generator/variants.ts
Labels: cla: yes

#5648 Enable garbage collection between tests
  integration-tests/environments/node/index.cjs
  integration-tests/environments/node/index.mjs
Labels: T-Test, T-Internal, cla: yes

#5665 Make reproducible builds on iOS
  integration-tests/environments/react-native/package.json
  scripts/build-ios.sh
Labels: cla: yes

#5662 Added `App.get` method
  integration-tests/tests/src/tests.ts
  integration-tests/tests/src/tests/sync/app.ts
  packages/realm/src/Configuration.ts
  packages/realm/src/app-services/App.ts
  packages/realm/src/app-services/User.ts
Labels: cla: yes

#5661 Adds a deprecation to the global `WeakRef` constructor
  packages/realm/src/runtime.d.ts
Labels: cla: yes

#5664 Introducing `IterableWeakSet` and using it to close Realms when clearing test state
  packages/realm/src/IterableWeakRefs.ts
  packages/realm/src/Realm.ts
  packages/realm/src/internal.ts
Labels: cla: yes

#5663 Stop doing our own isValid check and let core handle it
  integration-tests/tests/src/tests/objects.ts
  packages/realm/src/PropertyHelpers.ts
Labels: cla: yes

#5658 Unit test workflow using NPM workspaces
  .github/workflows/package-unit-tests.yml
  packages/babel-plugin/package.json
  packages/bindgen/package.json
  packages/realm/package.json
Labels: cla: yes

#5660 Adding a `THROW_ON_GLOBAL_REALM` flag
  CHANGELOG.md
  packages/realm/src/Realm.ts
  packages/realm/src/flags.ts
Labels: cla: yes
