Repository realm/realm-js, pull requests merged in 2023-01, with the labels that each got.

#5216 Make integration tests conform to new parser
  integration-tests/tests/src/tests/class-models.ts
  integration-tests/tests/src/tests/dictionary.ts
  integration-tests/tests/src/tests/dynamic-schema-updates.ts
  integration-tests/tests/src/tests/realm-constructor.ts
  integration-tests/tests/src/tests/serialization.ts
  integration-tests/tests/src/tests/set.ts
  packages/realm/src/Configuration.ts
  packages/realm/src/assert.ts
  packages/realm/src/errors.ts
  packages/realm/src/schema/normalize.ts
  packages/realm/src/tests/schema-normalization.test.ts
  packages/realm/src/tests/schema-validation.test.ts
Labels: cla: yes

#5193 Update bug.yml
  .github/ISSUE_TEMPLATE/bug.yml
Labels: cla: yes

#5234 Moving platform specific tsconfigs back
  packages/realm/rollup.config.mjs
  packages/realm/src/node/tsconfig.json
  packages/realm/src/react-native/tsconfig.json
  packages/realm/src/tests/tsconfig.json
Labels: T-Internal, cla: yes

#5213 Assert NDK version #2
  .github/workflows/pr-realm-js.yml
  contrib/building.md
  scripts/build-android.js
Labels: cla: yes

#5150 Windows ccache
  .github/workflows/pr-realm-js.yml
Labels: cla: yes

#5233 Revisiting bindgen Metro config (+ re-enabling performance tests)
  integration-tests/environments/react-native/metro.config.js
  integration-tests/tests/package.json
  integration-tests/tests/src/index.ts
  integration-tests/tests/src/performance-tests/property-reads.ts
  package-lock.json
  packages/metro-config/index.js
Labels: T-Internal, cla: yes

#5208 Refactor useObject
  packages/realm-react/CHANGELOG.md
  packages/realm-react/src/__tests__/useObjectRender.test.tsx
  packages/realm-react/src/cachedObject.ts
  packages/realm-react/src/useObject.tsx
  packages/realm-react/tsconfig.json
Labels: cla: yes

#5249 Bindgen RN fetch implementation
  package-lock.json
  packages/bindgen/CMakeLists.txt
  packages/bindgen/package.json
  packages/bindgen/src/formatter.ts
  packages/bindgen/src/output-directory.ts
  packages/bindgen/src/templates/typescript.ts
  packages/bindgen/tsconfig.json
  packages/realm/package.json
  packages/realm/src/react-native/network.ts
  packages/realm/src/react-native/tsconfig.json
Labels: cla: yes

#5250 Fixing creation of named constuctors
  packages/realm/src/ClassMap.ts
Labels: cla: yes

#5215 Improve AppProvider and UserProvider rendering perf
  packages/realm-react/src/AppProvider.tsx
  packages/realm-react/src/UserProvider.tsx
Labels: cla: yes

#5277 Prepare for 11.3.2
  CHANGELOG.md
  dependencies.list
  package-lock.json
  package.json
  react-native/ios/RealmReact.xcodeproj/project.pbxproj
Labels: cla: yes

#5269 Stabilized References for Collections, Lists and Objects
  packages/realm-react/CHANGELOG.md
  packages/realm-react/src/__tests__/useObjectRender.test.tsx
  packages/realm-react/src/__tests__/useQueryRender.test.tsx
  packages/realm-react/src/cachedCollection.ts
  packages/realm-react/src/cachedObject.ts
  packages/realm-react/src/useObject.tsx
  packages/realm-react/src/useQuery.tsx
Labels: cla: yes

#5279 Reenable notification tests for dictionary
  CHANGELOG.md
  tests/.lock
  tests/js/dictionary-tests.js
  tests/realm-bundle.realm.backup-log
Labels: cla: yes

#5258 Testing Bindgen SDK on React Native
  integration-tests/tests/package.json
  integration-tests/tests/src/tests/credentials/jwt.ts
  integration-tests/tests/src/tests/listeners.ts
  package-lock.json
  package.json
  packages/bindgen/CMakeLists.txt
  packages/bindgen/node.cmake
  packages/bindgen/spec.yml
  packages/bindgen/src/realm_js_helpers.h
  packages/bindgen/src/realm_js_jsi_helpers.h
  packages/bindgen/src/templates/jsi.ts
  packages/bindgen/src/templates/node-wrapper.ts
  packages/bindgen/src/templates/typescript.ts
  packages/realm/package.json
  packages/realm/react-native.config.js
  packages/realm/rollup.config.mjs
  packages/realm/src/Realm.ts
  packages/realm/src/node/fs.ts
  packages/realm/src/platform/file-system.ts
  packages/realm/src/react-native/fs.ts
  scripts/build-android.js
  src/android/CMakeLists.txt
  src/android/io_realm_react_RealmReactModule.cpp
  src/android/platform.cpp
  src/ios/platform.mm
  src/node/platform.cpp
  src/platform.hpp
Labels: cla: yes

#5224 🔄 Synced file(s) with realm/ci-actions
  .github/ISSUE_TEMPLATE/feature.yml
  .github/advanced-issue-labeler.yml
  .github/auto_assign.yml
  .github/workflows/Issue-Needs-Attention.yml
  .github/workflows/auto-assign.yml
  .github/workflows/check-changelog.yml
  .github/workflows/issue-labeler.yml
  .github/workflows/no-response.yml
  LICENSE
Labels: cla: yes, no-changelog

#5280 Update size of Android binaries. Update compatibility matrix.
  CHANGELOG.md
  COMPATIBILITY.md
Labels: cla: yes

#5285 Migrate migration tests to integration tests
  integration-tests/tests/src/tests/index.ts
  integration-tests/tests/src/tests/migrations.ts
Labels: cla: yes

#5304 Prepare for 11.4.0
  CHANGELOG.md
  dependencies.list
  package-lock.json
  package.json
  react-native/ios/RealmReact.xcodeproj/project.pbxproj
Labels: cla: yes

#5303 Run pod-install in the PR workflow for IOS only
  .github/workflows/pr-realm-js.yml
  integration-tests/environments/react-native/package.json
Labels: cla: yes

#5306 Update Release Note for RN upgrade
  COMPATIBILITY.md
  contrib/how-to-release.md
Labels: cla: yes

#5298 Create Generic Workflows for Publishing Packages
  .github/workflows/prepare-package-release.yml
  .github/workflows/publish-babel-plugin.yml
  .github/workflows/publish-package-release.yml
  .github/workflows/publish-realm-react.yml
  .github/workflows/publish-realm-web.yml
  CHANGELOG.md
  scripts/extract-changelog.js
Labels: cla: yes

#5290 Migrate set tests to integration tests
  integration-tests/tests/src/tests/index.ts
  integration-tests/tests/src/tests/sets.ts
Labels: cla: yes

#5322 Prepare for realm-react-0.4.3
  packages/realm-react/CHANGELOG.md
  packages/realm-react/package.json
Labels: cla: yes

#5320 Survey ad
  README.md
Labels: cla: yes, no-changelog

#5282 Test of logical operators
  integration-tests/tests/src/tests/queries.ts
Labels: cla: yes

#5325 Test Migration: Results Tests
  integration-tests/tests/src/tests/index.ts
  integration-tests/tests/src/tests/results.ts
Labels: cla: yes

#5291 Update Build Xcode to 13.4.1
  .github/workflows/pr-realm-js.yml
  CHANGELOG.md
  contrib/building.md
  scripts/build-ios.sh
Labels: cla: yes

#5256 move mixed tests to integration tests
  integration-tests/tests/src/tests/index.ts
  integration-tests/tests/src/tests/mixed.ts
  tests/js/index.js
  tests/js/mixed-tests.js
Labels: cla: yes

#5330 [bindgen] iOS support
  .gitignore
  integration-tests/environments/react-native/Gemfile.lock
  integration-tests/environments/react-native/ios/.xcode.env
  integration-tests/environments/react-native/ios/RealmReactNativeTests.xcodeproj/project.pbxproj
  packages/bindgen/CMakeLists.txt
  packages/realm/RealmJS.podspec
  packages/realm/package.json
  packages/realm/react-native/ios/RealmReact/RealmReact.h
  packages/realm/react-native/ios/RealmReact/RealmReact.mm
  packages/realm/react-native/ios/RealmReact/RealmReact.xcconfig
  react-native/ios/.gitignore
  react-native/ios/Podfile
  react-native/ios/RealmReact.xcodeproj/project.pbxproj
  react-native/ios/RealmReact.xcodeproj/xcshareddata/xcschemes/RealmReact.xcscheme
  scripts/build-ios.sh
  src/ios/CMakeLists.txt
Labels: cla: yes

#5255 Move array-buffer tests to integration tests
  integration-tests/tests/src/tests/array-buffer.ts
  integration-tests/tests/src/tests/index.ts
  tests/js/array-buffer-tests.js
  tests/js/index.js
Labels: cla: yes

#5301 Support Flexible Sync
  integration-tests/tests/src/tests/sync/asymmetric.ts
  integration-tests/tests/src/tests/sync/flexible.ts
  integration-tests/tests/src/tests/sync/sync-as-local.ts
  packages/bindgen/spec.yml
  packages/bindgen/src/realm_js_helpers.h
  packages/realm/src/Configuration.ts
  packages/realm/src/ProgressRealmPromise.ts
  packages/realm/src/Realm.ts
  packages/realm/src/Results.ts
  packages/realm/src/app-services/BaseSubscriptionSet.ts
  packages/realm/src/app-services/MutableSubscriptionSet.ts
  packages/realm/src/app-services/Subscription.ts
  packages/realm/src/app-services/SubscriptionSet.ts
  packages/realm/src/app-services/Sync.ts
  packages/realm/src/app-services/SyncConfiguration.ts
  packages/realm/src/app-services/SyncSession.ts
  packages/realm/src/errors.ts
  packages/realm/src/index.ts
  packages/realm/src/internal.ts
  packages/realm/src/schema.ts
  packages/realm/src/schema/validate.ts
  packages/realm/src/tests/schema-validation.test.ts
Labels: cla: yes

#5344 Disable changelog checker
  .github/workflows/check-changelog.yml
Labels: cla: yes

#5337 use correct baseurl for tests
  integration-tests/tests/src/tests/sync/app.ts
  integration-tests/tests/src/utils/import-app.ts
  tests/js/object-tests.js
Labels: cla: yes

#5332 Cleanup Clusters and Apps every night
  .github/workflows/cleanup-clusters.yml
Labels: cla: yes, no-changelog

#5254 migrate dictionary tests to ts
  integration-tests/tests/src/tests/dictionary.ts
  packages/realm-app-importer/package-lock.json
  tests/js/dictionary-tests.js
  tests/js/index.js
Labels: cla: yes
