Repository realm/realm-js, pull requests merged in 2023-12, with the labels that each got.

#6308 Passing actions when expecting notifications in tests
  integration-tests/tests/src/tests/observable.ts
Labels: T-Test

#6312 Fix unit tests
  .github/workflows/package-unit-tests.yml
  .github/workflows/pr-coverage.yml
  .github/workflows/pr-linting.yml
  .github/workflows/pr-realm-js.yml
  .github/workflows/pr-realm-web.yml
  .github/workflows/prepare-templates-release.yml
  .github/workflows/publish-docs.yml
  .github/workflows/publish-package-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/publish-templates.yml
  integration-tests/tests/.mocharc.json
  integration-tests/tests/src/tests/sync/app.ts
  package-lock.json
  package.json
  packages/realm-app-importer/.mocharc.json
  packages/realm-web-integration-tests/.mocharc.json
  packages/realm/.mocharc.json
Labels: T-Test, T-Internal

#6313 Read core version from submodule
  packages/realm/dependencies.list
  packages/realm/package.json
  packages/realm/scripts/submit-analytics.mjs
Labels: T-Internal

#6315 Adding `inspect.custom` symbol on RealmObject and Collection on Node
  CHANGELOG.md
  integration-tests/tests/src/node/custom-inspect.ts
  integration-tests/tests/src/node/index.ts
  packages/realm/src/platform/node/custom-inspect.ts
  packages/realm/src/platform/node/index.ts
Labels: T-Enhancement

#6321 Upgraded mocha-remote to v1.8.0
  integration-tests/environments/electron/package.json
  integration-tests/environments/node/package.json
  integration-tests/environments/react-native/package.json
  package-lock.json
  packages/realm-web-integration-tests/package.json
Labels: T-Internal

#6310 Key path filtered notifications in `Object` and `Collection`
  CHANGELOG.md
  integration-tests/tests/src/setup-globals.ts
  integration-tests/tests/src/tests/observable.ts
  packages/realm/bindgen/js_opt_in_spec.yml
  packages/realm/src/Collection.ts
  packages/realm/src/Dictionary.ts
  packages/realm/src/Listeners.ts
  packages/realm/src/Object.ts
  packages/realm/src/ObjectListeners.ts
  packages/realm/src/OrderedCollection.ts
  packages/realm/src/app-services/SyncSession.ts
  packages/realm/src/tests/milestone-3.test.ts
Labels: T-Enhancement

#6326 Removing `tsx` from sub-packages
  integration-tests/baas-test-server/package.json
  integration-tests/environments/node/package.json
  package-lock.json
Labels: T-Internal

#6328 Update BaaS test server to authenticate automatically
  integration-tests/baas-test-server/index.ts
Labels: T-Internal

#5694 Add SSL sync config tests
  integration-tests/tests/src/node/index.ts
  integration-tests/tests/src/node/ssl.ts
Labels: cla: yes
