Repository realm/realm-js, pull requests merged in 2023-06, with the labels that each got.

#5862 Fix warning for deprecated namespace setting method in Android
  CHANGELOG.md
  packages/realm/react-native/android/build.gradle
  packages/realm/react-native/android/src/main/AndroidManifest.xml
Labels: cla: yes

#5772 Add Flexible Sync subscribe/unsubscribe APIs
  CHANGELOG.md
  integration-tests/tests/src/tests/sync/flexible.ts
  packages/realm/src/ProgressRealmPromise.ts
  packages/realm/src/Results.ts
  packages/realm/src/TimeoutPromise.ts
  packages/realm/src/app-services/BaseSubscriptionSet.ts
  packages/realm/src/app-services/MutableSubscriptionSet.ts
  packages/realm/src/app-services/SyncSession.ts
  packages/realm/src/index.ts
Labels: cla: yes

#5768 Fix User.callFunction JSDoc to match the v11+ API
  packages/realm/src/app-services/User.ts
Labels: cla: yes

#5849 [v11] Align sync connection parameters
  lib/utils.js
  src/android/platform.cpp
  src/ios/platform.mm
  src/js_app.hpp
  src/node/platform.cpp
  src/platform.hpp
Labels: cla: yes

#5883 Remove `Realm` namespace depreciations
  CHANGELOG.md
  packages/realm/src/Realm.ts
Labels: cla: yes

#5889 Prepare for 11.10.0
  CHANGELOG.md
  dependencies.list
  package-lock.json
  package.json
  react-native/ios/RealmReact.xcodeproj/project.pbxproj
Labels: cla: yes

#5898 Fix global `Realm` usage in integration tests
  integration-tests/tests/src/setup-globals.ts
  integration-tests/tests/src/tests/sync/app.ts
  integration-tests/tests/src/tests/sync/encryption.ts
  integration-tests/tests/src/tests/sync/realm.ts
  packages/realm/src/Realm.ts
Labels: cla: yes

#5896 Pick correct toolchain for Linux x86_64 builds
  CHANGELOG.md
  CMakeLists.txt
Labels: cla: yes

#5899 Prepare for 11.10.1
  CHANGELOG.md
  dependencies.list
  package-lock.json
  package.json
  react-native/ios/RealmReact.xcodeproj/project.pbxproj
Labels: cla: yes

#5878 Remove Sync Logger from AppProvider
  .github/workflows/package-unit-tests.yml
  example/app/AppSync.tsx
  example/app/components/LoginScreen.tsx
  example/app/models/Task.js
  example/app/models/Task.ts
  example/sync.config.js
  packages/realm-app-importer/src/AppConfigBuilder.ts
  packages/realm-react/CHANGELOG.md
  packages/realm-react/README.md
  packages/realm-react/src/AppProvider.tsx
  packages/realm-react/src/__tests__/helpers.ts
  packages/realm-react/src/__tests__/useAuth.test.tsx
  packages/realm-react/src/__tests__/useEmailPasswordAuth.test.tsx
  packages/realm-react/src/types.ts
  packages/realm-react/src/useAuth.tsx
  packages/realm-react/src/useAuthOperation.tsx
  packages/realm-react/src/useEmailPasswordAuth.tsx
Labels: cla: yes

#5719 Auth Hooks
  .github/workflows/package-unit-tests.yml
  example/App.tsx
  example/app/AppSync.tsx
  example/app/AppWrapperSync.tsx
  example/app/components/LoginScreen.tsx
  example/app/models/Task.js
  example/app/models/Task.ts
  example/index.js
  example/ios/Podfile.lock
  example/package.json
  example/sync.config.js
  package-lock.json
  package.json
  packages/realm-app-importer/src/AdminApiClient.ts
  packages/realm-app-importer/src/AppConfigBuilder.ts
  packages/realm-react/CHANGELOG.md
  packages/realm-react/README.md
  packages/realm-react/package.json
  packages/realm-react/src/AppProvider.tsx
  packages/realm-react/src/__tests__/helpers.ts
  packages/realm-react/src/__tests__/useAuth.test.tsx
  packages/realm-react/src/__tests__/useEmailPasswordAuth.test.tsx
  packages/realm-react/src/index.tsx
  packages/realm-react/src/types.ts
  packages/realm-react/src/useAuth.tsx
  packages/realm-react/src/useAuthOperation.tsx
  packages/realm-react/src/useEmailPasswordAuth.tsx
Labels: cla: yes

#5911 Quick Fixes for 0.5
  packages/realm-react/CHANGELOG.md
  packages/realm-react/package.json
  packages/realm-react/src/useAuth.tsx
  packages/realm-react/src/useAuthOperation.tsx
  packages/realm-react/src/useEmailPasswordAuth.tsx
Labels: cla: yes

#5915 Fix bugs, add enhancements in the Example app
  example/app/AppWrapperSync.tsx
  example/app/components/LoginScreen.tsx
  example/ios/Podfile.lock
  example/package.json
  package-lock.json
  packages/realm-react/CHANGELOG.md
  packages/realm-react/src/useEmailPasswordAuth.tsx
Labels: cla: yes

#5917 Prepare for realm-react-0.5.1
  packages/realm-react/CHANGELOG.md
  packages/realm-react/package.json
Labels: cla: yes

#5919 Update Templates to v6
  example/sync.config.js
  templates/expo-template/LICENSE
  templates/expo-template/app.json
  templates/expo-template/app/AppNonSync.tsx
  templates/expo-template/app/AppSync.tsx
  templates/expo-template/app/AppWrapperNonSync.tsx
  templates/expo-template/app/AppWrapperSync.tsx
  templates/expo-template/app/components/LoginScreen.tsx
  templates/expo-template/app/components/OfflineModeButton.tsx
  templates/expo-template/app/components/TaskManager.tsx
  templates/expo-template/app/models/Task.ts
  templates/expo-template/app/models/index.ts
  templates/expo-template/package.json
  templates/react-native-template/template/app/AppNonSync.tsx
  templates/react-native-template/template/app/AppSync.tsx
  templates/react-native-template/template/app/AppWrapperNonSync.tsx
  templates/react-native-template/template/app/AppWrapperSync.tsx
  templates/react-native-template/template/app/components/LoginScreen.tsx
  templates/react-native-template/template/app/components/OfflineModeButton.tsx
  templates/react-native-template/template/app/components/TaskManager.tsx
  templates/react-native-template/template/app/models/Task.ts
  templates/react-native-template/template/app/models/index.ts
  templates/react-native-template/template/package.json
  templates/scripts/sync_rn_ts_to_all_templates.sh
Labels: cla: yes

#5880 Add example app for WASM / Web Sync
  examples/example-react-task/.gitignore
  examples/example-react-task/README.md
  examples/example-react-task/craco.config.ts
  examples/example-react-task/package.json
  examples/example-react-task/public/favicon.ico
  examples/example-react-task/public/index.html
  examples/example-react-task/public/manifest.json
  examples/example-react-task/public/robots.txt
  examples/example-react-task/src/App.tsx
  examples/example-react-task/src/AuthenticatedApp.tsx
  examples/example-react-task/src/assets/logo.png
  examples/example-react-task/src/assets/screenshot-realm-web-sync-login.png
  examples/example-react-task/src/assets/screenshot-realm-web-sync-tasks.png
  examples/example-react-task/src/atlas-app-services/config.json
  examples/example-react-task/src/components/AddTaskForm.tsx
  examples/example-react-task/src/components/IntroText.tsx
  examples/example-react-task/src/components/NavBar.tsx
  examples/example-react-task/src/components/PageLayout.tsx
  examples/example-react-task/src/components/TaskItem.tsx
  examples/example-react-task/src/components/TaskList.tsx
  examples/example-react-task/src/hooks/useTaskManager.ts
  examples/example-react-task/src/index.tsx
  examples/example-react-task/src/models/Task.ts
  examples/example-react-task/src/pages/ErrorPage.tsx
  examples/example-react-task/src/pages/LoginPage.tsx
  examples/example-react-task/src/pages/TaskPage.tsx
  examples/example-react-task/src/react-app-env.d.ts
  examples/example-react-task/src/reportWebVitals.ts
  examples/example-react-task/src/setupTests.ts
  examples/example-react-task/src/styles/AddTaskForm.module.css
  examples/example-react-task/src/styles/App.module.css
  examples/example-react-task/src/styles/ErrorPage.module.css
  examples/example-react-task/src/styles/IntroText.module.css
  examples/example-react-task/src/styles/LoginPage.module.css
  examples/example-react-task/src/styles/NavBar.module.css
  examples/example-react-task/src/styles/PageLayout.module.css
  examples/example-react-task/src/styles/TaskItem.module.css
  examples/example-react-task/src/styles/TaskList.module.css
  examples/example-react-task/src/styles/TaskPage.module.css
  examples/example-react-task/src/styles/global.css
  examples/example-react-task/tsconfig.json
  package-lock.json
  package.json
Labels: cla: yes

#5916 Add missing enums for OpenRealmTimeOutBehavior
  CHANGELOG.md
  lib/extensions.js
Labels: cla: yes

#5779 Enable recommended `eslint-plugin-jsdoc` rules
  package-lock.json
  package.json
  packages/realm-react/.eslintrc.json
  packages/realm-react/package.json
  packages/realm-react/src/AppProvider.tsx
  packages/realm-react/src/RealmProvider.tsx
  packages/realm-react/src/index.tsx
  packages/realm-react/src/useAuth.tsx
  packages/realm-react/src/useEmailPasswordAuth.tsx
  packages/realm-react/src/useObject.tsx
  packages/realm-react/src/useQuery.tsx
  packages/realm-react/src/useRealm.tsx
  packages/realm/.eslintignore
  packages/realm/.eslintrc.json
  packages/realm/scripts/submit-analytics.mjs
  packages/realm/src/Collection.ts
  packages/realm/src/Configuration.ts
  packages/realm/src/Dictionary.ts
  packages/realm/src/InsertionModel.ts
  packages/realm/src/List.ts
  packages/realm/src/Object.ts
  packages/realm/src/OrderedCollection.ts
  packages/realm/src/Realm.ts
  packages/realm/src/Results.ts
  packages/realm/src/Set.ts
  packages/realm/src/TypeHelpers.ts
  packages/realm/src/Types.ts
  packages/realm/src/app-services/ApiKeyAuth.ts
  packages/realm/src/app-services/App.ts
  packages/realm/src/app-services/BaseSubscriptionSet.ts
  packages/realm/src/app-services/Credentials.ts
  packages/realm/src/app-services/EmailPasswordAuth.ts
  packages/realm/src/app-services/MongoDBCollection.ts
  packages/realm/src/app-services/MutableSubscriptionSet.ts
  packages/realm/src/app-services/PushClient.ts
  packages/realm/src/app-services/Subscription.ts
  packages/realm/src/app-services/SubscriptionSet.ts
  packages/realm/src/app-services/Sync.ts
  packages/realm/src/app-services/SyncConfiguration.ts
  packages/realm/src/app-services/SyncSession.ts
  packages/realm/src/app-services/User.ts
  packages/realm/src/assert.ts
  packages/realm/src/bson.ts
  packages/realm/src/decorators.ts
  packages/realm/src/errors.ts
  packages/realm/src/index.ts
  packages/realm/src/runtime.d.ts
  packages/realm/src/schema/from-binding.ts
  packages/realm/src/schema/types.ts
  packages/realm/src/schema/validate.ts
  packages/realm/type-tests/type-tests.ts
Labels: cla: yes

#5912 Enabling session multiplexing by default
  CHANGELOG.md
  packages/realm/bindgen/js_opt_in_spec.yml
  packages/realm/src/app-services/App.ts
Labels: cla: yes

#5927 Added RealmObject.entries()
  integration-tests/tests/src/tests/objects.ts
  packages/realm/src/Object.ts
Labels: cla: yes

#5926 Moving all valuable docs from `/types` into the SDK
  packages/realm-web/.gitignore
  packages/realm-web/package.json
  packages/realm-web/scripts/update-types.ts
  packages/realm-web/types/realm/.eslintrc.json
  packages/realm-web/types/realm/app.d.ts
  packages/realm-web/types/realm/auth-providers.d.ts
  packages/realm-web/types/realm/decorators.d.ts
  packages/realm-web/types/realm/index.d.ts
  packages/realm-web/types/realm/services.d.ts
  packages/realm-web/types/realm/types.d.ts
  packages/realm/src/Object.ts
  packages/realm/src/OrderedCollection.ts
  packages/realm/src/Realm.ts
  packages/realm/src/Results.ts
  packages/realm/src/Unmanaged.ts
  packages/realm/src/app-services/App.ts
  packages/realm/src/app-services/BaseSubscriptionSet.ts
  packages/realm/src/app-services/Credentials.ts
  packages/realm/src/app-services/EmailPasswordAuth.ts
  packages/realm/src/app-services/FunctionsFactory.ts
  packages/realm/src/app-services/Sync.ts
  packages/realm/src/app-services/SyncConfiguration.ts
  packages/realm/src/app-services/User.ts
  packages/realm/src/index.ts
  packages/realm/src/internal.ts
Labels: T-Doc, cla: yes

#5930 Fix failing `@realm/react` async unit test
  packages/realm-react/src/__tests__/useQueryRender.test.tsx
Labels: T-Test, cla: yes

#5935 Reenable list snapshot test
  integration-tests/tests/src/tests/list.ts
Labels: cla: yes

#5945 Update README.md
  README.md
Labels: cla: yes

#5947 Update README.md
  README.md
Labels: cla: yes

#5950 Fix Prepare Release Workflow
  .github/workflows/prepare-release.yml
Labels: cla: yes

#5951 Prepare for 12.0.0-rc.0
  CHANGELOG.md
  package-lock.json
  packages/realm/package.json
Labels: cla: yes

#5890 Add `baseFilePath` to app config
  integration-tests/tests/src/hooks/import-app-before.ts
  integration-tests/tests/src/node/path.ts
  package.json
  packages/realm/bindgen/js_opt_in_spec.yml
  packages/realm/bindgen/js_spec.yml
  packages/realm/scripts/submit-analytics.mjs
  packages/realm/src/app-services/App.ts
  packages/realm/src/platform/file-system.ts
  packages/realm/src/platform/node/fs.ts
  packages/realm/src/platform/react-native/fs.ts
  src/android/io_realm_react_RealmReactModule.cpp
  src/android/platform.cpp
  src/ios/platform.mm
  src/node/platform.cpp
  src/platform.hpp
Labels: cla: yes

#5956 Include CJS index files in the packaged source for Realm
  CHANGELOG.md
  packages/realm/package.json
Labels: cla: yes

#5938 Add missing dependencies to wasm example
  examples/example-react-task/craco.config.ts
  examples/example-react-task/src/pages/LoginPage.tsx
Labels: cla: yes

#5958 Prepare for 12.0.0-rc.1
  CHANGELOG.md
  package-lock.json
  packages/realm/package.json
Labels: cla: yes
