Repository realm/realm-js, pull requests merged in 2024-08, with the labels that each got.

#6801 RJS-2187: Add progress information to RealmProvider fallback.
  packages/realm-react/CHANGELOG.md
  packages/realm-react/package.json
  packages/realm-react/src/RealmProvider.tsx
  packages/realm-react/src/__tests__/RealmProvider.test.tsx
  packages/realm-react/src/__tests__/mocks.ts
  packages/realm-react/src/helpers.ts
Labels: cla: yes

#6804 RJS-2867: Add useProgress and tests
  packages/realm-react/CHANGELOG.md
  packages/realm-react/src/RealmContext.ts
  packages/realm-react/src/__tests__/helpers.ts
  packages/realm-react/src/__tests__/mocks.ts
  packages/realm-react/src/__tests__/useProgress.test.tsx
  packages/realm-react/src/index.tsx
  packages/realm-react/src/useProgress.tsx
Labels: cla: yes

#6833 Fix realm-react progress tests
  packages/realm-react/src/__tests__/mocks.ts
  packages/realm-react/src/__tests__/useProgress.test.tsx
  packages/realm-react/src/helpers.ts
  packages/realm/src/indirect.ts
Labels: cla: yes, no-changelog, no-jira-ticket

#6836 Prepare for 12.13.0
  CHANGELOG.md
  integration-tests/tests/src/tests/sync/open-behavior.ts
  package-lock.json
  packages/realm/package.json
Labels: cla: yes, no-jira-ticket

#6843 Prepare for realm-react-0.10.0
  package-lock.json
  packages/realm-react/CHANGELOG.md
  packages/realm-react/package.json
Labels: cla: yes, no-jira-ticket

#6849 Update expo instructions
  packages/realm/README.md
  packages/realm/src/platform/react-native/expo-go-detection.ts
Labels: cla: yes

#6851 RJS-2888: Fixing React scheduler's call to RN `CallInvoker`'s `invokeAsync` and upgrading our RNTA test app to React Native v0.75.1
  .github/workflows/pr-realm-js.yml
  CHANGELOG.md
  integration-tests/environments/react-native-test-app/android/gradle/wrapper/gradle-wrapper.properties
  integration-tests/environments/react-native-test-app/harness/react-native-cli.js
  integration-tests/environments/react-native-test-app/ios/Podfile.lock
  integration-tests/environments/react-native-test-app/package.json
  package-lock.json
  packages/realm-react/package.json
  packages/realm/binding/jsi/react_scheduler.cpp
  packages/realm/package.json
Labels: cla: yes

#6855 Prepare for 12.13.1
  CHANGELOG.md
  package-lock.json
  packages/realm/package.json
Labels: cla: yes, no-jira-ticket

#6869 RJS-2887: Avoid recreating Provider in createDynamicRealmProvider
  packages/realm-react/CHANGELOG.md
  packages/realm-react/src/RealmProvider.tsx
Labels: cla: yes

#6868 Throwing `RealmInExpoGoError` only when native module fails to load
  packages/realm/src/platform/react-native/binding.ts
  packages/realm/src/platform/react-native/expo-go-detection.ts
Labels: T-Internal, cla: yes, no-changelog, no-jira-ticket

#6870 Prepare for realm-react-0.10.1
  package-lock.json
  packages/realm-react/CHANGELOG.md
  packages/realm-react/package.json
Labels: cla: yes, no-jira-ticket
