Repository realm/realm-js, pull requests merged in 2024-03, with the labels that each got.

#6524 Followup to #6492, allowing "$$typeof" to be read from binding prior to injection
  CHANGELOG.md
  package-lock.json
  packages/realm/binding/index.js
  packages/realm/package.json
  packages/realm/src/platform/binding.ts
Labels: cla: yes

#6533 RPM-568: Add a workflow that verifies PR title
  .github/workflows/check-pr-title.yml
Labels: no-changelog

#6535 Suggesting array of categories and string union for LogCategory
  integration-tests/tests/src/tests/shared-realms.ts
  packages/realm/src/Logger.ts
  packages/realm/src/Realm.ts
Labels: cla: yes

#6536 🔄 Synced file(s) with realm/ci-actions
  .github/workflows/check-pr-title.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#6537 🔄 Synced file(s) with realm/ci-actions
  .github/workflows/issue-labeler.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#6548 Update verbage and cli command
  examples/node-telemetry/README.md
Labels: cla: yes

#6551 🔄 Synced file(s) with realm/ci-actions
  .github/workflows/lock-threads.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#6557 RJS-2761: upgrade puppeteer
  package-lock.json
  packages/realm-web-integration-tests/package.json
Labels: cla: yes

#6566 Suggestions for "nested collections in mixed"
  packages/realm/src/Collection.ts
  packages/realm/src/Dictionary.ts
  packages/realm/src/List.ts
  packages/realm/src/Object.ts
  packages/realm/src/OrderedCollection.ts
  packages/realm/src/PropertyHelpers.ts
  packages/realm/src/Realm.ts
  packages/realm/src/Results.ts
  packages/realm/src/Set.ts
  packages/realm/src/TypeHelpers.ts
Labels: cla: yes

#6576 Use `no-jira-ticket` label on PRs created by workflows
  .github/workflows/prepare-package-release.yml
  .github/workflows/prepare-release.yml
  .github/workflows/prepare-templates-release.yml
  .github/workflows/publish-package-release.yml
  .github/workflows/publish-release.yml
Labels: T-Internal, cla: yes, no-jira-ticket

#6575 Prepare for 12.7.0-rc.0
  CHANGELOG.md
  package-lock.json
  packages/realm/package.json
Labels: cla: yes, no-jira-ticket

#6580 RJS-2764: Replacing "object" overload on `Realm.setLogLevel` with a second optional `category` argument
  CHANGELOG.md
  packages/realm/src/Logger.ts
  packages/realm/src/Realm.ts
Labels: cla: yes
