Repository realm/realm-js, pull requests merged in 2024-04, with the labels that each got.

#6587 Replacing `changelog-header.sh` with a TypeScript equivalent
  .github/workflows/publish-package-release.yml
  .github/workflows/publish-release.yml
  CHANGELOG.header.md
  package.json
  scripts/prepend-changelog-header.ts
Labels: T-Internal, cla: yes, no-changelog, no-jira-ticket

#6588 RJS-2789: Surface errors when linking credentials fails
  package-lock.json
  packages/realm-web/CHANGELOG.md
  packages/realm-web/package.json
  packages/realm-web/src/App.ts
  packages/realm-web/src/Fetcher.ts
  packages/realm-web/src/tests/utils/MockFetch.ts
  packages/realm-web/src/tests/utils/index.ts
  packages/realm-web/tsconfig.json
  packages/realm/package.json
Labels: T-Bug, cla: yes

#6591 RJS-2788: Update base url in `realm-web`
  packages/realm-web/CHANGELOG.md
  packages/realm-web/src/App.ts
Labels: T-Enhancement, cla: yes

#6595 Update building.md to include instructions on installing `clang-format`
  contrib/building.md
Labels: T-Doc, cla: yes, no-changelog, no-jira-ticket

#6550 RJS-2673: Prevent flickering behavior in `RealmProvider`
  packages/realm-react/CHANGELOG.md
  packages/realm-react/src/UserProvider.tsx
  packages/realm/src/Listeners.ts
  packages/realm/src/app-services/User.ts
Labels: cla: yes

#6592 RJS-2727: Re-using anonymous users by default in `realm-web`
  package-lock.json
  package.json
  packages/realm-web-integration-tests/src/app.test.ts
  packages/realm-web/CHANGELOG.md
  packages/realm-web/src/App.ts
  packages/realm-web/src/Credentials.ts
  packages/realm-web/src/tests/App.test.ts
Labels: T-Bug

#6531 Upgrade actions to silence Node16 deprecation warning
  .github/workflows/install-test-react-native.yml
  .github/workflows/package-unit-tests.yml
  .github/workflows/pr-coverage.yml
  .github/workflows/pr-linting.yml
  .github/workflows/pr-realm-js.yml
  .github/workflows/pr-realm-web.yml
  .github/workflows/prepare-package-release.yml
  .github/workflows/prepare-release.yml
  .github/workflows/prepare-templates-release.yml
  .github/workflows/publish-containers.yml
  .github/workflows/publish-docs.yml
  .github/workflows/publish-package-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/publish-templates.yml
  .github/workflows/test-server.yml
Labels: T-Internal, cla: yes, no-jira-ticket

#6523 Adding more precise detection of Expo Go
  CHANGELOG.md
  packages/realm/src/platform/react-native/expo-go-detection.ts
  packages/realm/src/platform/react-native/index.ts
Labels: T-Enhancement, cla: yes, no-jira-ticket

#6606 Add a note to changelogs on the base URL change
  CHANGELOG.md
  packages/realm-web/CHANGELOG.md
Labels: T-Internal, cla: yes, no-jira-ticket

#6602 Publish with provenance statements
  .github/workflows/publish-package-release.yml
  .github/workflows/publish-release.yml
  CHANGELOG.md
  packages/babel-plugin/package.json
  packages/fetch/package.json
Labels: cla: yes, no-jira-ticket

#6619 Use CMake 3.29.2
  .github/workflows/pr-realm-js.yml
  CHANGELOG.md
Labels: cla: yes, no-jira-ticket

#6612 RJS-2784: Clear internal state to avoid crashes when React Native app is reloaded
  CHANGELOG.md
  packages/realm/src/Realm.ts
  packages/realm/src/platform/react-native/index.ts
Labels: cla: yes

#6605 RJS-2757: Add Apple Privacy Manifest
  CHANGELOG.md
  packages/realm/PrivacyInfo.xcprivacy
  packages/realm/RealmJS.podspec
  packages/realm/package.json
Labels: cla: yes

#6622 Prepare for 12.7.0
  CHANGELOG.md
  package-lock.json
  packages/realm/package.json
Labels: cla: yes, no-jira-ticket

#6597 Update to the new documentation URL
  CHANGELOG.md
  packages/babel-plugin/README.md
  packages/realm-react/README.md
  packages/realm-web/README.md
  packages/realm/README.md
Labels: cla: yes, no-jira-ticket

#6625 Fixing unstable test
  .github/workflows/pr-coverage.yml
  integration-tests/tests/src/tests/sync/geospatial.ts
  integration-tests/tests/src/tests/sync/sync-session.ts
Labels: cla: yes, no-changelog, no-jira-ticket

#6623 RJS-2143: Tests to clarify number conversion
  integration-tests/tests/src/tests/shared-realms.ts
Labels: cla: yes, no-changelog

#6632 Prepare for 12.7.1
  CHANGELOG.md
  package-lock.json
  packages/realm/package.json
Labels: cla: yes, no-jira-ticket

#6639 Add missing changelog header
  CHANGELOG.md
Labels: cla: yes, no-jira-ticket
