Repository realm/realm-js, pull requests merged in 2024-07, with the labels that each got.

#6721 Refactored type and property helpers
  packages/realm/src/PropertyHelpers.ts
  packages/realm/src/PropertyMap.ts
  packages/realm/src/TypeHelpers.ts
  packages/realm/src/internal.ts
  packages/realm/src/property-accessors/Array.ts
  packages/realm/src/property-accessors/Dictionary.ts
  packages/realm/src/property-accessors/Int.ts
  packages/realm/src/property-accessors/Mixed.ts
  packages/realm/src/property-accessors/Object.ts
  packages/realm/src/property-accessors/Set.ts
  packages/realm/src/property-accessors/default.ts
  packages/realm/src/property-accessors/types.ts
  packages/realm/src/type-helpers/Array.ts
  packages/realm/src/type-helpers/Bool.ts
  packages/realm/src/type-helpers/Data.ts
  packages/realm/src/type-helpers/Date.ts
  packages/realm/src/type-helpers/Decimal.ts
  packages/realm/src/type-helpers/Double.ts
  packages/realm/src/type-helpers/Float.ts
  packages/realm/src/type-helpers/Int.ts
  packages/realm/src/type-helpers/LinkingObjects.ts
  packages/realm/src/type-helpers/Mixed.ts
  packages/realm/src/type-helpers/Object.ts
  packages/realm/src/type-helpers/ObjectId.ts
  packages/realm/src/type-helpers/String.ts
  packages/realm/src/type-helpers/Uuid.ts
  packages/realm/src/type-helpers/array-buffer.ts
  packages/realm/src/type-helpers/default.ts
  packages/realm/src/type-helpers/null-passthrough.ts
  packages/realm/src/type-helpers/types.ts
Labels: T-Internal, cla: yes, no-changelog, no-jira-ticket

#6769 Test on Android using "release" configuration
  .github/workflows/pr-realm-js.yml
  integration-tests/environments/electron/package.json
  integration-tests/environments/node/package.json
  integration-tests/environments/react-native-test-app/package.json
  integration-tests/tests/src/tests/sync/flexible.ts
  package-lock.json
  package.json
  packages/realm-react/package.json
  packages/realm-web-integration-tests/package.json
  packages/realm/binding/android/build.gradle
  packages/realm/package.json
Labels: T-Internal, cla: yes, no-changelog, no-jira-ticket

#6743 RJS-2636: Add progress notifications and tests
  CHANGELOG.md
  integration-tests/environments/react-native-test-app/ios/Podfile.lock
  integration-tests/tests/package.json
  integration-tests/tests/src/hooks/authenticate-user-before.ts
  integration-tests/tests/src/setup-globals.ts
  integration-tests/tests/src/tests/sync/flexible.ts
  integration-tests/tests/src/tests/sync/sync-session.ts
  package-lock.json
  packages/realm/bindgen/js_opt_in_spec.yml
  packages/realm/src/ProgressRealmPromise.ts
  packages/realm/src/Realm.ts
  packages/realm/src/app-services/SyncSession.ts
Labels: cla: yes

#6784 Test collection and object listeners for updates on links
  integration-tests/tests/src/tests/observable.ts
  packages/realm/src/Collection.ts
  packages/realm/src/Object.ts
Labels: cla: yes, no-changelog, no-jira-ticket

#6771 Test on iOS using "release" configuration
  .github/workflows/pr-realm-js.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#6788 RJS-2861: Deprecate AppConfiguration.app and add app instance to App Provider
  CHANGELOG.md
  packages/realm-react/CHANGELOG.md
  packages/realm-react/src/AppProvider.tsx
  packages/realm-react/src/RealmProvider.tsx
  packages/realm-react/src/__tests__/AppProvider.test.tsx
  packages/realm/src/app-services/App.ts
Labels: cla: yes

#6792 Prepare for realm-react-0.9.0
  package-lock.json
  packages/realm-react/CHANGELOG.md
  packages/realm-react/package.json
Labels: cla: yes, no-jira-ticket

#6805 Prepare for 12.12.0
  CHANGELOG.md
  package-lock.json
  packages/realm/package.json
Labels: no-jira-ticket

#6812 RJS-2870: Remove an unused header from the iOS and unused import from Android binding
  CHANGELOG.md
  packages/realm/binding/android/src/main/java/io/realm/react/RealmReactModule.java
  packages/realm/binding/apple/RealmReactModule.mm
Labels: cla: yes

#6816 Prepare for 12.12.1
  CHANGELOG.md
  package-lock.json
  packages/realm/package.json
Labels: cla: yes, no-jira-ticket
