Repository realm/realm-js, pull requests merged in 2024-01, with the labels that each got.

#6348 `@realm/react` cleanup
  package-lock.json
  packages/realm-react/jest.config.json
  packages/realm-react/package.json
  packages/realm-react/src/AppProvider.tsx
  packages/realm-react/src/RealmProvider.tsx
  packages/realm-react/src/__tests__/AppProvider.test.tsx
  packages/realm-react/src/__tests__/RealmProvider.test.tsx
  packages/realm-react/src/__tests__/UserProvider.test.tsx
  packages/realm-react/src/__tests__/setup.ts
  packages/realm-react/src/__tests__/tsconfig.json
  packages/realm-react/src/__tests__/useAuth.test.tsx
  packages/realm-react/src/__tests__/useEmailPasswordAuth.test.tsx
  packages/realm-react/src/__tests__/useObjectHook.test.tsx
  packages/realm-react/src/__tests__/useObjectRender.test.tsx
  packages/realm-react/src/__tests__/useQueryHook.test.tsx
  packages/realm-react/src/__tests__/useQueryRender.test.tsx
  packages/realm-react/src/cachedCollection.ts
  packages/realm-react/src/cachedObject.ts
  packages/realm-react/src/helpers.ts
  packages/realm-react/src/index.tsx
  packages/realm-react/src/runtime.d.ts
  packages/realm-react/src/useAuth.tsx
  packages/realm-react/src/useAuthOperation.tsx
  packages/realm-react/src/useEmailPasswordAuth.tsx
  packages/realm-react/src/useObject.tsx
  packages/realm-react/src/useQuery.tsx
  packages/realm-react/src/useRealm.tsx
  packages/realm-react/tsconfig.json
Labels: T-Internal

#6365 Removed "build-dependencies" from `@realm/integration-tests` lint
  integration-tests/tests/package.json
Labels: T-Internal

#6390 Using BaaSaaS in the Realm JS PR workflow
  .github/actions/baas-test-server/.eslintrc.json
  .github/actions/baas-test-server/action.yml
  .github/actions/baas-test-server/package.json
  .github/actions/baas-test-server/start-server.js
  .github/actions/baas-test-server/stop-server.js
  .github/workflows/pr-realm-js.yml
  .github/workflows/test-server.yml
  integration-tests/baas-test-server/README.md
  integration-tests/baas-test-server/baasaas/assertions.ts
  integration-tests/baas-test-server/baasaas/client.ts
  integration-tests/baas-test-server/baasaas/request.ts
  integration-tests/baas-test-server/cli.ts
  integration-tests/baas-test-server/docker.ts
  integration-tests/baas-test-server/helpers.ts
  integration-tests/baas-test-server/index.ts
  integration-tests/baas-test-server/package.json
  integration-tests/environments/react-native/harness/runner.js
  integration-tests/environments/react-native/package.json
  integration-tests/tests/src/node/ssl.ts
  package-lock.json
Labels: T-Internal

#6395 BaaSaaS all the things ✊
  .github/workflows/package-unit-tests.yml
  .github/workflows/pr-coverage.yml
Labels: T-Test, T-Internal

#6402 Update `build-android.js` to use the `ANDROID_HOME` environment variable
  scripts/build-android.js
Labels: T-Internal

#6411 Upgrading the gradle wrapper for the `packages/realm/react-native` directory
  packages/realm/react-native/android/gradle/wrapper/gradle-wrapper.jar
  packages/realm/react-native/android/gradle/wrapper/gradle-wrapper.properties
  packages/realm/react-native/android/gradlew
  packages/realm/react-native/android/gradlew.bat
Labels: T-Internal, cla: yes

#6422 Removed unused dependencies from `@realm/app-importer`
  package-lock.json
  packages/realm-app-importer/package.json
  packages/realm-app-importer/src/AppImporter.ts
Labels: T-Internal, cla: yes

#6424 Removing `concurrently` as dependency from a few packages
  integration-tests/environments/electron/package.json
  integration-tests/environments/node/package.json
  integration-tests/tests/package.json
Labels: T-Internal, cla: yes

#6409 Upgrade `puppeteer` and remove `@types/puppeteer`
  package-lock.json
  packages/realm-web-integration-tests/harness/index.ts
  packages/realm-web-integration-tests/package.json
Labels: T-Internal, cla: yes

#6442 Prepare for 12.6.0
  CHANGELOG.md
  package-lock.json
  packages/realm/package.json
Labels: cla: yes

#6448 Updating the readme to reflect the Atlas Device SDK branding
  packages/realm/README.md
Labels: T-Internal, cla: yes
