Repository realm/realm-js, pull requests merged in 2024-06, with the labels that each got.

#6709 RJS-2835: Include immediatelyRunFileActions in opt-in list
  CHANGELOG.md
  packages/realm/bindgen/js_opt_in_spec.yml
Labels: cla: yes

#6711 Explicitly enable anonymous auth provider in tests
  integration-tests/tests/src/tests/sync/partition-values.ts
  integration-tests/tests/src/tests/sync/sync-session.ts
Labels: T-Internal, cla: yes, no-changelog, no-jira-ticket

#6649 Adding tests accessing `app.currentUser` from `App` and `User` listeners
  integration-tests/tests/src/tests/sync/app.ts
Labels: T-Test, cla: yes, no-changelog, no-jira-ticket

#6712 Enables Ccache for our RNTA on iOS
  .github/workflows/pr-realm-js.yml
  integration-tests/environments/react-native-test-app/ios/Podfile
  integration-tests/environments/react-native-test-app/ios/Podfile.lock
  integration-tests/environments/react-native-test-app/package.json
Labels: cla: yes, no-changelog, no-jira-ticket

#6715 RJS-2810: Add privacy manifest for Apple App Store
  CHANGELOG.md
  packages/realm/PrivacyInfo.xcprivacy
  packages/realm/RealmJS.podspec
  packages/realm/package.json
Labels: cla: yes

#6720 Fix starting local Docker
  integration-tests/baas-test-server/docker.ts
Labels: cla: yes, no-changelog, no-jira-ticket

#6723 Prepare for 12.10.0
  CHANGELOG.md
  package-lock.json
  packages/realm/package.json
Labels: cla: yes, no-jira-ticket

#6727 Update main package PR workflow to ignore unrelated packages
  .github/workflows/pr-realm-js.yml
Labels: T-Internal, cla: yes, no-changelog, no-jira-ticket

#6633 RJS-2717: Replaced lodash with lodash.isequal
  package-lock.json
  packages/realm-react/package.json
  packages/realm-react/src/AppProvider.tsx
  packages/realm-react/src/RealmProvider.tsx
Labels: cla: yes

#6731 Fixing `@realm/react` bundling issue from #6633
  packages/realm-react/rollup.config.js
  packages/realm-react/src/AppProvider.tsx
  packages/realm-react/src/RealmProvider.tsx
  packages/realm/src/platform/node/fs.ts
Labels: T-Internal, cla: yes, no-changelog, no-jira-ticket

#6714 RJS-2648: Add ability for Realm instance to be used in RealmProvider
  packages/realm-react/CHANGELOG.md
  packages/realm-react/src/RealmContext.ts
  packages/realm-react/src/RealmProvider.tsx
  packages/realm-react/src/__tests__/RealmProvider.test.tsx
  packages/realm-react/src/helpers.ts
  packages/realm-react/src/index.tsx
Labels: cla: yes

#6729 Prepare for 12.11.0
  .github/workflows/pr-realm-js.yml
  .github/workflows/publish-release.yml
  CHANGELOG.md
  package-lock.json
  packages/realm/package.json
Labels: cla: yes, no-jira-ticket

#6226 RJS-2618: additional test of IN
  integration-tests/tests/src/tests/queries.ts
Labels: cla: yes

#6735 Prepare for realm-react-0.8.0
  package-lock.json
  packages/realm-react/CHANGELOG.md
  packages/realm-react/package.json
Labels: cla: yes, no-jira-ticket

#6733 Exposing an internal API to get file ident of a `SyncSession`
  integration-tests/tests/src/tests/sync/sync-session.ts
  packages/realm/bindgen/js_opt_in_spec.yml
  packages/realm/src/app-services/SyncSession.ts
Labels: cla: yes, no-changelog, no-jira-ticket

#6745 Correct usage of RealmProvider in README.md
  packages/realm-react/README.md
Labels: cla: yes

#6746 Refactor PR workflow into separate test jobs
  .github/workflows/pr-realm-js.yml
  .gitignore
  integration-tests/environments/react-native-test-app/ios/Podfile.lock
  integration-tests/environments/react-native-test-app/package.json
  package-lock.json
  packages/realm/package.json
Labels: T-Internal, cla: yes, no-changelog, no-jira-ticket

#6753 RJS-2846: Fix path configuration when using sync
  CHANGELOG.md
  integration-tests/tests/src/tests/sync/realm.ts
  packages/realm/src/Realm.ts
Labels: cla: yes

#6756 Prepare for 12.11.1
  CHANGELOG.md
  package-lock.json
  packages/realm/package.json
Labels: cla: yes, no-jira-ticket

#6760 Update PR workflow to avoid saving a snapshot
  .github/workflows/pr-realm-js.yml
Labels: T-Internal, cla: yes, no-changelog, no-jira-ticket

#6766 Update PR template with item to tag docs team
  .github/pull_request_template.md
Labels: cla: yes, no-changelog, no-jira-ticket
