Repository realm/realm-js, pull requests merged in 2024-05, with the labels that each got.

#6643 Prepare for 12.8.0
  CHANGELOG.md
  package-lock.json
  packages/realm/package.json
Labels: cla: yes, no-jira-ticket

#6646 Fix unresolvable links in API reference docs and remove re-exports
  packages/realm-react/src/__tests__/useEmailPasswordAuth.test.tsx
  packages/realm/src/Logger.ts
  packages/realm/src/Realm.ts
  packages/realm/src/app-services/User.ts
  packages/realm/typedoc.json
Labels: cla: yes, no-changelog, no-jira-ticket

#6652 Prepare for 12.8.1-alpha.0
  CHANGELOG.md
  package-lock.json
  packages/realm/package.json
Labels: cla: yes, no-jira-ticket

#6659 Update OAuth2Helper to remove accessing the stitch prefix
  packages/realm-web/CHANGELOG.md
  packages/realm-web/src/OAuth2Helper.ts
Labels: cla: yes, no-jira-ticket

#6660 Fix GHA error when publishing package release
  .github/workflows/publish-package-release.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#6661 Fix realm/react changelog
  packages/realm-react/CHANGELOG.md
Labels: cla: yes, no-jira-ticket

#6668 Prepare for 12.8.1
  CHANGELOG.md
  package-lock.json
  packages/realm/package.json
Labels: cla: yes, no-jira-ticket

#6671 Upgrade @trunk/launcher to v1.3.1 to support Apple's versioning scheme for macOS
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cla: yes, no-jira-ticket

#6673 Adding --latest-local to the baas test server CLI
  integration-tests/baas-test-server/cli.ts
  integration-tests/baas-test-server/docker.ts
Labels: cla: yes, no-jira-ticket

#6674 Update expected error messages
  integration-tests/tests/src/tests/sync/app.ts
  integration-tests/tests/src/tests/sync/user.ts
  packages/realm-web-integration-tests/src/user.test.ts
Labels: no-changelog, no-jira-ticket

#6613 Combined: Support `Mixed` data type with collections
  CHANGELOG.md
  integration-tests/tests/src/tests/dictionary.ts
  integration-tests/tests/src/tests/list.ts
  integration-tests/tests/src/tests/mixed.ts
  integration-tests/tests/src/tests/observable.ts
  integration-tests/tests/src/tests/results.ts
  packages/realm/bindgen/js_opt_in_spec.yml
  packages/realm/bindgen/js_spec.yml
  packages/realm/bindgen/src/templates/base-wrapper.ts
  packages/realm/bindgen/src/templates/jsi.ts
  packages/realm/bindgen/src/templates/node.ts
  packages/realm/bindgen/src/templates/typescript.ts
  packages/realm/src/Collection.ts
  packages/realm/src/Dictionary.ts
  packages/realm/src/GeoSpatial.ts
  packages/realm/src/List.ts
  packages/realm/src/Object.ts
  packages/realm/src/OrderedCollection.ts
  packages/realm/src/PropertyHelpers.ts
  packages/realm/src/Realm.ts
  packages/realm/src/Results.ts
  packages/realm/src/Set.ts
  packages/realm/src/TypeHelpers.ts
  packages/realm/src/tests/collection-helpers.test.ts
Labels: cla: yes, no-jira-ticket

#6665 Fix performance tests
  integration-tests/tests/src/performance-tests/property-reads.ts
Labels: cla: yes, no-changelog, no-jira-ticket

#6676 Prepare for 12.9.0
  CHANGELOG.md
  package-lock.json
  packages/realm/package.json
Labels: cla: yes, no-jira-ticket

#6678 Add internal annotation to fix docs build
  .github/workflows/pr-linting.yml
  packages/realm/src/TypeHelpers.ts
Labels: cla: yes, no-changelog, no-jira-ticket

#6686 Simplify RealmJS.podspec to avoid passing the version
  packages/realm/RealmJS.podspec
Labels: T-Internal, no-jira-ticket

#6679 RJS-2397 (re-merge): Collections in mixed - synced tests
  integration-tests/tests/src/hooks/open-realm-before.ts
  integration-tests/tests/src/tests/sync/mixed.ts
Labels: cla: yes

#6692 Prepare for realm-web-2.0.1
  package-lock.json
  packages/realm-web/CHANGELOG.md
  packages/realm-web/package.json
Labels: cla: yes, no-jira-ticket

#6696 Prepare for 12.10.0-rc.0
  CHANGELOG.md
  package-lock.json
  packages/realm/package.json
Labels: cla: yes, no-jira-ticket
