Repository realm/realm-js, pull requests merged in 2025-08, with the labels that each got.

#7030 Upgrade GHA workflows to use Node v22
  .github/workflows/package-unit-tests.yml
  .github/workflows/pr-coverage.yml
  .github/workflows/pr-linting.yml
  .github/workflows/pr-realm-web.yml
  .github/workflows/prepare-templates-release.yml
  .github/workflows/publish-docs.yml
  .github/workflows/publish-package-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/publish-templates.yml
  .github/workflows/test-server.yml
  packages/realm-common/rollup.config.mjs
  packages/realm-react/rollup.config.js
  packages/realm-web/rollup.config.mjs
Labels: CI, cla: yes, no-jira-ticket

#7029 Pure C++ turbomodule
  .github/workflows/pr-realm-js.yml
  CHANGELOG.md
  integration-tests/environments/react-native-test-app/Gemfile
  integration-tests/environments/react-native-test-app/Gemfile.lock
  integration-tests/environments/react-native-test-app/android/gradle/wrapper/gradle-wrapper.properties
  integration-tests/environments/react-native-test-app/ios/Podfile.lock
  integration-tests/environments/react-native-test-app/package.json
  integration-tests/tests/package.json
  integration-tests/tests/tsconfig.common.json
  package-lock.json
  package.json
  packages/realm-react/package.json
  packages/realm-react/src/__tests__/RealmProvider.test.tsx
  packages/realm-react/src/useObject.tsx
  packages/realm-react/src/useQuery.tsx
  packages/realm/RealmJS.podspec
  packages/realm/binding/android/CMakeLists.txt
  packages/realm/binding/android/src/main/cpp/io_realm_react_RealmReactModule.cpp
  packages/realm/binding/android/src/main/cpp/io_realm_react_RealmReactPackage.cpp
  packages/realm/binding/android/src/main/java/io/realm/react/RealmReactModule.java
  packages/realm/binding/android/src/main/java/io/realm/react/RealmReactPackage.java
  packages/realm/binding/apple/RealmModuleProvider.mm
  packages/realm/binding/apple/RealmReactModule.mm
  packages/realm/binding/jsi/CxxRealmModule.cpp
  packages/realm/binding/jsi/CxxRealmModule.hpp
  packages/realm/binding/jsi/jsi_externs.hpp
  packages/realm/binding/jsi/jsi_init.h
  packages/realm/package.json
  packages/realm/src/platform/react-native/binding.ts
  packages/realm/src/scripts/build/android.ts
  packages/realm/src/scripts/build/apple.ts
  packages/realm/src/scripts/build/xcode.ts
Labels: T-Enhancement, cla: yes, no-jira-ticket

#7019 Support 16KB page size on Android 15+
  CHANGELOG.md
  packages/realm/binding/android/CMakeLists.txt
Labels: cla: yes
